    .globl  bq27421_xwd_2200_fw
bq27421_xwd_2200_fw:
    .incbin "/arch/arm/plat-lc/drivers/pmic/coulometer/bq27421_xwd_2200.bqfs"

    .globl bq27421_xwd_2200_fw_end
bq27421_xwd_2200_fw_end:

    .globl  bq27421_gy_2200_fw
bq27421_gy_2200_fw:
    .incbin "/arch/arm/plat-lc/drivers/pmic/coulometer/bq27421_gy_2200.bqfs"

    .globl bq27421_gy_2200_fw_end
bq27421_gy_2200_fw_end:

    .globl  bq27421_ds_2200_fw
bq27421_ds_2200_fw:
    .incbin "/arch/arm/plat-lc/drivers/pmic/coulometer/bq27421_ds_2200.bqfs"

    .globl bq27421_ds_2200_fw_end
bq27421_ds_2200_fw_end: