obj-$(CONFIG_COMIP_PMIC) += comip-pmic.o comip_xceiv_usb.o
obj-$(CONFIG_COMIP_CALIBRATION) += comip-calib.o
obj-$(CONFIG_BAT_ID_BQ2022A)	+= bq2022a-batid.o
obj-$(CONFIG_BATTERY_BQ27510) += bq27510_battery.o
obj-$(CONFIG_CW201X_BATTERY)  += cw201x_battery.o
obj-$(CONFIG_BATTERY_BQ27421) += bq27421_firmware.o bq27421_battery.o
obj-$(CONFIG_BATTERY_MAX17058) += max17058_battery.o
obj-$(CONFIG_CHARGER_BQ24158) += bq24158_charger.o
obj-$(CONFIG_CHARGER_BQ2419X) += bq2419x_charger.o
obj-$(CONFIG_CHARGER_BQ24296) += bq24296_charger.o
obj-$(CONFIG_CHARGER_NCP1851) += ncp1851_charger.o
obj-y += lc1100h/
obj-y += lc1100ht/
obj-y += lc1132/
obj-y += lc1160/

obj-$(CONFIG_BUCK_NCP6335) += ncp6335.o
obj-$(CONFIG_BUCK_FAN53555) += fan53555.o
