#ifndef __ASM_ARCH_BOARD_A310T_H__
#define __ASM_ARCH_BOARD_A310T_H__

#include <plat/mfp.h>
#include <plat/comipfb.h>

#if defined(CONFIG_COMIP_PROJECT_A310T)

/* PMIC&CODEC-LC1160. */
#define LC1160_GPIO_MCLK		MFP_PIN_GPIO(90)
#define LC1160_GPIO_ECLK		MFP_PIN_GPIO(91)
#define LC1160_INT_PIN			MFP_PIN_GPIO(99)
#define LC1160_INT2_PIN		MFP_PIN_GPIO(223)
//#define CODEC_PA_PIN			MFP_PIN_GPIO(75)
#define CODEC_JACK_POLARITY	1

/* GPIO keypad. */
#define COMIP_GPIO_KEY_VOLUMEUP		MFP_PIN_GPIO(72)
#define COMIP_GPIO_KEY_VOLUMEDOWN		MFP_PIN_GPIO(73)

/* LCD. */
#define LCD_RESET_PIN			MFP_PIN_GPIO(154)
#define LCD_BK_CTL_PIN			MFP_PIN_GPIO(153)
/* Touchscreen-FT5X06. */
#define FT5X06_INT_PIN			MFP_PIN_GPIO(166)
#define FT5X06_RST_PIN			MFP_PIN_GPIO(165)

/*CAMERA*/
#if defined(CONFIG_VIDEO_BF3905)
#define BF3905_POWERDOWN_PIN		MFP_PIN_GPIO(172)
#define BF3905_RESET_PIN		MFP_PIN_GPIO(170)
#endif

#if defined(CONFIG_VIDEO_GC2145_2LANE_26M)
#define GC2145_POWERDOWN_PIN		MFP_PIN_GPIO(171)
#define GC2145_RESET_PIN		MFP_PIN_GPIO(169)
#endif

#if defined(CONFIG_VIDEO_GC0310)
#define GC0310_POWERDOWN_PIN		MFP_PIN_GPIO(172)
#define GC0310_RESET_PIN		MFP_PIN_GPIO(170)
#endif

#if defined(CONFIG_VIDEO_HM2056)
#define HM2056_POWERDOWN_PIN		MFP_PIN_GPIO(171)
#define HM2056_RESET_PIN		MFP_PIN_GPIO(169)
#endif

/*rtk wifi*/
#ifdef CONFIG_RTK_WLAN_SDIO
#define RTK_WIFI_ONOFF_PIN		MFP_PIN_GPIO(199)
#define RTK_WIFI_WAKE_I_PIN		MFP_PIN_GPIO(203)
#define RTK_BTWIFI_CHIPEN_PIN		MFP_PIN_GPIO(140)
#endif

/* BT-RTL8723BS. */
#ifdef CONFIG_RTK_BLUETOOTH
#define RTK_BT_ONOFF_PIN		MFP_PIN_GPIO(MFP_PIN_MAX)
#define RTK_BT_RESET_PIN		MFP_PIN_GPIO(198)
#define RTK_BT_WAKE_I_PIN		MFP_PIN_GPIO(200)
#define RTK_BT_WAKE_O_PIN		MFP_PIN_GPIO(202)
#define RTK_BT_UART_CTS_PIN		MFP_PIN_GPIO(185)
#endif

#ifdef CONFIG_RADIO_RTK8723B
#define RTK_FM_EN_PIN 			MFP_PIN_GPIO(143)
#endif


#endif
#endif /*__ASM_ARCH_BOARD_A310T_H__*/
