#ifndef __ASM_ARCH_BOARD_ZEUS_H__
#define __ASM_ARCH_BOARD_ZEUS_H__

#include <plat/mfp.h>
#include <plat/comipfb.h>

//#if defined(CONFIG_COMIP_PROJECT_1860)
//#if defined(CONFIG_COMIP_BOARD_LC1860_ZEUS)

/* PMIC&CODEC-LC1160. */
#define LC1160_GPIO_MCLK		MFP_PIN_GPIO(90)
#define LC1160_GPIO_ECLK		MFP_PIN_GPIO(91)
#define LC1160_INT_PIN			MFP_PIN_GPIO(99)
#define LC1160_INT2_PIN                 MFP_PIN_GPIO(223)
//#define CODEC_PA_EXTRA_PIN			MFP_PIN_GPIO(74)
#define CODEC_PA_PIN			MFP_PIN_GPIO(75)
#define CODEC_JACK_POLARITY	1

/* BQ27510 GASGAUGE. */
#define BQ27510_GASGAUGE_INT_PIN    MFP_PIN_GPIO(134)
/* max17058 GASGAUGE. */
#define MAX17058_FG_INT_PIN             MFP_PIN_GPIO(134)
/* extern charger. */
#define EXTERN_CHARGER_INT_PIN      MFP_PIN_GPIO(132)

/* GPIO keypad. */
#define COMIP_GPIO_KEY_VOLUMEUP		MFP_PIN_GPIO(72)
#define COMIP_GPIO_KEY_VOLUMEDOWN		MFP_PIN_GPIO(73)

/* LCD. */
#define LCD_RESET_PIN			MFP_PIN_GPIO(154)

#define KEYPAD_LED_PIN			MFP_PIN_GPIO(255)
/* Touchscreen-FT5X06. */
#if defined(CONFIG_TOUCHSCREEN_FT5X06)
#define FT5X06_INT_PIN			MFP_PIN_GPIO(166)
#define FT5X06_RST_PIN			MFP_PIN_GPIO(165)
#endif
#if defined(CONFIG_VIDEO_OV8865)
#define OV8865_POWERDOWN_PIN		MFP_PIN_GPIO(171)
#define OV8865_RESET_PIN		MFP_PIN_GPIO(169)
#define OV8865_MCLK_PIN			MFP_PIN_GPIO(178)
#endif
#if defined(CONFIG_VIDEO_S5K3H2)
#define S5K3H2_POWERDOWN_PIN		MFP_PIN_GPIO(171)
#define S5K3H2_RESET_PIN		MFP_PIN_GPIO(169)
#endif

#if defined(CONFIG_VIDEO_OV9760)
#define OV9760_POWERDOWN_PIN		MFP_PIN_GPIO(172)
#define OV9760_RESET_PIN		MFP_PIN_GPIO(170)
#endif

#if defined(CONFIG_VIDEO_OV2680)
#define OV2680_POWERDOWN_PIN		MFP_PIN_GPIO(172)
#define OV2680_RESET_PIN		MFP_PIN_GPIO(170)
#define OV2680_MCLK_PIN			MFP_PIN_GPIO(173)
#endif

#if defined(CONFIG_GPS_UBLOX)
#define UBLOX_GPS_RESET_PIN		MFP_PIN_GPIO(205)
#endif

/*rtk wifi*/
#ifdef CONFIG_RTK_WLAN_SDIO
#define RTK_WIFI_ONOFF_PIN		MFP_PIN_GPIO(199)
#define RTK_WIFI_WAKE_I_PIN		MFP_PIN_GPIO(203)
#define RTK_BTWIFI_CHIPEN_PIN		MFP_PIN_GPIO(140)
#endif

#if defined (CONFIG_BRCM_BLUETOOTH) || defined (CONFIG_RTK_BLUETOOTH)
#define UART2_CTS_PIN		MFP_PIN_GPIO(185)
#endif

/* BT-RTL8723BS. */
#ifdef CONFIG_RTK_BLUETOOTH
#define RTK_BT_ONOFF_PIN		MFP_PIN_GPIO(MFP_PIN_MAX)
#define RTK_BT_RESET_PIN		MFP_PIN_GPIO(198)
#define RTK_BT_WAKE_I_PIN		MFP_PIN_GPIO(200)
#define RTK_BT_WAKE_O_PIN		MFP_PIN_GPIO(202)
#endif

#ifdef CONFIG_RADIO_RTK8723B
#define RTK_FM_EN_PIN 			MFP_PIN_GPIO(143)
#endif

#ifdef CONFIG_BRCM_BLUETOOTH
#define BRCM_BT_ONOFF_PIN       MFP_PIN_GPIO(MFP_PIN_MAX)
#define BRCM_BT_RESET_PIN		MFP_PIN_GPIO(198)
#define BRCM_BT_WAKE_I_PIN		MFP_PIN_GPIO(200)
#define BRCM_BT_WAKE_O_PIN		MFP_PIN_GPIO(202)
#endif

#ifdef CONFIG_BRCM_WIFI
#define BRCM_WIFI_ONOFF_PIN		MFP_PIN_GPIO(199)
#define BRCM_WIFI_WAKE_I_PIN		MFP_PIN_GPIO(203)
#define BRCM_WIFI_SDIO_CLK_PIN		MFP_PIN_GPIO(191)
#define BRCM_WIFI_SDIO_CMD_PIN		MFP_PIN_GPIO(192)
#define BRCM_WIFI_SDIO_DATA3_PIN	MFP_PIN_GPIO(193)
#define BRCM_WIFI_SDIO_DATA2_PIN	MFP_PIN_GPIO(194)
#define BRCM_WIFI_SDIO_DATA1_PIN	MFP_PIN_GPIO(195)
#define BRCM_WIFI_SDIO_DATA0_PIN	MFP_PIN_GPIO(196)
#endif

#ifdef CONFIG_BRCM_GPS
#define BCM_GPS_RESET_PIN		MFP_PIN_GPIO(MFP_PIN_MAX)
#define BCM_GPS_STANDBY_PIN		MFP_PIN_GPIO(206)
#endif

#ifdef CONFIG_VIDEO_OCP8111
#define OCP8111_EN_PIN			MFP_PIN_GPIO(174)
#define OCP8111_MODE_PIN		MFP_PIN_GPIO(175)
#endif

#ifdef CONFIG_LIGHT_PROXIMITY_STK3X1X
#define STK3X1X_INT_PIN             MFP_PIN_GPIO(211)
#endif

#ifdef CONFIG_LIGHT_PROXIMITY_LTR55XALS
#define LTR55XALS_INT_PIN       	MFP_PIN_GPIO(211)
#endif

#ifdef CONFIG_SENSORS_LSM330
#define LSM330_ACC_INT_PIN          MFP_PIN_GPIO(209)
#define LSM330_GYR_INT_PIN          MFP_PIN_GPIO(135)
#endif

#ifdef CONFIG_SENSORS_INV_MPU6880
#define INV6880_INT_PIN          MFP_PIN_GPIO(209)
#endif

#ifdef CONFIG_USB_COMIP_OTG
/* USB OTG ID PIN. */
#define USB_OTG_ID_PIN 			MFP_PIN_GPIO(161)
#endif

#ifdef CONFIG_COMIP_SDCARD_DETECT
/* SDCARD DETECT PIN. */
#define SDCARD_DETECT_PIN 			MFP_PIN_GPIO(243)
#endif

//#endif

//#endif
#endif /*__ASM_ARCH_BOARD_LC1860_H__*/
