# board product config

obj-$(CONFIG_COMIP_BOARD_LC1860_MENTOR) += board-lc1860-mentor.o
obj-$(CONFIG_COMIP_BOARD_LC1860_EVB) += board-lc1860.o
obj-$(CONFIG_COMIP_BOARD_LC1860_EVB2) += board-lc1860.o
obj-$(CONFIG_COMIP_BOARD_LC1860_EVB3) += board-lc1860.o
obj-$(CONFIG_COMIP_PROJECT_USL90) += board-usl90.o
obj-$(CONFIG_COMIP_PROJECT_LTE26007) += board-lte26007.o
obj-$(CONFIG_COMIP_PROJECT_A310T) += board-a310t.o
obj-$(CONFIG_COMIP_PROJECT_M9206) += board-m9206.o
obj-$(CONFIG_COMIP_PROJECT_YONGDA) += board-yongda.o
obj-$(CONFIG_COMIP_PROJECT_LX70A) += board-lx70a.o
obj-$(CONFIG_COMIP_PROJECT_K706_V1_0) += board-k706.o
obj-$(CONFIG_COMIP_PROJECT_SMARTMODULE) += board-smartmodule.o
obj-$(CONFIG_COMIP_PROJECT_USL9) += board-usl9.o
obj-$(CONFIG_COMIP_PROJECT_FOURMODE) += board-fourmode.o
obj-$(CONFIG_COMIP_PROJECT_FIVEMODE) += board-fivemode.o
obj-$(CONFIG_COMIP_PROJECT_LC1860_PHONE) += board-lc1860-phone.o
obj-$(CONFIG_COMIP_BOARD_LC1860_ZEUS) += board-zeus.o
