obj-$(CONFIG_COMIP_LC1120) += lc1120.o
obj-$(CONFIG_SND_COMIP_CODECS) += comip_codecs_interface.o comip-snd-notifier.o
obj-$(CONFIG_SND_COMIP_LC1120)  += comip_codecs_lc1120.o
obj-$(CONFIG_SND_COMIP_LC1132)  += comip_codecs_lc1132.o
obj-$(CONFIG_SND_COMIP_LC1160) += lc1160_codec.o comip-snd-notifier.o
