#
# Makefile for ST-Ericsson CG2900 connectivity combo controller
#

ccflags-y :=					\
	-Idrivers/staging/cg2900/include	\
	-Idrivers/staging/cg2900		\
	-Iarch/arm/mach-comip

#obj-y		+= btcg2900.o
obj-y	+= cg2900_uart.o hci_ldisc.o
