

#ifndef _NCP1851_CHARGER_H
#define _NCP1851_CHARGER_H

#define NCP1851_I2C_ADDR    (0x36)
/* timeout for resetting chip timer */
#define NCP1851_TIMER_TIMEOUT           (20)

enum{
    OTG_MODE = 0,
    CHARGE_MODE = 1,
};

#define REG_STATUS_REGISTER      (0x00)

#define CHARGER_MODE_SHIFT        (4)
#define FAULTINT_STAT       (1 << 0)
#define STATINT_STAT        (1 << 1)
#define NTC_STAT            (1 << 2)
#define BATFET_STAT         (1 << 3)
#define CHARGE_OFF          (0 << 4)
#define WAIT_STBY           (1 << 4)
#define SAFE_CHARGE         (2 << 4)
#define PRE_CHARGE          (3 << 4)
#define FULL_CHARGE         (4 << 4)
#define VOLT_CHARGE         (5 << 4)
#define CHARGE_DONE         (6 << 4)
#define DPP                 (7 << 4)
#define WEAK_WAIT           (8 << 4)
#define WEAK_SAFE           (9 << 4)
#define WEAK_CHARGE         (10 << 4)
#define CHARGE_FAULT        (11 << 4)
/*BOOST STATUS*/
#define BOOST_WAIT          (12 << 4)
#define BOOST_MODE          (13 << 4)
#define BOOST_FAULT         (14 << 4)
#define BOOST_OVER          (15 << 4)




#define REG_CTRL1_REGISTER    (0x01)
#define CHG_EN_SHIFT    (6)
#define OTG_EN_SHIFT    (5)
#define NTC_EN_SHIFT    (4)
#define TCHG_RST_SHIFT  (1)
#define REG_RST_EN       (1 << 7)
#define CHG_EN           (1)
#define CHG_DIS          (0)
#define OTG_EN           (1)
#define OTG_DIS          (0)
#define NTC_EN           (1)
#define NTC_DIS          (0)
#define TJ_WARN_OPT      (1 << 3)
#define JEITA_OPT        (1 << 2)
#define TCHG_RST_EN      (1)
#define TCHG_RST_DIS     (0)
#define INT_MASK         (1)
#define INT_UNMASK       (0)

#define REG_CTRL2_REGISTER    (0x02)
#define WDTO_DIS_SHIFT       (7)
#define CHGTO_DIS_SHIFT      (6)
#define PWR_PATH_SHIFT       (5)
#define FCTRY_MOD_SHIFT      (3)
#define IINSET_PIN_EN_SHIFT  (2)
#define WDTO_EN           (0)
#define WDTO_DIS          (1)
#define CHGTO_EN          (0)
#define CHGTO_DIS         (1)
#define PWR_PATH_EN       (1)
#define PWR_PATH_DIS      (0)
#define TRANS_EN_REG      (1 << 4)
#define FCTRY_MOD_EN      (1)
#define FCTRY_MOD_DIS     (0)
#define IINSET_PIN_EN     (1)
#define IINSET_PIN_DIS    (0)
#define IINLIM_EN         (1)
#define IINLIM_DIS        (0)
#define AICL_EN           (1)
#define AICL_DIS          (0)

#define REG_STAT_INT_REGISTER    (0x03)
#define TWARN_INT    (1 << 5)
#define TM1_INT      (1 << 4)
#define TM2_INT      (1 << 3)
#define TSD_INT      (1 << 2)
#define CHGEX_INT    (1 << 1)
#define VBUSOK_INT   (1 << 0)

#define REG_CHG1_INT_REGISTER    (0x04)
#define VINLO_INT   (1 << 4)
#define VINHI_INT   (1 << 3)
#define BATRMV_INT  (1 << 2)
#define BUCKOVP_INT (1 << 1)
#define CHINT2      (1 << 0)

#define REG_CHG2_INT_REGISTER    (0x05)
#define NTCHOT_INT      (1 << 7)
#define NTCWARM_INT     (1 << 6)
#define NTCCHILLY_INT   (1 << 5)
#define NTCCOLD_INT     (1 << 4)
#define WDTO_INT        (1 << 3)
#define USBTO_INT       (1 << 2)
#define CHGTO_INT       (1 << 1)
#define CHINT1      (1 << 0)

#define REG_BST_INT_REGISTER    (0x06)
#define VBUSILIM_INT       (1 << 2)
#define VBUSOV_INT         (1 << 1)
#define VBATLO_INT         (1 << 0)

#define REG_VIN_SNS_REGISTER    (0x07)
#define VINOVLO_SNS      (1 << 7)
#define CHEXTD7V_SNS     (1 << 6)
#define VBUSOV_SNS       (1 << 5)
#define VBUSUV_SNS       (1 << 4)
#define VINDET_SNS       (1 << 3)
#define VCHGDET_SNS      (1 << 2)
#define VBOOST_UV_SNS    (1 << 1)

#define REG_VBAT_SNS_REGISTER    (0x08)
#define NTC_REMOVAL_SNS   (1 << 7)
#define BAT_OV_SNS        (1 << 6)
#define VRECHG_OK_SNS     (1 << 5)
#define VFET_OK_SNS       (1 << 4)
#define VPRE_OK_SNS       (1 << 3)
#define VSAFE_OK_SNS      (1 << 2)
#define VEOC_OK_SNS       (1 << 1)

#define REG_TEMP_SNS_REGISTER    (0x09)
#define NTC_COLD_SNS       (1 << 7)
#define NTC_CHILLY_SNS     (1 << 6)
#define NTC_WARM_SNS       (1 << 5)
#define NTC_HOT_SNS        (1 << 4)
#define TSD_SNS            (1 << 3)
#define TM2_SNS            (1 << 2)
#define TM1_SNS            (1 << 1)
#define TWARN              (1 << 0)

#define REG_STAT_MSK_REGISTER    (0x0A)
#define TWARM_MASK       (1 << 5)
#define TM1_MASK         (1 << 4)
#define TM2_MASK         (1 << 3)
#define TSD_MASK         (1 << 2)
#define VBUSOK_MASK      (1 << 0)

#define REG_CH1_MSK_REGISTER    (0x0B)
#define VINLO_MASK         (1 << 4)
#define VINHI_MASK         (1 << 3)
#define BATRMV_MASK        (1 << 2)
#define BUCKOVP_MASK       (1 << 1)
#define STATECHG_MASK      (1 << 0)

#define REG_CH2_MSK_REGISTER    (0x0C)
#define NTCHOT_MASK       (1 << 7)
#define NTCWARM_MASK      (1 << 6)
#define NTCCHILLY_MASK    (1 << 5)
#define NTCCOLD_MASK      (1 << 4)
#define WDTO_MASK         (1 << 3)
#define USBTO_MASK        (1 << 2)
#define CHGTO_MASK        (1 << 1)

#define REG_BST_MSK_REGISTER    (0x0D)
#define VBUSILIM_MASK         (1 << 3)
#define VBUSOV_MASK        (1 << 2)
#define VBUSLO_MASK        (1 << 1)
#define STATEOTG_MASK      (1 << 0)

#define REG_VBAT_SET_REGISTER    (0x0E)
#define CTRL_VBAT_MIN   (3300)
#define CTRL_VBAT_STEP   (25)
#define CTRL_VBAT_MAX   (4500)

#define REG_IBAT_SET_REGISTER    (0x0F)
#define IEOC_SHIFT   (4)
#define IEOC_MIN   (100)
#define IEOC_STEP   (25)
#define IEOC_MAX   (275)
#define ICHG_MIN   (400)
#define ICHG_STEP   (100)
#define ICHG_MAX   (1600)

#define REG_MISC_SET_REGISTER    (0x10)
#define IWEAK_SHIFT       (5)
#define CTRL_VFET_SHIFT   (2)
#define IWEAK_MIN       (0)
#define IWEAK_STEP      (100)
#define IWEAK_MAX       (300)
#define CTRL_VFET_MIN   (3100)
#define CTRL_VFET_STEP  (100)
#define CTRL_VFET_MAX   (3600)
#define IINLIM_MIN   (100)
#define IINLIM_MAX   (1500)

#define REG_NTC_SET1_REGISTER    (0x11)
#define VCHRED_SHIFT   (2)
#define VCHRED_MIN       (0)
#define VCHRED_STEP      (100)
#define VCHRED_MAX       (300)
#define ICHRED_MIN       (400)
#define ICHRED_STEP      (100)
#define ICHRED_MAX       (700)

#define REG_NTC_SET2_REGISTER    (0x12)
#define BATCOLD_SHIFT     (5)
#define BATHOT_SHIFT      (2)
#define BATCHILLY_SHIFT   (1)
#define BATCOLD_MIN       (995)
#define BATCOLD_STEP      (146)
#define BATCOLD_MAX       (2017)

#define BATHOT_MIN       (87)
#define BATHOT_STEP      (146)
#define BATHOT_MAX       (1109)

#define BATCHILLY_SEL       (0 << 1)
#define BATWARM_SEL         (0 << 0)


#endif /* __NCP1851_CHARGER_H */
