obj-$(CONFIG_BRCM_BLUETOOTH) += brcm-bluetooth.o
obj-$(CONFIG_BRCM_GPS) += brcm-gps.o
obj-$(CONFIG_BRCM_WIFI) += brcm-wifi.o
obj-$(CONFIG_BCMDHD) += bcmdhd/
# RealTek
obj-$(CONFIG_RTK_BLUETOOTH) += rtk-bluetooth.o
obj-$(CONFIG_RTL8723BS)		+= rtl8723bs/
obj-$(CONFIG_RTK_WLAN_SDIO) += rtl8723_adapter.o
#STE
obj-$(CONFIG_STE_WIFI) += cw1100/
#STE CG2900 driver
obj-$(CONFIG_CG2900) += cg2900/

obj-$(CONFIG_BT_SLEEP)		+= bluesleep.o
#ublox
obj-$(CONFIG_GPS_UBLOX) += ublox-gps.o
obj-$(CONFIG_RTL8192)                += rtl8192es/
