#ifndef __ARCH_ARM_MACH_RESET_H
#define __ARCH_ARM_MACH_RESET_H

static struct rst rst[] = {
	/* ap. */
	RST_VAR(AP, 0, AP_PWR_SFRST_CTL, 0),

	/* 
		TODO : AP_PWR_CP_RSTCTL
			AP_PWR_TOP_RSTCTL.
	*/

	/* ha7. */
	RST_VAR(HA7_CORE0_DBG, 0, AP_PWR_HA7_RSTCTL0, 0),
	RST_VAR(HA7_CORE1_DBG, 0, AP_PWR_HA7_RSTCTL0, 1),
	RST_VAR(HA7_CORE2_DBG, 0, AP_PWR_HA7_RSTCTL0, 2),
	RST_VAR(HA7_CORE3_DBG, 0, AP_PWR_HA7_RSTCTL0, 3),
	RST_VAR(HA7_CORE0, 0, AP_PWR_HA7_RSTCTL0, 4),
	RST_VAR(HA7_CORE1, 0, AP_PWR_HA7_RSTCTL0, 5),
	RST_VAR(HA7_CORE2, 0, AP_PWR_HA7_RSTCTL0, 6),
	RST_VAR(HA7_CORE3, 0, AP_PWR_HA7_RSTCTL0, 7),
	RST_VAR(HA7_DBG0, 0, AP_PWR_HA7_RSTCTL0, 8),
	RST_VAR(HA7_DBG1, 0, AP_PWR_HA7_RSTCTL0, 9),
	RST_VAR(HA7_DBG2, 0, AP_PWR_HA7_RSTCTL0, 10),
	RST_VAR(HA7_DBG3, 0, AP_PWR_HA7_RSTCTL0, 11),
	RST_VAR(HA7_ETM0, 0, AP_PWR_HA7_RSTCTL0, 12),
	RST_VAR(HA7_ETM1, 0, AP_PWR_HA7_RSTCTL0, 13),
	RST_VAR(HA7_ETM2, 0, AP_PWR_HA7_RSTCTL0, 14),
	RST_VAR(HA7_ETM3, 0, AP_PWR_HA7_RSTCTL0, 15),
	RST_VAR(HA7_L2, 0, AP_PWR_HA7_RSTCTL0, 16),
	RST_VAR(HA7_SOCDBG, 0, AP_PWR_HA7_RSTCTL0, 17),

	/*
		TODO : AP_PWR_HA7_RSTCTL1
	*/

	/* sa7 */
	RST_VAR(SA7_CORE_DBG, 0, AP_PWR_SA7_RSTCTL0, 0),
	RST_VAR(SA7_CORE, 0, AP_PWR_SA7_RSTCTL0, 1),
	RST_VAR(SA7_DBG, 0 , AP_PWR_SA7_RSTCTL0, 2),
	RST_VAR(SA7_ETM, 0, AP_PWR_SA7_RSTCTL0, 3),
	RST_VAR(SA7_L2, 0, AP_PWR_SA7_RSTCTL0, 4),
	RST_VAR(SA7_SOCDBG, 0, AP_PWR_SA7_RSTCTL0, 5),

	/*
		TODO : AP_PWR_SA7_RSTCTL1
	*/

	/* modules. */
	RST_MODULE_VAR(CCI400, 0, 0),
	RST_MODULE_VAR(AP_SW0, 0, 1),
	RST_MODULE_VAR(AP_SW2, 0, 2),
	RST_MODULE_VAR(AP_PERI_SW0, 0, 3),
	RST_MODULE_VAR(AP_PERI_SW5, 0, 4),
	RST_MODULE_VAR(SDMMC0, 0, 5),
	RST_MODULE_VAR(SDMMC2, 0, 6),
	RST_MODULE_VAR(CTL, 0, 7),
	RST_MODULE_VAR(SECURITY, 0, 8),
	RST_MODULE_VAR(SEC_RAM, 0, 9),
	RST_MODULE_VAR(HPI, 0, 10),
	RST_MODULE_VAR(GIC, 0, 11),

	RST_MODULE_VAR(SSI0, 1, 0),
	RST_MODULE_VAR(SSI1, 1, 1),
	RST_MODULE_VAR(UART0, 1, 2),
	RST_MODULE_VAR(UART1, 1, 3),
	RST_MODULE_VAR(UART2, 1, 4),
	RST_MODULE_VAR(I2S, 1, 5),

	RST_MODULE_VAR(KBS, 2, 0),
	RST_MODULE_VAR(SSI2, 2, 1),
	RST_MODULE_VAR(I2C2, 2, 2),
	RST_MODULE_VAR(BP147, 2, 3),
	RST_MODULE_VAR(TPZCTL, 2, 4),

	RST_MODULE_VAR(WDT0, 3, 0),
	RST_MODULE_VAR(WDT1, 3, 1),
	RST_MODULE_VAR(WDT2, 3, 2),
	RST_MODULE_VAR(WDT3, 3, 3),
	RST_MODULE_VAR(WDT4, 3, 4),
	RST_MODULE_VAR(TIMER0, 3, 5),
	RST_MODULE_VAR(TIMER1, 3, 6),
	RST_MODULE_VAR(TIMER2, 3, 7),
	RST_MODULE_VAR(TIMER3, 3, 8),
	RST_MODULE_VAR(TIMER4, 3, 9),
	RST_MODULE_VAR(TIMER5, 3, 10),
	RST_MODULE_VAR(TIMER6, 3, 11),
	RST_MODULE_VAR(TIMER7, 3, 12),
	RST_MODULE_VAR(I2C0, 3, 13),
	RST_MODULE_VAR(I2C1, 3, 14),
	RST_MODULE_VAR(I2C3, 3, 15),
	RST_MODULE_VAR(PWM, 3, 16),

	/* gpu. */
	RST_VAR(GPU, 0, AP_PWR_GPU_RSTCTL, 0),

	/* video. */
	RST_VAR(ACC2D, 0, AP_PWR_VIDEO_RSTCTL, 0),
	RST_VAR(ON2_CODEC, 0, AP_PWR_VIDEO_RSTCTL, 1),
	RST_VAR(ON2_ENC, 0, AP_PWR_VIDEO_RSTCTL, 2),
	RST_VAR(SMMU0, 0, AP_PWR_VIDEO_RSTCTL, 3),
	RST_VAR(AP_PERI_SW1, 0, AP_PWR_VIDEO_RSTCTL, 4),
	RST_VAR(AP_SW1, 0, AP_PWR_VIDEO_RSTCTL, 5),

	/* dsp-isp */
	RST_VAR(ISP, 0, AP_PWR_DSIISP_RSTCTL, 0),
	RST_VAR(DISPLAY, 0, AP_PWR_DSIISP_RSTCTL, 1),
	RST_VAR(SMMU1, 0, AP_PWR_DSIISP_RSTCTL, 2),
	RST_VAR(AP_PERI_SW3, 0, AP_PWR_DSIISP_RSTCTL, 3),
	RST_VAR(AP_SW3, 0, AP_PWR_DSIISP_RSTCTL, 4),

	/*
		TODO : AP_PWR_USB_RSTCTL
			AP_PWR_HBLK0_RSTCTL
			AP_PWR_WDT_RSTCTL
	*/

	/* ddr pwr. */
	RST_VAR(COM_I2C, RST_WRITE_ENABLE, DDR_PWR_RESET, 0),
	RST_VAR(COM_I2S, RST_WRITE_ENABLE, DDR_PWR_RESET, 1),
	RST_VAR(COM_UART, RST_WRITE_ENABLE, DDR_PWR_RESET, 2),
	RST_VAR(COM_PCM, RST_WRITE_ENABLE, DDR_PWR_RESET, 3),
	RST_VAR(TOP_MAILBOX, RST_WRITE_ENABLE, DDR_PWR_RESET, 4),
	RST_VAR(GPIO, RST_WRITE_ENABLE, DDR_PWR_RESET, 5),
	RST_VAR(MUXPIN, RST_WRITE_ENABLE, DDR_PWR_RESET, 6),
	RST_VAR(MEMCTL0, RST_WRITE_ENABLE, DDR_PWR_RESET, 7),
	RST_VAR(MEMCTL1, RST_WRITE_ENABLE, DDR_PWR_RESET, 8),
	RST_VAR(TOP_DMAS, RST_WRITE_ENABLE, DDR_PWR_RESET, 9),
	RST_VAR(TOP_DMAG, RST_WRITE_ENABLE, DDR_PWR_RESET, 10),
	RST_VAR(TL420_ICTL, RST_WRITE_ENABLE, DDR_PWR_RESET, 11),
	RST_VAR(TIME_STAMP, RST_WRITE_ENABLE, DDR_PWR_RESET, 12),
	RST_VAR(TOP_RAM1, RST_WRITE_ENABLE, DDR_PWR_RESET, 13),
	RST_VAR(CP_BOOT_RAM, RST_WRITE_ENABLE, DDR_PWR_RESET, 14),
	RST_VAR(TL420, RST_WRITE_ENABLE, DDR_PWR_RESET, 15),
};

#endif /* __ARCH_ARM_MACH_RESET_H */
