#ifndef __ASM_ARCH_LC1813_MFP_H
#define __ASM_ARCH_LC1813_MFP_H

enum {
	MFP_PIN_GPIO16_2 = 243,
	MFP_PIN_GPIO17_2,
	MFP_PIN_GPIO18_2,
	MFP_PIN_GPIO19_2,
	MFP_PIN_GPIO191_2,
	MFP_PIN_GPIO192_2,

	MFP_PIN_NAND_TBALL_0,
	MFP_PIN_NAND_TBALL_1,
	MFP_PIN_NAND_TBALL_2,
	MFP_PIN_NAND_TBALL_3,
	MFP_PIN_NAND_TBALL_4,

	MFP_PIN_MAX,
};

enum {
	MFP_PULL_TD_DATA0_0 = 0,
	MFP_PULL_TD_DATA0_1,
	MFP_PULL_TD_DATA0_2,
	MFP_PULL_TD_DATA0_3,
	MFP_PULL_TD_DATA0_4,
	MFP_PULL_TD_DATA0_5,
	MFP_PULL_TD_DATA0_6,
	MFP_PULL_TD_DATA0_7,
	MFP_PULL_TD_DATA0_8,
	MFP_PULL_TD_DATA0_9,
	MFP_PULL_OSC_EN1,
	MFP_PULL_CLK26M_IN1,
	MFP_PULL_GSM0_DIGRF_DEN,
	MFP_PULL_GSM0_DIGRF_D,
	MFP_PULL_GSM0_GPO,
	MFP_PULL_GSM0_SW_GPO0,
	MFP_PULL_GSM0_SW_GPO1,
	MFP_PULL_GSM0_SW_GPO2,
	MFP_PULL_GSM0_SW_GPO3,
	MFP_PULL_TD_GPO0,
	MFP_PULL_TD_GPO1,
	MFP_PULL_TD_GPO2,
	MFP_PULL_TD_GPO3,
	MFP_PULL_TD_GPO4,
	MFP_PULL_TD_GPO5,
	MFP_PULL_TD_GPO6,
	MFP_PULL_TD_GPO7,
	MFP_PULL_TD_GPO8,
	MFP_PULL_TD_GPO9,
	MFP_PULL_TD_GPO10,
	MFP_PULL_TD_GPO11,
	MFP_PULL_TD_SPI_CS2,
	MFP_PULL_TD_SPI_CS0,
	MFP_PULL_TD_SPI_CLK,
	MFP_PULL_TD_SPI_DOUT,
	MFP_PULL_TD_SPI_DIN,
	MFP_PULL_ISP_FSIN1,
	MFP_PULL_ISP_FSIN0,
	MFP_PULL_CLK26_SEL,
	MFP_PULL_KB_DKI_2,
	MFP_PULL_KB_DKI_3,
	MFP_PULL_KB_DKI_4,
	MFP_PULL_KB_DKI_5,
	MFP_PULL_KB_DKI_6,
	MFP_PULL_KB_DKI_7,
	MFP_PULL_COM_UART_RX,
	MFP_PULL_COM_UART_TX,
	MFP_PULL_UART1_RTS,
	MFP_PULL_UART1_CTS,
	MFP_PULL_UART1_RX,
	MFP_PULL_UART1_TX,
	MFP_PULL_UART2_RTS,
	MFP_PULL_UART2_CTS,
	MFP_PULL_UART2_RX,
	MFP_PULL_UART2_TX,
	MFP_PULL_PWM_0,
	MFP_PULL_NAND_OEN,
	MFP_PULL_NAND_WEN,
	MFP_PULL_NAND_IO_0,
	MFP_PULL_NAND_IO_1,
	MFP_PULL_NAND_IO_2,
	MFP_PULL_NAND_IO_3,
	MFP_PULL_NAND_IO_4,
	MFP_PULL_NAND_IO_5,
	MFP_PULL_NAND_IO_6,
	MFP_PULL_NAND_IO_7,
	MFP_PULL_NAND_IO_8,
	MFP_PULL_NAND_IO_9,
	MFP_PULL_NAND_IO_10,
	MFP_PULL_NAND_IO_11,
	MFP_PULL_NAND_IO_12,
	MFP_PULL_NAND_IO_13,
	MFP_PULL_NAND_IO_14,
	MFP_PULL_NAND_IO_15,
	MFP_PULL_I2S0_WS,
	MFP_PULL_I2S0_SCLK,
	MFP_PULL_I2S0_SDOUT,
	MFP_PULL_I2S0_SDIN,
	MFP_PULL_COM_PCM_SSN,
	MFP_PULL_COM_PCM_CLK,
	MFP_PULL_COM_PCM_RX,
	MFP_PULL_COM_PCM_TX,
	MFP_PULL_COM_PCM0_SSN,
	MFP_PULL_COM_PCM0_CLK,
	MFP_PULL_COM_PCM0_RX,
	MFP_PULL_COM_PCM0_TX,
	MFP_PULL_BOOT_CTL_0,
	MFP_PULL_BOOT_CTL_1,
	MFP_PULL_BOOT_CTL_2,
	MFP_PULL_SSI2_SSN,
	MFP_PULL_SSI2_CLK,
	MFP_PULL_SSI2_RX,
	MFP_PULL_SSI2_TX,
	MFP_PULL_SSI1_SSN,
	MFP_PULL_SSI1_CLK,
	MFP_PULL_SSI1_RX,
	MFP_PULL_SSI1_TX,
	MFP_PULL_SSI0_SSN_0,
	MFP_PULL_SSI0_SSN_1,
	MFP_PULL_SSI0_CLK,
	MFP_PULL_SSI0_RX,
	MFP_PULL_SSI0_TX,
	MFP_PULL_SEC_SW,
	MFP_PULL_SEC_SMC,
	MFP_PULL_GPIO_D_24,
	MFP_PULL_JTAG1_NTRS,
	MFP_PULL_JTAG1_TMS,
	MFP_PULL_JTAG1_TDO,
	MFP_PULL_JTAG1_TDI,
	MFP_PULL_JTAG1_TCK,
	MFP_PULL_JTAG0_NTRS,
	MFP_PULL_JTAG0_TMS,
	MFP_PULL_JTAG0_TDO,
	MFP_PULL_JTAG0_TDI,
	MFP_PULL_JTAG0_TCK,
	MFP_PULL_SIM1_IO,
	MFP_PULL_SIM0_IO,
	MFP_PULL_I2C1_SDA,
	MFP_PULL_I2C1_SCL,
	MFP_PULL_I2C0_SDA,
	MFP_PULL_I2C0_SCL,
	MFP_PULL_COM_I2C_SDA,
	MFP_PULL_COM_I2C_SCL,
	MFP_PULL_ISP_I2C_SDA,
	MFP_PULL_ISP_I2C_SCL,
	MFP_PULL_ISP_S_VSYNC,
	MFP_PULL_ISP_S_HSYNC,
	MFP_PULL_ISP_SCLK,
	MFP_PULL_ISP_S_DATA_0,
	MFP_PULL_ISP_S_DATA_1,
	MFP_PULL_ISP_S_DATA_2,
	MFP_PULL_ISP_S_DATA_3,
	MFP_PULL_ISP_S_DATA_4,
	MFP_PULL_ISP_S_DATA_5,
	MFP_PULL_ISP_S_DATA_6,
	MFP_PULL_ISP_S_DATA_7,
	MFP_PULL_ISP_S_DATA_8,
	MFP_PULL_ISP_S_DATA_9,
	MFP_PULL_ISP_STROBE,
	MFP_PULL_ISP_SCLK0,
	MFP_PULL_ISP_PWM,
	MFP_PULL_ISP_PDWN1,
	MFP_PULL_ISP_PDWN0,
	MFP_PULL_ISP_RSTN1,
	MFP_PULL_ISP_RSTN0,
	MFP_PULL_GPIO_D_0,
	MFP_PULL_GPIO_D_1,
	MFP_PULL_GPIO_D_2,
	MFP_PULL_GPIO_D_3,
	MFP_PULL_GPIO_D_4,
	MFP_PULL_GPIO_D_5,
	MFP_PULL_GPIO_D_6,
	MFP_PULL_GPIO_D_7,
	MFP_PULL_GPIO_D_8,
	MFP_PULL_GPIO_D_9,
	MFP_PULL_GPIO_D_10,
	MFP_PULL_GPIO_D_11,
	MFP_PULL_GPIO_D_12,
	MFP_PULL_GPIO_D_28,
	MFP_PULL_GPIO_D_25,
	MFP_PULL_GPIO_D_240,
	MFP_PULL_GPIO_D_239,
	MFP_PULL_GPIO_D_234,
	MFP_PULL_GPIO_D_233,
	MFP_PULL_GPIO_D_232,
	MFP_PULL_MMC0_CMD,
	MFP_PULL_MMC0_DATA_3,
	MFP_PULL_MMC0_DATA_2,
	MFP_PULL_MMC0_DATA_1,
	MFP_PULL_MMC0_DATA_0,
	MFP_PULL_MMC1_CMD,
	MFP_PULL_MMC1_DATA_7,
	MFP_PULL_MMC1_DATA_6,
	MFP_PULL_MMC1_DATA_5,
	MFP_PULL_MMC1_DATA_4,
	MFP_PULL_MMC1_DATA_3,
	MFP_PULL_MMC1_DATA_2,
	MFP_PULL_MMC1_DATA_1,
	MFP_PULL_MMC1_DATA_0,
	MFP_PULL_MMC2_CMD,
	MFP_PULL_MMC2_DATA_3,
	MFP_PULL_MMC2_DATA_2,
	MFP_PULL_MMC2_DATA_1,
	MFP_PULL_MMC2_DATA_0,

	MFP_PULL_MAX
};

#define MFP_GPIO14_ISP_PDWN_1		MFP_PIN_MODE_0
#define MFP_GPIO15_ISP_PDWN_0		MFP_PIN_MODE_0
#define MFP_GPIO16_GSM0_SW_GPO_3	MFP_PIN_MODE_0
#define MFP_GPIO17_GSM0_SW_GPO_2	MFP_PIN_MODE_0
#define MFP_GPIO18_GSM0_SW_GPO_1	MFP_PIN_MODE_0
#define MFP_GPIO19_GSM0_SW_GPO_0	MFP_PIN_MODE_0
#define MFP_GPIO20_ISP_SDATA_0		MFP_PIN_MODE_0
#define MFP_GPIO20_MMC0_CARD_WPRT	MFP_PIN_MODE_3
#define MFP_GPIO21_ISP_SDATA_1		MFP_PIN_MODE_0
#define MFP_GPIO21_MMC0_CARD_DET	MFP_PIN_MODE_3
#define MFP_GPIO22_SEC_SW		MFP_PIN_MODE_0
#define MFP_GPIO23_SEC_SMC		MFP_PIN_MODE_0
#define MFP_GPIO26_ISP_RST_0		MFP_PIN_MODE_0
#define MFP_GPIO27_ISP_RST_1		MFP_PIN_MODE_0
#define MFP_GPIO28_USB0_DRVVBUS		MFP_PIN_MODE_1
#define MFP_GPIO32_CLK26M_IN1 		MFP_PIN_MODE_0
#define MFP_GPIO33_OSC_EN1    		MFP_PIN_MODE_0
#define MFP_GPIO44_TD_SPI_DIN		MFP_PIN_MODE_0
#define MFP_GPIO45_TD_SPI_DOUT		MFP_PIN_MODE_0
#define MFP_GPIO46_TD_SPI_CLK		MFP_PIN_MODE_0
#define MFP_GPIO47_TD_SPI_CS0		MFP_PIN_MODE_0
#define MFP_GPIO48_GSM0_SPI_CS2		MFP_PIN_MODE_0
#define MFP_GPIO59_TD_GPO_11		MFP_PIN_MODE_0
#define MFP_GPIO60_TD_GPO_10		MFP_PIN_MODE_0
#define MFP_GPIO61_TD_GPO_9		MFP_PIN_MODE_0
#define MFP_GPIO62_TD_GPO_8		MFP_PIN_MODE_0
#define MFP_GPIO63_TD_GPO_7		MFP_PIN_MODE_0
#define MFP_GPIO64_TD_GPO_6		MFP_PIN_MODE_0
#define MFP_GPIO65_TD_GPO_5		MFP_PIN_MODE_0
#define MFP_GPIO66_TD_GPO_4		MFP_PIN_MODE_0
#define MFP_GPIO67_TD_GPO_3		MFP_PIN_MODE_0
#define MFP_GPIO68_TD_GPO_2		MFP_PIN_MODE_0
#define MFP_GPIO69_TD_GPO_1		MFP_PIN_MODE_0
#define MFP_GPIO70_TD_GPO_0		MFP_PIN_MODE_0
#define MFP_GPIO71_ISP_PWM		MFP_PIN_MODE_0
#define MFP_GPIO71_PWM_1		MFP_PIN_MODE_1
#define MFP_GPIO71_PWM_GPIO_1		MFP_PIN_MODE_GPIO
#define MFP_GPIO72_ISP_SCLK0		MFP_PIN_MODE_0
#define MFP_GPIO73_ISP_STROBE		MFP_PIN_MODE_0
#define MFP_GPIO74_ISP_SDATA_7		MFP_PIN_MODE_0
#define MFP_GPIO75_ISP_SDATA_6		MFP_PIN_MODE_0
#define MFP_GPIO76_ISP_SDATA_5		MFP_PIN_MODE_0
#define MFP_GPIO77_ISP_SDATA_4		MFP_PIN_MODE_0
#define MFP_GPIO78_ISP_SDATA_3		MFP_PIN_MODE_0
#define MFP_GPIO79_ISP_SDATA_2		MFP_PIN_MODE_0
#define MFP_GPIO80_ISP_SDATA_9		MFP_PIN_MODE_0
#define MFP_GPIO81_ISP_SDATA_8		MFP_PIN_MODE_0
#define MFP_GPIO82_ISP_SCLK		MFP_PIN_MODE_0
#define MFP_GPIO83_ISP_S_HSYNC		MFP_PIN_MODE_0
#define MFP_GPIO84_ISP_S_VSYNC		MFP_PIN_MODE_0
#define MFP_GPIO85_ISP_I2C_SCL		MFP_PIN_MODE_0
#define MFP_GPIO85_I2C3_SCL		MFP_PIN_MODE_1
#define MFP_GPIO86_ISP_I2C_SDA		MFP_PIN_MODE_0
#define MFP_GPIO86_I2C3_SDA		MFP_PIN_MODE_1
#define MFP_GPIO87_NAND_IO_7 		MFP_PIN_MODE_0
#define MFP_GPIO88_NAND_IO_6		MFP_PIN_MODE_0
#define MFP_GPIO89_NAND_CS_0		MFP_PIN_MODE_0
#define MFP_GPIO89_CP_CLKOUT		MFP_PIN_MODE_1
#define MFP_GPIO90_NAND_IO_4		MFP_PIN_MODE_0
#define MFP_GPIO91_NAND_IO_3		MFP_PIN_MODE_0
#define MFP_GPIO92_NAND_IO_2		MFP_PIN_MODE_0
#define MFP_GPIO93_NAND_IO_1		MFP_PIN_MODE_0
#define MFP_GPIO94_NAND_IO_0 		MFP_PIN_MODE_0
#define MFP_GPIO96_KBS_DKI_7	    	MFP_PIN_MODE_0
#define MFP_GPIO96_DSI_TE	    	MFP_PIN_MODE_1
#define MFP_GPIO97_KBS_DKI_6	    	MFP_PIN_MODE_0
#define MFP_GPIO98_KBS_DKI_5	    	MFP_PIN_MODE_0
#define MFP_GPIO99_KBS_DKI_4	    	MFP_PIN_MODE_0
#define MFP_GPIO100_KBS_DKI_3	    	MFP_PIN_MODE_0
#define MFP_GPIO101_KBS_DKI_2	   	MFP_PIN_MODE_0
#define MFP_GPIO109_NAND_IO_15		MFP_PIN_MODE_0
#define MFP_GPIO110_NAND_IO_14		MFP_PIN_MODE_0
#define MFP_GPIO111_NAND_IO_13		MFP_PIN_MODE_0
#define MFP_GPIO112_NAND_IO_12		MFP_PIN_MODE_0
#define MFP_GPIO113_NAND_IO_11		MFP_PIN_MODE_0
#define MFP_GPIO114_NAND_IO_10		MFP_PIN_MODE_0
#define MFP_GPIO115_NAND_IO_9		MFP_PIN_MODE_0
#define MFP_GPIO116_NAND_IO_8		MFP_PIN_MODE_0
#define MFP_GPIO117_MMC1_DATA_6		MFP_PIN_MODE_0
#define MFP_GPIO117_NAND_ALE	    	MFP_PIN_MODE_1
#define MFP_GPIO118_MMC1_DATA_7		MFP_PIN_MODE_0
#define MFP_GPIO118_NAND_CLE	    	MFP_PIN_MODE_1
#define MFP_GPIO119_NAND_WEN	    	MFP_PIN_MODE_0
#define MFP_GPIO120_NAND_OEN	    	MFP_PIN_MODE_0
#define MFP_GPIO121_MMC1_DATA_0		MFP_PIN_MODE_0
#define MFP_GPIO121_NAND_RB	    	MFP_PIN_MODE_1
#define MFP_GPIO122_MMC1_DATA_1 	MFP_PIN_MODE_0
#define MFP_GPIO122_NAND_CSN1 	   	MFP_PIN_MODE_1
#define MFP_GPIO123_MMC1_DATA_2 	MFP_PIN_MODE_0
#define MFP_GPIO123_NAND_CSN0 	   	MFP_PIN_MODE_1
#define MFP_GPIO126_MMC1_DATA_3 	MFP_PIN_MODE_0
#define MFP_GPIO127_MMC1_DATA_4 	MFP_PIN_MODE_0
#define MFP_GPIO128_MMC1_DATA_5 	MFP_PIN_MODE_0
#define MFP_GPIO129_MMC1_CLK 		MFP_PIN_MODE_0
#define MFP_GPIO130_MMC1_CMD 		MFP_PIN_MODE_0
#define MFP_GPIO131_MMC0_CLK 		MFP_PIN_MODE_0
#define MFP_GPIO132_MMC0_CMD 		MFP_PIN_MODE_0
#define MFP_GPIO133_MMC0_DATA_3 	MFP_PIN_MODE_0
#define MFP_GPIO134_MMC0_DATA_2 	MFP_PIN_MODE_0
#define MFP_GPIO135_MMC0_DATA_1 	MFP_PIN_MODE_0
#define MFP_GPIO136_MMC0_DATA_0 	MFP_PIN_MODE_0
#define MFP_GPIO137_MMC2_CLK 		MFP_PIN_MODE_0
#define MFP_GPIO138_MMC2_CMD 		MFP_PIN_MODE_0
#define MFP_GPIO139_MMC2_DATA_3 	MFP_PIN_MODE_0
#define MFP_GPIO140_MMC2_DATA_2  	MFP_PIN_MODE_0
#define MFP_GPIO141_MMC2_DATA_1  	MFP_PIN_MODE_0
#define MFP_GPIO142_MMC2_DATA_0  	MFP_PIN_MODE_0
#define MFP_GPIO145_UART0_TX  		MFP_PIN_MODE_0
#define MFP_GPIO145_SSI3_TX 		MFP_PIN_MODE_3
#define MFP_GPIO146_UART0_RX  		MFP_PIN_MODE_0
#define MFP_GPIO146_SSI3_RX 		MFP_PIN_MODE_3
#define MFP_GPIO147_UART0_CTS  		MFP_PIN_MODE_0
#define MFP_GPIO147_SSI3_CLK 		MFP_PIN_MODE_3
#define MFP_GPIO148_UART0_RTS  		MFP_PIN_MODE_0
#define MFP_GPIO148_SSI3_SSN 		MFP_PIN_MODE_3
#define MFP_GPIO149_PWM_0 		MFP_PIN_MODE_0
#define MFP_GPIO149_GPIO_0 		MFP_PIN_MODE_GPIO
#define MFP_GPIO150_UART2_TX 		MFP_PIN_MODE_0
#define MFP_GPIO151_UART2_RX 		MFP_PIN_MODE_0
#define MFP_GPIO152_UART2_CTS		MFP_PIN_MODE_0
#define MFP_GPIO153_UART2_RTS		MFP_PIN_MODE_0
#define MFP_GPIO154_UART1_TX 		MFP_PIN_MODE_0
#define MFP_GPIO155_UART1_RX 		MFP_PIN_MODE_0
#define MFP_GPIO156_UART1_CTS		MFP_PIN_MODE_0
#define MFP_GPIO157_UART1_RTS		MFP_PIN_MODE_0
#define MFP_GPIO158_COM_UART_TX		MFP_PIN_MODE_0
#define MFP_GPIO159_COM_UART_RX		MFP_PIN_MODE_0
#define MFP_GPIO160_SSI0_TX		MFP_PIN_MODE_0
#define MFP_GPIO161_SSI0_RX		MFP_PIN_MODE_0
#define MFP_GPIO162_SSI0_CLK		MFP_PIN_MODE_0
#define MFP_GPIO163_SSI0_SSN_1		MFP_PIN_MODE_0
#define MFP_GPIO164_SSI0_SSN_0		MFP_PIN_MODE_0
#define MFP_GPIO165_SSI1_TX		MFP_PIN_MODE_0
#define MFP_GPIO166_SSI1_RX		MFP_PIN_MODE_0
#define MFP_GPIO167_SSI1_CLK		MFP_PIN_MODE_0
#define MFP_GPIO168_SSI1_SSN		MFP_PIN_MODE_0
#define MFP_GPIO169_SSI2_TX		MFP_PIN_MODE_0
#define MFP_GPIO170_SSI2_RX		MFP_PIN_MODE_0
#define MFP_GPIO171_SSI2_CLK		MFP_PIN_MODE_0
#define MFP_GPIO171_I2C2_SCL		MFP_PIN_MODE_1
#define MFP_GPIO172_SSI2_SSN		MFP_PIN_MODE_0
#define MFP_GPIO172_I2C2_SDA		MFP_PIN_MODE_1
#define MFP_GPIO173_COM_PCM0_TX		MFP_PIN_MODE_0
#define MFP_GPIO173_ISP_SHUTTER_0	MFP_PIN_MODE_1
#define MFP_GPIO173_ISP_DEBUG_VSYNC	MFP_PIN_MODE_3
#define MFP_GPIO174_COM_PCM0_RX		MFP_PIN_MODE_0
#define MFP_GPIO174_ISP_FREX_0		MFP_PIN_MODE_1
#define MFP_GPIO174_ISP_DEBUG_HREF	MFP_PIN_MODE_3
#define MFP_GPIO175_COM_PCM0_CLK	MFP_PIN_MODE_0
#define MFP_GPIO175_ISP_GC_0		MFP_PIN_MODE_1
#define MFP_GPIO175_ISP_DEBUG_PCLK	MFP_PIN_MODE_3
#define MFP_GPIO176_COM_PCM0_SSN	MFP_PIN_MODE_0
#define MFP_GPIO176_ISP_DEBUG_Y_0	MFP_PIN_MODE_3
#define MFP_GPIO177_COM_PCM1_TX		MFP_PIN_MODE_0
#define MFP_GPIO177_I2S1_SDOUT		MFP_PIN_MODE_1
#define MFP_GPIO178_COM_PCM1_RX		MFP_PIN_MODE_0
#define MFP_GPIO178_I2S1_SDIN		MFP_PIN_MODE_1
#define MFP_GPIO179_COM_PCM1_CLK	MFP_PIN_MODE_0
#define MFP_GPIO179_I2S1_SCLK		MFP_PIN_MODE_1
#define MFP_GPIO180_COM_PCM1_SSN	MFP_PIN_MODE_0
#define MFP_GPIO180_I2S1_WS		MFP_PIN_MODE_1
#define MFP_GPIO181_I2S0_SDIN		MFP_PIN_MODE_0
#define MFP_GPIO182_I2S0_SDOUT		MFP_PIN_MODE_0
#define MFP_GPIO183_I2S0_SCLK		MFP_PIN_MODE_0
#define MFP_GPIO184_I2S0_WS		MFP_PIN_MODE_0
#define MFP_GPIO185_COM_I2C_SCL		MFP_PIN_MODE_0
#define MFP_GPIO186_COM_I2C_SDA		MFP_PIN_MODE_0
#define MFP_GPIO187_I2C0_SCL		MFP_PIN_MODE_0
#define MFP_GPIO188_I2C0_SDA		MFP_PIN_MODE_0
#define MFP_GPIO189_I2C1_SCL		MFP_PIN_MODE_0
#define MFP_GPIO190_I2C1_SDA		MFP_PIN_MODE_0
#define MFP_GPIO191_SIM0_CLK		MFP_PIN_MODE_0
#define MFP_GPIO192_SIM0_IO		MFP_PIN_MODE_0
#define MFP_GPIO193_SIM0_RST		MFP_PIN_MODE_0
#define MFP_GPIO194_SIM1_CLK		MFP_PIN_MODE_0
#define MFP_GPIO195_SIM1_IO		MFP_PIN_MODE_0
#define MFP_GPIO196_SIM1_RST		MFP_PIN_MODE_0
#define MFP_GPIO209_PWR_PWEN		MFP_PIN_MODE_0
#define MFP_GPIO210_PWR_CLK_OUT_3	MFP_PIN_MODE_0
#define MFP_GPIO211_PWR_CLK_OUT_2  	MFP_PIN_MODE_0
#define MFP_GPIO211_ISP_SCLK_1  	MFP_PIN_MODE_1
#define MFP_GPIO212_PWR_CLK_OUT_1  	MFP_PIN_MODE_0
#define MFP_GPIO213_PWR_CLK_OUT_0  	MFP_PIN_MODE_0
#define MFP_GPIO213_ISP_DEBUG_Y_7	MFP_PIN_MODE_3
#define MFP_GPIO214_PWR_PMU_DVFS_1 	MFP_PIN_MODE_0
#define MFP_GPIO214_ISP_DEBUG_Y_8	MFP_PIN_MODE_3
#define MFP_GPIO215_PWR_PMU_DVFS_0 	MFP_PIN_MODE_0
#define MFP_GPIO216_JTAG0_TCK		MFP_PIN_MODE_0
#define MFP_GPIO216_TEST_PIN_9		MFP_PIN_MODE_1
#define MFP_GPIO217_JTAG0_TDI		MFP_PIN_MODE_0
#define MFP_GPIO217_TEST_PIN_8		MFP_PIN_MODE_1
#define MFP_GPIO218_JTAG0_TDO		MFP_PIN_MODE_0
#define MFP_GPIO218_TEST_PIN_7		MFP_PIN_MODE_1
#define MFP_GPIO219_JTAG0_TMS		MFP_PIN_MODE_0
#define MFP_GPIO219_TEST_PIN_6		MFP_PIN_MODE_1
#define MFP_GPIO220_JTAG0_NTRS		MFP_PIN_MODE_0
#define MFP_GPIO220_TEST_PIN_5		MFP_PIN_MODE_1
#define MFP_GPIO221_JTAG1_TCK		MFP_PIN_MODE_0
#define MFP_GPIO221_TEST_PIN_4		MFP_PIN_MODE_1
#define MFP_GPIO221_SEC_SW		MFP_PIN_MODE_3
#define MFP_GPIO222_JTAG1_TDI		MFP_PIN_MODE_0
#define MFP_GPIO222_TEST_PIN_3		MFP_PIN_MODE_1
#define MFP_GPIO222_SEC_SMC		MFP_PIN_MODE_3
#define MFP_GPIO223_JTAG1_TDO		MFP_PIN_MODE_0
#define MFP_GPIO223_TEST_PIN_2		MFP_PIN_MODE_1
#define MFP_GPIO224_JTAG1_TMS		MFP_PIN_MODE_0
#define MFP_GPIO224_TEST_PIN_1		MFP_PIN_MODE_1
#define MFP_GPIO224_KBS_DKI_1		MFP_PIN_MODE_3
#define MFP_GPIO225_JTAG1_NTRS		MFP_PIN_MODE_0
#define MFP_GPIO225_TEST_PIN_0		MFP_PIN_MODE_1
#define MFP_GPIO225_KBS_DKI_0		MFP_PIN_MODE_3
#define MFP_GPIO226_BOOT_CTL_2		MFP_PIN_MODE_0
#define MFP_GPIO226_ISP_DEBUG_Y_9	MFP_PIN_MODE_3
#define MFP_GPIO227_BOOT_CTL_1		MFP_PIN_MODE_0
#define MFP_GPIO227_ISP_DEBUG_EN 	MFP_PIN_MODE_3
#define MFP_GPIO228_BOOT_CTL_0		MFP_PIN_MODE_0
#define MFP_GPIO229_ISP_FSIN0 		MFP_PIN_MODE_0
#define MFP_GPIO230_ISP_FSIN1 		MFP_PIN_MODE_0
#define MFP_GPIO241_RSTN 		MFP_PIN_MODE_0
#define MFP_GPIO242_OSC_EN_3V		MFP_PIN_MODE_0

/* Pin pull caps. */
#define MFP_PULL_UP_CAP		(1 << MFP_PULL_UP) | (1 << MFP_PULL_DISABLE)
#define MFP_PULL_DOWN_CAP	(1 << MFP_PULL_DOWN) | (1 << MFP_PULL_DISABLE)
#define MFP_PULL_ALL_CAP	(MFP_PULL_UP_CAP | MFP_PULL_DOWN_CAP)

/* Pin flags. */
#define MFP_PIN_GPIO_ONLY	(0x01)
#define MFP_PIN_SECURITY	(0x02)

struct mfp {
	unsigned int id;
	unsigned int mux;
	unsigned char val;
	unsigned char flags;
};

struct mfp_info {
	struct mfp *mfp;
	unsigned int size;
};

struct mfp_pull {
	unsigned int id;
	unsigned int caps;
	unsigned char en_reg_id;
	unsigned char en_bit;
	unsigned char pull_reg_id;
	unsigned char pull_bit;
};

extern struct mfp mfp_pin_list[];
extern unsigned int mfp_pin_list_size;
extern struct mfp_pull mfp_pull_list[];
extern unsigned int mfp_pull_list_size;

#endif /* __ASM_ARCH_LC1813_MFP_H */
