#ifndef __ARCH_ARM_MACH_RESET_H
#define __ARCH_ARM_MACH_RESET_H

#if defined(CONFIG_CPU_LC1810)

static struct rst rst[] = {
	/* ap. */
	RST_VAR(AP, 0, AP_PWR_SFRST_CTL, 0),

	/* a9. */
	RST_VAR(A9_CORE0, 0, AP_PWR_A9_RSTCTL, 0),
	RST_VAR(A9_CORE1, 0, AP_PWR_A9_RSTCTL, 1),
	RST_VAR(A9_NEON0, 0, AP_PWR_A9_RSTCTL, 2),
	RST_VAR(A9_NEON1, 0, AP_PWR_A9_RSTCTL, 3),
	RST_VAR(A9_DBG0, 0, AP_PWR_A9_RSTCTL, 4),
	RST_VAR(A9_DBG1, 0, AP_PWR_A9_RSTCTL, 5),
	RST_VAR(A9_PERI, 0, AP_PWR_A9_RSTCTL, 6),
	RST_VAR(A9_SCU, 0, AP_PWR_A9_RSTCTL, 7),
	RST_VAR(A9_WD0, 0, AP_PWR_A9_RSTCTL, 8),
	RST_VAR(A9_WD1, 0, AP_PWR_A9_RSTCTL, 9),
	RST_VAR(A9_L2C, 0, AP_PWR_A9_RSTCTL, 10),
	RST_VAR(A9_PTM, 0, AP_PWR_A9_RSTCTL, 11),
	RST_VAR(A9_ATB, 0, AP_PWR_A9_RSTCTL, 12),
	RST_VAR(A9_DBG_APB, 0, AP_PWR_A9_RSTCTL, 13),

	/* m0. */
	RST_VAR(M0_DBG, 0, AP_PWR_M0_RSTCTL, 0),
	RST_VAR(M0, 0, AP_PWR_M0_RSTCTL, 1),

	/* gpu. */
	RST_VAR(GPU, 0, AP_PWR_GPU_RSTCTL, 0),

	/* on2. */
	RST_VAR(ON2_E0, 0, AP_PWR_ON2_RSTCTL, 0),
	RST_VAR(ON2_E1, 0, AP_PWR_ON2_RSTCTL, 1),
	RST_VAR(ON2_D, 0, AP_PWR_ON2_RSTCTL, 2),
	RST_VAR(ON2_EBUS, 0, AP_PWR_ON2_RSTCTL, 3),
	RST_VAR(ON2_DBUS, 0, AP_PWR_ON2_RSTCTL, 4),

	/* isp. */
	RST_VAR(ISP_AHB, 0, AP_PWR_ISP_RSTCTL, 0),
	RST_VAR(ISP_P, 0, AP_PWR_ISP_RSTCTL, 1),

	/* dispaly. */
	RST_VAR(DISPLAY, 0, AP_PWR_DISPLAY_RSTCTL, 0),
	RST_VAR(HDMI, 0, AP_PWR_DISPLAY_RSTCTL, 1),

	/* cp. */
	RST_VAR(CP, 0, AP_PWR_CP_RSTCTL, 0),
	RST_VAR(CP_ARM0, 0, AP_PWR_CP_RSTCTL, 1),

	/* modules. */
	RST_MODULE_VAR(PERI_AXI, 0, 0),
	RST_MODULE_VAR(ACP_AXI, 0, 1),
	RST_MODULE_VAR(DMA_AXI, 0, 2),
	RST_MODULE_VAR(DDR_AXI, 0, 3),
	RST_MODULE_VAR(AU_DMAS, 0, 4),
	RST_MODULE_VAR(AP_DMAS, 0, 5),
	RST_MODULE_VAR(AP_DMAC, 0, 6),
	RST_MODULE_VAR(AXI_AHB, 0, 7),
	RST_MODULE_VAR(AP_DMA_BUS, 0, 8),
	RST_MODULE_VAR(AP_DMAG, 0, 9),
	RST_MODULE_VAR(M0_RAM, 1, 0),
	RST_MODULE_VAR(CTL, 1, 1),
	RST_MODULE_VAR(NFC, 1, 2),
	RST_MODULE_VAR(HPI, 1, 3),
	RST_MODULE_VAR(NFC_HPI_ARB, 1, 4),
	RST_MODULE_VAR(USBOTG, 1, 5),
	RST_MODULE_VAR(USBOTG_P, 1, 6),
	RST_MODULE_VAR(USBHOST, 1, 7),
	RST_MODULE_VAR(USBHOST_P, 1, 8),
	RST_MODULE_VAR(USBHSIC, 1, 9),
	RST_MODULE_VAR(USBHSIC_P, 1, 10),
	RST_MODULE_VAR(AP_SEC_RAM, 1, 11),
	RST_MODULE_VAR(CIPHER, 1, 12),
	RST_MODULE_VAR(BOOTROM, 1, 13),
	RST_MODULE_VAR(TB, 2, 0),
	RST_MODULE_VAR(WDT, 2, 1),
	RST_MODULE_VAR(TIMER0, 2, 2),
	RST_MODULE_VAR(TIMER1, 2, 3),
	RST_MODULE_VAR(TIMER2, 2, 4),
	RST_MODULE_VAR(TIMER3, 2, 5),
	RST_MODULE_VAR(I2C0, 2, 6),
	RST_MODULE_VAR(I2C1, 2, 7),
	RST_MODULE_VAR(I2C3, 2, 8),
	RST_MODULE_VAR(PWM, 2, 9),
	RST_MODULE_VAR(DATA_PBR, 3, 0),
	RST_MODULE_VAR(I2S0, 3, 1),
	RST_MODULE_VAR(I2S1, 3, 2),
	RST_MODULE_VAR(SSI0, 3, 3),
	RST_MODULE_VAR(SSI1, 3, 4),
	RST_MODULE_VAR(SSI3, 3, 5),
	RST_MODULE_VAR(UART0, 3, 6),
	RST_MODULE_VAR(UART1, 3, 7),
	RST_MODULE_VAR(UART2, 3, 8),
	RST_MODULE_VAR(SEC_PBR, 4, 0),
	RST_MODULE_VAR(I2C2, 4, 1),
	RST_MODULE_VAR(KBS, 4, 2),
	RST_MODULE_VAR(SSI2, 4, 3),
	RST_MODULE_VAR(BP147, 4, 4),
	RST_MODULE_VAR(TPZCTL, 4, 5),
	RST_MODULE_VAR(SDIOC0, 4, 6),
	RST_MODULE_VAR(SDIOC1, 4, 7),
	RST_MODULE_VAR(SDIOC2, 4, 8),
	RST_MODULE_VAR(SDIOC3, 4, 9),

	/* core sight. */
	RST_VAR(CS_ATB, 0, AP_PWR_CS_RSTCTL, 0),
	RST_VAR(CS_DBG_PM, 0, AP_PWR_CS_RSTCTL, 1),
	RST_VAR(CS_DBG_PS, 0, AP_PWR_CS_RSTCTL, 2),
	RST_VAR(CS_AHB, 0, AP_PWR_CS_RSTCTL, 3),
	RST_VAR(CS_CTM, 0, AP_PWR_CS_RSTCTL, 4),
	RST_VAR(CS_ARM0CTI, 0, AP_PWR_CS_RSTCTL, 5),
	RST_VAR(CS_M0CTI, 0, AP_PWR_CS_RSTCTL, 6),

	/* ddr pwr. */
	RST_VAR(COM_I2C, RST_WRITE_ENABLE, DDR_PWR_RESET, 0),
	RST_VAR(COM_UART, RST_WRITE_ENABLE, DDR_PWR_RESET, 2),
	RST_VAR(PCM1, RST_WRITE_ENABLE, DDR_PWR_RESET, 3),
	RST_VAR(GPIO1, RST_WRITE_ENABLE, DDR_PWR_RESET, 5),
	RST_VAR(GPIO0, RST_WRITE_ENABLE, DDR_PWR_RESET, 6),
	RST_VAR(MUXPIN, RST_WRITE_ENABLE, DDR_PWR_RESET, 7),
	RST_VAR(PHY_DDR, RST_WRITE_ENABLE, DDR_PWR_RESET, 8),
	RST_VAR(CTRL_DDR, RST_WRITE_ENABLE, DDR_PWR_RESET, 9),
};

#elif defined(CONFIG_CPU_LC1813)

static struct rst rst[] = {
	/* ap. */
	RST_VAR(AP, 0, AP_PWR_SFRST_CTL, 0),

	/* a7. */
	RST_VAR(A7_CORE0_n_DBG, 0, AP_PWR_A7_RSTCTL0, 0),
	RST_VAR(A7_CORE1_n_DBG, 0, AP_PWR_A7_RSTCTL0, 1),
	RST_VAR(A7_CORE2_n_DBG, 0, AP_PWR_A7_RSTCTL0, 2),
	RST_VAR(A7_CORE3_n_DBG, 0, AP_PWR_A7_RSTCTL0, 3),
	RST_VAR(A7_CORE0, 0, AP_PWR_A7_RSTCTL0, 4),
	RST_VAR(A7_CORE1, 0, AP_PWR_A7_RSTCTL0, 5),
	RST_VAR(A7_CORE2, 0, AP_PWR_A7_RSTCTL0, 6),
	RST_VAR(A7_CORE3, 0, AP_PWR_A7_RSTCTL0, 7),
	RST_VAR(A7_DBG0, 0, AP_PWR_A7_RSTCTL0, 8),
	RST_VAR(A7_DBG1, 0, AP_PWR_A7_RSTCTL0, 9),
	RST_VAR(A7_DBG2, 0, AP_PWR_A7_RSTCTL0, 10),
	RST_VAR(A7_DBG3, 0, AP_PWR_A7_RSTCTL0, 11),
	RST_VAR(A7_ETM0, 0, AP_PWR_A7_RSTCTL0, 12),
	RST_VAR(A7_ETM1, 0, AP_PWR_A7_RSTCTL0, 13),
	RST_VAR(A7_ETM2, 0, AP_PWR_A7_RSTCTL0, 14),
	RST_VAR(A7_ETM3, 0, AP_PWR_A7_RSTCTL0, 15),
	RST_VAR(A7_L2, 0, AP_PWR_A7_RSTCTL0, 16),
	RST_VAR(A7_SOCDBG, 0, AP_PWR_A7_RSTCTL0, 17),

	/* gpu. */
	RST_VAR(GPU, 0, AP_PWR_GPU_RSTCTL, 0),

	/* on2. */
	RST_VAR(ON2_E0, 0, AP_PWR_ON2_RSTCTL, 0),
	RST_VAR(ON2_E1, 0, AP_PWR_ON2_RSTCTL, 1),
	RST_VAR(ON2_D, 0, AP_PWR_ON2_RSTCTL, 2),
	RST_VAR(ON2_EBUS, 0, AP_PWR_ON2_RSTCTL, 3),
	RST_VAR(ON2_DBUS, 0, AP_PWR_ON2_RSTCTL, 4),

	/* isp. */
	RST_VAR(ISP_AHB, 0, AP_PWR_ISP_RSTCTL, 0),
	RST_VAR(ISP_P, 0, AP_PWR_ISP_RSTCTL, 1),

	/* dispaly. */
	RST_VAR(DISPLAY, 0, AP_PWR_DISPLAY_RSTCTL, 0),
	RST_VAR(HDMI, 0, AP_PWR_DISPLAY_RSTCTL, 1),

	/* cp. */
	RST_VAR(CP, 0, AP_PWR_CP_RSTCTL, 0),
	RST_VAR(CP_ARM0, 0, AP_PWR_CP_RSTCTL, 1),

	/* modules. */
	RST_MODULE_VAR(PERI_AXI, 0, 0),
	RST_MODULE_VAR(ACP_AXI, 0, 1),
	RST_MODULE_VAR(DMA_AXI, 0, 2),
	RST_MODULE_VAR(DDR_AXI, 0, 3),
	RST_MODULE_VAR(AU_DMAS, 0, 4),
	RST_MODULE_VAR(AP_DMAS, 0, 5),
	RST_MODULE_VAR(AP_DMAC, 0, 6),
	RST_MODULE_VAR(AXI_AHB, 0, 7),
	RST_MODULE_VAR(AP_DMA_BUS, 0, 8),
	RST_MODULE_VAR(AP_DMAG, 0, 9),
	RST_MODULE_VAR(A7_AXI_MAIN, 0, 10),
	RST_MODULE_VAR(A7_AXI_GPV, 0, 11),

	RST_MODULE_VAR(CTL, 1, 1),
	RST_MODULE_VAR(NFC, 1, 2),
	RST_MODULE_VAR(HPI, 1, 3),
	RST_MODULE_VAR(NFC_HPI_ARB, 1, 4),
	RST_MODULE_VAR(USBOTG, 1, 5),
	RST_MODULE_VAR(USBOTG_P, 1, 6),
	RST_MODULE_VAR(USBHOST, 1, 7),
	RST_MODULE_VAR(USBHOST_P, 1, 8),
	RST_MODULE_VAR(USBHSIC, 1, 9),
	RST_MODULE_VAR(USBHSIC_P, 1, 10),
	RST_MODULE_VAR(AP_SEC_RAM, 1, 11),
	RST_MODULE_VAR(CIPHER, 1, 12),
	RST_MODULE_VAR(BOOTROM, 1, 13),
	RST_MODULE_VAR(A7_AXI_PERI, 1, 14),

	RST_MODULE_VAR(TB, 2, 0),
	RST_MODULE_VAR(WDT, 2, 1),
	RST_MODULE_VAR(TIMER0, 2, 2),
	RST_MODULE_VAR(TIMER1, 2, 3),
	RST_MODULE_VAR(TIMER2, 2, 4),
	RST_MODULE_VAR(TIMER3, 2, 5),
	RST_MODULE_VAR(I2C0, 2, 6),
	RST_MODULE_VAR(I2C1, 2, 7),
	RST_MODULE_VAR(I2C3, 2, 8),
	RST_MODULE_VAR(PWM, 2, 9),
	RST_MODULE_VAR(TIMER4, 2, 10),
	RST_MODULE_VAR(TIMER5, 2, 11),
	RST_MODULE_VAR(TIMER6, 2, 12),
	RST_MODULE_VAR(WDT0, 2, 13),
	RST_MODULE_VAR(WDT1, 2, 14),
	RST_MODULE_VAR(WDT2, 2, 15),

	RST_MODULE_VAR(DATA_PBR, 3, 0),
	RST_MODULE_VAR(I2S0, 3, 1),
	RST_MODULE_VAR(I2S1, 3, 2),
	RST_MODULE_VAR(SSI0, 3, 3),
	RST_MODULE_VAR(SSI1, 3, 4),
	RST_MODULE_VAR(SSI3, 3, 5),
	RST_MODULE_VAR(UART0, 3, 6),
	RST_MODULE_VAR(UART1, 3, 7),
	RST_MODULE_VAR(UART2, 3, 8),

	RST_MODULE_VAR(SEC_PBR, 4, 0),
	RST_MODULE_VAR(I2C2, 4, 1),
	RST_MODULE_VAR(KBS, 4, 2),
	RST_MODULE_VAR(SSI2, 4, 3),
	RST_MODULE_VAR(BP147, 4, 4),
	RST_MODULE_VAR(TPZCTL, 4, 5),
	RST_MODULE_VAR(SDIOC0, 4, 6),
	RST_MODULE_VAR(SDIOC1, 4, 7),
	RST_MODULE_VAR(SDIOC2, 4, 8),
	RST_MODULE_VAR(SDIOC3, 4, 9),

	/* core sight. */
	RST_VAR(CS_ATB, 0, AP_PWR_CS_RSTCTL, 0),
	RST_VAR(CS_DBG_PM, 0, AP_PWR_CS_RSTCTL, 1),
	RST_VAR(CS_DBG_PS, 0, AP_PWR_CS_RSTCTL, 2),
	RST_VAR(CS_AHB, 0, AP_PWR_CS_RSTCTL, 3),
	RST_VAR(CS_CTM, 0, AP_PWR_CS_RSTCTL, 4),
	RST_VAR(CS_ARM0CTI, 0, AP_PWR_CS_RSTCTL, 5),

	/* ddr pwr. */
	RST_VAR(COM_I2C, RST_WRITE_ENABLE, DDR_PWR_RESET, 0),
	RST_VAR(COM_UART, RST_WRITE_ENABLE, DDR_PWR_RESET, 2),
	RST_VAR(PCM1, RST_WRITE_ENABLE, DDR_PWR_RESET, 3),
	RST_VAR(GPIO1, RST_WRITE_ENABLE, DDR_PWR_RESET, 5),
	RST_VAR(GPIO0, RST_WRITE_ENABLE, DDR_PWR_RESET, 6),
	RST_VAR(MUXPIN, RST_WRITE_ENABLE, DDR_PWR_RESET, 7),
	RST_VAR(PHY_DDR, RST_WRITE_ENABLE, DDR_PWR_RESET, 8),
	RST_VAR(CTRL_DDR, RST_WRITE_ENABLE, DDR_PWR_RESET, 9),
};

#endif

#endif /* __ARCH_ARM_MACH_RESET_H */
