#
# Makefile for the light and prox drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_LIGHT_PROXIMITY_APDS990X)	+= apds990x.o
obj-$(CONFIG_LIGHT_PROXIMITY_LTR558)	+= ltr558.o
obj-$(CONFIG_LIGHT_PROXIMITY_TMD22713T)	+= tmd22713.o
obj-$(CONFIG_LIGHT_PROXIMITY_TAOS_TMD22713T)	+= taos.o
obj-$(CONFIG_LIGHT_PROXIMITY_LTR55XALS)    += ltr558als.o
obj-$(CONFIG_LIGHT_PROXIMITY_CM36283)   += cm36283.o
obj-$(CONFIG_LIGHT_PROXIMITY_GP2AP030)   += gp2ap030.o
obj-$(CONFIG_LIGHT_PROXIMITY_STK3X1X)   += stk3x1x.o
obj-$(CONFIG_LIGHT_PROXIMITY_RPR521)	+= rpr0521_driver.o
