obj-$(CONFIG_SND_COMIP_I2S) += comip-i2s.o comip-snd-dma.o
obj-$(CONFIG_SND_COMIP_VIRTUAL) += comip-snd-virtual.o
obj-$(CONFIG_SND_COMIP_PCM) += comip-pcm.o comip-pcm-dma.o
obj-$(CONFIG_SND_COMIP_LOWPOWER) += comip-snd-lowpower.o
obj-y += codecs/
