static const char *const rlim_names[RLIM_NLIMITS] = {
[RLIMIT_CPU] = "cpu",
[RLIMIT_FSIZE] = "fsize",
[RLIMIT_DATA] = "data",
[RLIMIT_STACK] = "stack",
[RLIMIT_CORE] = "core",
[RLIMIT_RSS] = "rss",
[RLIMIT_NPROC] = "nproc",
[RLIMIT_NOFILE] = "nofile",
[RLIMIT_MEMLOCK] = "memlock",
[RLIMIT_AS] = "as",
[RLIMIT_LOCKS] = "locks",
[RLIMIT_SIGPENDING] = "sigpending",
[RLIMIT_MSGQUEUE] = "msgqueue",
[RLIMIT_NICE] = "nice",
[RLIMIT_RTPRIO] = "rtprio",
[RLIMIT_RTTIME] = "rttime",
};
static const int rlim_map[RLIM_NLIMITS] = {
RLIMIT_CPU,
RLIMIT_FSIZE,
RLIMIT_DATA,
RLIMIT_STACK,
RLIMIT_CORE,
RLIMIT_RSS,
RLIMIT_NPROC,
RLIMIT_NOFILE,
RLIMIT_MEMLOCK,
RLIMIT_AS,
RLIMIT_LOCKS,
RLIMIT_SIGPENDING,
RLIMIT_MSGQUEUE,
RLIMIT_NICE,
RLIMIT_RTPRIO,
RLIMIT_RTTIME,
};
#define AA_FS_RLIMIT_MASK "cpu fsize data stack core rss nproc nofile memlock as locks sigpending msgqueue nice rtprio rttime"
