obj-$(CONFIG_CPU_LC1810) += headsmp-lc1810.o headsmp-comip-lc1810.o cpuidle-lc1810.o suspend-lc1810.o cortex-a9.o
obj-$(CONFIG_CPU_LC1813) += sleep.o headsmp-lc1813.o cpuidle-lc1813.o suspend-lc1813.o

