obj-$(CONFIG_COMIP_LC1100H) += lc1100h.o
obj-$(CONFIG_LC1100H_ADC) += lc1100h_adc.o
obj-$(CONFIG_LC1100H_MONITOR_BATTERY) += lc1100h_monitor_battery.o
obj-$(CONFIG_LC1100H_BATTERY) += lc1100h-battery.o

