#ifndef __ASM_ARCH_REGS_DDR_PWR_H
#define __ASM_ARCH_REGS_DDR_PWR_H

#define DDR_PWR_PLLCTL					(DDR_PWR_BASE + 0x00)	/* L1810 & L1813 */
#define DDR_PWR_PLLCNT					(DDR_PWR_BASE + 0x04)
#define DDR_PWR_CTL 					(DDR_PWR_BASE + 0x08)
#define DDR_PWR_DIVCLKCTL				(DDR_PWR_BASE + 0x0c)
#define DDR_PWR_APBCLKCTL				(DDR_PWR_BASE + 0x10)
#define DDR_PWR_DDRCLKCTL				(DDR_PWR_BASE + 0x14)
#define DDR_PWR_I2CCLKCTL				(DDR_PWR_BASE + 0x18)
#define DDR_PWR_SSICLKCTL				(DDR_PWR_BASE + 0x1c)
#define DDR_PWR_PCMCLKCTL				(DDR_PWR_BASE + 0x20)
#define DDR_PWR_PCM1CLKCTL				(DDR_PWR_BASE + 0x24)
#define DDR_PWR_COMUARTCLKCTL				(DDR_PWR_BASE + 0x28)
#define DDR_PWR_CLKOUTCTL				(DDR_PWR_BASE + 0x2c)
#define DDR_PWR_PCLKEN					(DDR_PWR_BASE + 0x30)
#define DDR_PWR_CLKEN					(DDR_PWR_BASE + 0x34)
#define DDR_PWR_CLKEN0					(DDR_PWR_BASE + 0x34)
#define DDR_PWR_RESET					(DDR_PWR_BASE + 0x38)
#define DDR_PWR_MEMCTL_STATE				(DDR_PWR_BASE + 0x3c)
#define DDR_PWR_ADDRCTL_CS0 				(DDR_PWR_BASE + 0x40)
#define DDR_PWR_ADDRCTL_CS1 				(DDR_PWR_BASE + 0x44)
#define DDR_PWR_ADDRCTL 				(DDR_PWR_BASE + 0x48)
#define DDR_PWR_ADDRSEL0				(DDR_PWR_BASE + 0x4c)
#define DDR_PWR_ADDRSEL1				(DDR_PWR_BASE + 0x50)
#define DDR_PWR_BWCALIDCTL0 				(DDR_PWR_BASE + 0x54)
#define DDR_PWR_BWCALIDCTL1 				(DDR_PWR_BASE + 0x58)
#define DDR_PWR_BWCALCNT0				(DDR_PWR_BASE + 0x5c)
#define DDR_PWR_BWCALCNT1				(DDR_PWR_BASE + 0x60)
#define DDR_PWR_BWCALCTL				(DDR_PWR_BASE + 0x64)
#define DDR_PWR_BWCALNUM_CP 				(DDR_PWR_BASE + 0x68)
#define DDR_PWR_BWCALNUM_A9 				(DDR_PWR_BASE + 0x6c)
#define DDR_PWR_BWCALNUM_LCDC				(DDR_PWR_BASE + 0x70)
#define DDR_PWR_BWCALNUM_DDR_AXI			(DDR_PWR_BASE + 0x74)
#define DDR_PWR_INTR_EN 				(DDR_PWR_BASE + 0x78)
#define DDR_PWR_INTR_RAW				(DDR_PWR_BASE + 0x80)
#define DDR_PWR_INTR_ST 				(DDR_PWR_BASE + 0x84)
#define DDR_PWR_INTR_CLR				(DDR_PWR_BASE + 0x88)
#define DDR_PWR_PCMCTL					(DDR_PWR_BASE + 0x8c)
#define DDR_PWR_ICMCTL					(DDR_PWR_BASE + 0x90)
#define DDR_PWR_MEMCTL_DTOATOCTL			(DDR_PWR_BASE + 0x94)
#define DDR_PWR_LPCTL					(DDR_PWR_BASE + 0x98)
#define DDR_PWR_GENERAL_REG_1				(DDR_PWR_BASE + 0xa0)
#define DDR_PWR_GENERAL_REG_2				(DDR_PWR_BASE + 0xa4)
#define DDR_PWR_GENERAL_REG_3				(DDR_PWR_BASE + 0xa8)
#define DDR_PWR_GENERAL_REG_4				(DDR_PWR_BASE + 0xac)
#define DDR_PWR_CPU0_ARBIT_REQ				(DDR_PWR_BASE + 0xb0)
#define DDR_PWR_CPU1_ARBIT_REQ				(DDR_PWR_BASE + 0xb4)
#define DDR_PWR_CPU2_ARBIT_REQ				(DDR_PWR_BASE + 0xb8)
#define DDR_PWR_CPU3_ARBIT_REQ				(DDR_PWR_BASE + 0xbc)
#define DDR_PWR_CPU4_ARBIT_REQ				(DDR_PWR_BASE + 0xc0)
#define DDR_PWR_CPU_ARBIT_EN				(DDR_PWR_BASE + 0xc4)
#define DDR_PWR_CPU0_ARBIT_ACK				(DDR_PWR_BASE + 0xc8)
#define DDR_PWR_CPU1_ARBIT_ACK				(DDR_PWR_BASE + 0xcc)
#define DDR_PWR_CPU2_ARBIT_ACK				(DDR_PWR_BASE + 0xd0)
#define DDR_PWR_CPU3_ARBIT_ACK				(DDR_PWR_BASE + 0xd4)
#define DDR_PWR_CPU4_ARBIT_ACK				(DDR_PWR_BASE + 0xd8)
#define DDR_PWR_GENERAL_REG_5				(DDR_PWR_BASE + 0xe0)
#define DDR_PWR_GENERAL_REG_6				(DDR_PWR_BASE + 0xe4)
#define DDR_PWR_GENERAL_REG_7				(DDR_PWR_BASE + 0xe8)
#define DDR_PWR_GENERAL_REG_8				(DDR_PWR_BASE + 0xec)
#define DDR_PWR_MEMCTL_FREQ_ADJ				(DDR_PWR_BASE + 0xf0)
#define DDR_PWR_CLKEN1					(DDR_PWR_BASE + 0xf4)
#define DDR_PWR_MEMCTL_CTL				(DDR_PWR_BASE + 0xf8)
#define DDR_PWR_MEMCTL_LPCTL1				(DDR_PWR_BASE + 0x160)
#define DDR_PWR_MEMCTL_LPCTL2				(DDR_PWR_BASE + 0x164)
#define DDR_PWR_CKO4L1CTL				(DDR_PWR_BASE + 0x180)
#define DDR_PWR_CKO4L2CTL				(DDR_PWR_BASE + 0x184)
#define DDR_PWR_PLLCTL0					(DDR_PWR_BASE + 0x1A4)	/* L1813S */
#define DDR_PWR_PLLCTL1					(DDR_PWR_BASE + 0x1A8)	/* L1813S */

/* DDR_PWR_PLLCTLE. */
#define DDR_PWR_PLL_OD_SEL				16
#define DDR_PWR_PLL_F_SEL				8
#define DDR_PWR_PLL_R_SEL				0

/* DDR_PWR_CTL. */
#define DDR_PWR_CTL_COM_UART_LP_REQ_PCLK		26
#define DDR_PWR_CTL_COM_UART_LP_REQ_SCLK		25
#define DDR_PWR_CTL_COM_UART_CLK_OFF_PROTECT_EN		24
#define DDR_PWR_CTL_COM_APB_BUS_MONITOR_BYPASS		16
#define DDR_PWR_CTL_CP_DDR_BRIDGE_LP_BYPASS		8

/* DDR_PWR_DIVCLKCTL. */
#define DDR_PWR_I2C_SSI_DIV				8
#define DDR_PWR_FRACTION_IN_DIV				0

/* DDR_PWR_APBCLKCTL. */
#define DDR_PWR_COM_APB_PCLK_IDLE_DIV			8
#define DDR_PWR_COM_APB_PCLK_WK_DIV			0

/* DDR_PWR_PCMXCLKCTL. */
#define DDR_PWR_PCM_CLK_MUL				16
#define DDR_PWR_PCM_CLK_DIV				0

/* DDR_PWR_COMUARTCLKCTL. */
#define DDR_PWR_COM_UART_CLK_MUL			16
#define DDR_PWR_COM_UART_CLK_DIV			0

/* DDR_PWR_CLKOUTCTL. */
#define DDR_PWR_CLK_OUT_MUL				16
#define DDR_PWR_CLK_OUT_DIV				0

/* DDR_PWR_PCLKEN. */
#define DDR_PWR_PCM1_PCLK_EN				8
#define DDR_PWR_COM_UART_PCLK_EN			7
#define DDR_PWR_GPIO0_PCLK_EN				6
#define DDR_PWR_GPIO1_PCLK_EN				5
#define DDR_PWR_COM_I2C_PCLK_EN				4
#define DDR_PWR_PCM_SSI_PCLK_EN				3
#define DDR_PWR_MUXPIN_PCLK_EN				2
#define DDR_PWR_MCTL_DDR_PCLK_EN			1
#define DDR_PWR_MPHY_DDR_PCLK_EN			0

/* DDR_PWR_CLKEN. */
#define DDR_PWR_AXI0_CP_DDR_CLK_EN			11
#define DDR_PWR_AXI1_A9_DDR_CLK_EN			10
#define DDR_PWR_COM_UART_CLK_EN				9
#define DDR_PWR_CLK_OUT_EN				8
#define DDR_PWR_GPIO0_CLK_EN				7
#define DDR_PWR_GPIO1_CLK_EN				6
#define DDR_PWR_PCM_CLK_EN				5
#define DDR_PWR_PCM_SSI_CLK_EN				4
#define DDR_PWR_PCM1_CLK_EN				3
#define DDR_PWR_COM_I2C_CLK_EN				2
#define DDR_PWR_DDR_CLK_EN				0

/* DDR_PWR_RESET. */
#define DDR_PWR_MCTL_DDR_SF_RST				9
#define DDR_PWR_MPHY_DDR_SF_RST				8
#define DDR_PWR_MUXPIN_SF_RST				7
#define DDR_PWR_GPIO0_SF_RST				6
#define DDR_PWR_GPIO1_SF_RST				5
#define DDR_PWR_PCM_SF_RST				4
#define DDR_PWR_PCM1_SF_RST				3
#define DDR_PWR_COM_UART_SF_RST				2
#define DDR_PWR_PCM_SSI_SF_RST				1
#define DDR_PWR_COM_I2C_SF_RST				0

/* DDR_PWR_MEMCTL_STATE. */
#define DDR_PWR_P_CTL_STAT				8
#define DDR_PWR_CP_DDR_CLK_STATE			5
#define DDR_PWR_AXI3_CLK_STATE				4
#define DDR_PWR_AXI2_CLK_STATE				3
#define DDR_PWR_AXI1_CLK_STATE				2
#define DDR_PWR_AXI0_CLK_STATE				1
#define DDR_PWR_DDR_CLK_STATE				0

/* DDR_PWR_ADDRCTL_CS0. */
#define DDR_PWR_ADDRCTL_CS0_ADDR_MAP			24
#define DDR_PWR_ADDRCTL_CS0_COL				16
#define DDR_PWR_ADDRCTL_CS0_BANK			8
#define DDR_PWR_ADDRCTL_CS0_ROW				0

/* DDR_PWR_ADDRCTL_CS1. */
#define DDR_PWR_ADDRCTL_CS1_COL				16
#define DDR_PWR_ADDRCTL_CS1_BANK			8
#define DDR_PWR_ADDRCTL_CS1_ROW				0

/* DDR_PWR_ADDRCTL. */
#define DDR_PWR_ADDRCTL_CS_BASE				16
#define DDR_PWR_ADDRCTL_REMAP_DONE			8
#define DDR_PWR_ADDRCTL_REMAP_EN			0

/* DDR_PWR_BWCALIDCTL0. */
#define DDR_PWR_BW_CAL_0_ID_NUM				24
#define DDR_PWR_BW_CAL_0_ID_MASK			16
#define DDR_PWR_BW_CAL_1_ID_NUM				8
#define DDR_PWR_BW_CAL_1_ID_MASK			0

/* DDR_PWR_BWCALIDCTL1. */
#define DDR_PWR_BW_CAL_2_ID_NUM				24
#define DDR_PWR_BW_CAL_2_ID_MASK			16
#define DDR_PWR_BW_CAL_3_ID_NUM				8
#define DDR_PWR_BW_CAL_3_ID_MASK			0

/* DDR_PWR_BWCALCNT0. */
#define DDR_PWR_BW_CAL_1_CNT_VALUE			16
#define DDR_PWR_BW_CAL_0_CNT_VALUE			0			

/* DDR_PWR_BWCALCNT1. */
#define DDR_PWR_BW_CAL_3_CNT_VALUE			16
#define DDR_PWR_BW_CAL_2_CNT_VALUE			0

/* DDR_PWR_BWCALCTL. */
#define DDR_PWR_BW_CAL_DDR_AXI_EN			3
#define DDR_PWR_BW_CAL_LCDC_EN				2
#define DDR_PWR_BW_CAL_A9_EN				1
#define DDR_PWR_BW_CAL_CP_EN				0

/* DDR_PWR_INTR_EN. */
#define	DDR_PWR_DDR_AXI_TPZ_INTR			7
#define	DDR_PWR_LCDC_TPZ_INTR				6
#define	DDR_PWR_A9_TPZ_INTR				5
#define	DDR_PWR_CP_TPZ_INTR				4
#define	DDR_PWR_BWCAL_DDR_AXI_INTR			3
#define	DDR_PWR_BWCAL_LCDC_INTR				2
#define	DDR_PWR_BWCAL_A9_INTR				1
#define	DDR_PWR_BWCAL_CP_INTR				0

/* DDR_PWR_PCMCTL. */
#define DDR_PWR_PCM_CNT_VALUE				16
#define DDR_PWR_PCM_DELAY_BYPASS			8	
#define DDR_PWR_PCM_MODE				0

/* DDR_PWR_MEMCTL_DTOATOCTL. */
#define DDR_PWR_DTOATOCTL_SJ				24
#define DDR_PWR_DTOATOCTL_ATO_AE			16
#define DDR_PWR_DTOATOCTL_DTO_1_LB			13
#define DDR_PWR_DTOATOCTL_DTO_1_TE			12
#define DDR_PWR_DTOATOCTL_DTO_1_PDR			11
#define DDR_PWR_DTOATOCTL_DTO_1_PDD			10
#define DDR_PWR_DTOATOCTL_DTO_1_IOM			9
#define DDR_PWR_DTOATOCTL_DTO_1_OE			8
#define DDR_PWR_DTOATOCTL_DTO_0_LB			5
#define DDR_PWR_DTOATOCTL_DTO_0_TE			4
#define DDR_PWR_DTOATOCTL_DTO_0_PDR			3
#define DDR_PWR_DTOATOCTL_DTO_0_PDD			2
#define DDR_PWR_DTOATOCTL_DTO_0_IOM			1
#define DDR_PWR_DTOATOCTL_DTO_0_OE			0

/* DDR_PWR_MEMCTL_LPCTL. */
#define DDR_PWR_DDR_AXI_LP_BYPASS			24
#define DDR_PWR_PHY_DDR_LP_BYPASS			16
#define DDR_PWR_DDR_LP_CLK_CLOSE_CNT			8
#define DDR_PWR_CTRL_DDR_LP_BYPASS			0

/* DDR_PWR_CPU0_ARBIT_REQ. */
#define	DDR_PWR_CPU_ARBIT5_PRIOR			21
#define	DDR_PWR_CPU_ARBIT5_REQ				20
#define	DDR_PWR_CPU_ARBIT4_PRIOR			17
#define	DDR_PWR_CPU_ARBIT4_REQ				16
#define	DDR_PWR_CPU_ARBIT3_PRIOR			13
#define	DDR_PWR_CPU_ARBIT3_REQ				12
#define	DDR_PWR_CPU_ARBIT2_PRIOR			9
#define	DDR_PWR_CPU_ARBIT2_REQ				8
#define	DDR_PWR_CPU_ARBIT1_PRIOR			5
#define	DDR_PWR_CPU_ARBIT1_REQ				4
#define	DDR_PWR_CPU_ARBIT0_PRIOR			1
#define	DDR_PWR_CPU_ARBIT0_REQ				0

/* DDR_PWR_CPU_ARBIT_EN. */ 	  
#define	DDR_PWR_CPU_ARBIT5_EN				5
#define	DDR_PWR_CPU_ARBIT4_EN				4
#define	DDR_PWR_CPU_ARBIT3_EN				3
#define	DDR_PWR_CPU_ARBIT2_EN				2
#define	DDR_PWR_CPU_ARBIT1_EN				1
#define	DDR_PWR_CPU_ARBIT0_EN				0

/* DDR_PWR_CPU0_ARBIT_ACK. */
#define	DDR_PWR_CPU_ARBIT_ACK5				5
#define	DDR_PWR_CPU_ARBIT_ACK4				4
#define	DDR_PWR_CPU_ARBIT_ACK3				3
#define	DDR_PWR_CPU_ARBIT_ACK2				2
#define	DDR_PWR_CPU_ARBIT_ACK1				1
#define	DDR_PWR_CPU_ARBIT_ACK0				0

/* DDR_PWR_INTR_EN */
#define DDR_PWR_INTR_DDR_FREQ_ADJ_EN			9
#define DDR_PWR_INTR_TM_32K_EN				8
#define DDR_PWR_INTR_DDR_AXI_TPZ_EN			7
#define DDR_PWR_INTR_LCDC_TPZ_EN			6
#define DDR_PWR_INTR_A7_TPZ_EN				5
#define DDR_PWR_INTR_CP_TPZ_EN				4
#define DDR_PWR_INTR_BWCAL_DDR_AXI_EN			3
#define DDR_PWR_INTR_BWCAL_LCDC_EN			2
#define DDR_PWR_INTR_BWCAL_A7_EN			1
#define DDR_PWR_INTR_BWCAL_CP_EN			0

/* DDR_PWR_INTR_RAW */


/* DDR_PWR_INTR_ST */

/* DDR_PWR_INTR_CLR */
#define DDR_PWR_INTR_DDR_FREQ_ADJ_CLR			9
#define DDR_PWR_INTR_TM_32K_CLR				8
#define DDR_PWR_INTR_DDR_AXI_TPZ_CLR			7
#define DDR_PWR_INTR_LCDC_TPZ_CLR			6
#define DDR_PWR_INTR_A7_TPZ_CLR				5
#define DDR_PWR_INTR_CP_TPZ_CLR				4
#define DDR_PWR_INTR_BWCAL_DDR_AXI_CLR			3
#define DDR_PWR_INTR_BWCAL_LCDC_CLR			2
#define DDR_PWR_INTR_BWCAL_A7_CLR			1
#define DDR_PWR_INTR_BWCAL_CP_CLR			0

#endif /* __ASM_ARCH_REGS_DDR_PWR_H. */
