#ifndef __ASM_ARCH_REGS_CTL_H
#define __ASM_ARCH_REGS_CTL_H

#if defined(CONFIG_CPU_LC1810)
#define CTL_A92M0_INTR_SET			(CTL_BASE + 0x00)
#define CTL_A92M0_INTR_EN			(CTL_BASE + 0x04)
#define CTL_A92M0_INTR_STA			(CTL_BASE + 0x08)
#define CTL_A92M0_INTR_STA_RAW			(CTL_BASE + 0x0C)
#define CTL_M02A9_INTR_SET			(CTL_BASE + 0x10)
#define CTL_M02A9_INTR_EN			(CTL_BASE + 0x14)
#define CTL_M02A9_INTR_STA			(CTL_BASE + 0x18)
#define CTL_M02A9_INTR_STA_RAW			(CTL_BASE + 0x1C)
#define CTL_ARM02A9_INTR_EN 			(CTL_BASE + 0x20)
#define CTL_ARM02A9_INTR_STA			(CTL_BASE + 0x24)
#define CTL_CP2AP_INTR_STA_RAW			(CTL_BASE + 0x28)
#define CTL_ARM02M0_INTR_EN 			(CTL_BASE + 0x30)
#define CTL_ARM02M0_INTR_STA			(CTL_BASE + 0x34)
#define CTL_ARM02M0_INTR_STA_RAW		(CTL_BASE + 0x38)
#define CTL_AP2ARM0_INTR_SET			(CTL_BASE + 0x40)
#define CTL_AP2ARM0_INTR_SET_STA		(CTL_BASE + 0x44)
#elif defined(CONFIG_CPU_LC1813)
#define CTL_ARM2A7_INTR_EN 			(CTL_BASE + 0x20)
#define CTL_ARM2A7_INTR_STA			(CTL_BASE + 0x24)
#define CTL_CP2AP_INTR_STA_RAW			(CTL_BASE + 0x28)
#define CTL_CP2AP_INTR_STA_RAW1			(CTL_BASE + 0x2C)
#define CTL_ARM2A7_INTR_ALL_EN			(CTL_BASE + 0x38)
#define CTL_AP2ARM926_INTR_SET			(CTL_BASE + 0x40)
#define CTL_AP2ARM926_INTR_SET_STA		(CTL_BASE + 0x44)
#endif

#define CTL_ISP_ICM_PRIOR			(CTL_BASE + 0x50)

#if defined(CONFIG_CPU_LC1810)
#define CTL_LCDC_ICM_PRIOR			(CTL_BASE + 0x54)
#endif

#define CTL_DATA_APB_ICM_PRIOR			(CTL_BASE + 0x58)
#define CTL_TOPBRG_ICM_PRIOR			(CTL_BASE + 0x5C)
#define CTL_NFC_ICM_PRIOR			(CTL_BASE + 0x60)

#if defined(CONFIG_CPU_LC1810)
#define CTL_M0_IRAM_ICM_PRIOR			(CTL_BASE + 0x64)
#define CTL_ICM_PRIOR				(CTL_BASE + 0x68)
#define CTL_AP_DMA_ICM_PRIOR			(CTL_BASE + 0x6C)
#define CTL_APB_ICM_PRIOR			(CTL_BASE + 0x70)
#define CTL_ACP_MST0_ICM_PRIOR			(CTL_BASE + 0x74)
#define CTL_ACP_CIPHER_SDIO1_ICM_PRIOR		(CTL_BASE + 0x78)
#define CTL_ACP_MST3_ICM_PRIOR			(CTL_BASE + 0x7C)
#define CTL_ACP_SDIO23_ICM_PRIOR		(CTL_BASE + 0x80)
#elif defined(CONFIG_CPU_LC1813)
#define CTL_ACP_MH2X0_ICM_PRIOR			(CTL_BASE + 0x74)
#define CTL_ACP_MH2X2_ICM_PRIOR			(CTL_BASE + 0x78)
#define CTL_ACP_MH2X3_ICM_PRIOR			(CTL_BASE + 0x7C)
#endif

#define CTL_ACP_MH2X_CH_PRIOR			(CTL_BASE + 0x84)

#if defined(CONFIG_CPU_LC1810)
#define CTL_USB_MH2X_PRIOR			(CTL_BASE + 0x88)
#endif

#define CTL_LP_MODE_CTRL			(CTL_BASE + 0x8C)
#define CTL_ARBITER_EN				(CTL_BASE + 0x90)
#define CTL_CPU0_ARBITER_REQ			(CTL_BASE + 0x94)
#define CTL_CPU1_ARBITER_REQ			(CTL_BASE + 0x98)
#define CTL_CPU0_ARBITER_ACK			(CTL_BASE + 0x9C)
#define CTL_CPU1_ARBITER_ACK			(CTL_BASE + 0xA0)

#if defined(CONFIG_CPU_LC1810)
#define CTL_A92M0_INTR0_SEC 			(CTL_BASE + 0xB0)
#define CTL_A92M0_INTR1_SEC 			(CTL_BASE + 0xB4)
#define CTL_A92M0_INTR2_SEC 			(CTL_BASE + 0xB8)
#define CTL_A92M0_INTR3_SEC 			(CTL_BASE + 0xBC)
#define CTL_A92M0_INTR4_SEC 			(CTL_BASE + 0xC0)
#define CTL_A92M0_INTR5_SEC 			(CTL_BASE + 0xC4)
#define CTL_A92M0_INTR6_SEC 			(CTL_BASE + 0xC8)
#define CTL_A92M0_INTR7_SEC 			(CTL_BASE + 0xCC)
#define CTL_M02A9_INTR0_SEC 			(CTL_BASE + 0xD0)
#define CTL_M02A9_INTR1_SEC 			(CTL_BASE + 0xD4)
#define CTL_M02A9_INTR2_SEC 			(CTL_BASE + 0xD8)
#define CTL_M02A9_INTR3_SEC 			(CTL_BASE + 0xDC)
#define CTL_M02A9_INTR4_SEC 			(CTL_BASE + 0xE0)
#define CTL_M02A9_INTR5_SEC 			(CTL_BASE + 0xE4)
#define CTL_M02A9_INTR6_SEC 			(CTL_BASE + 0xE8)
#define CTL_M02A9_INTR7_SEC 			(CTL_BASE + 0xEC)
#define CTL_USB_SCALEDOWN_MODE			(CTL_BASE + 0x120)
#endif

#define CTL_RAM_EMA_CTRL			(CTL_BASE + 0x124)
#define CTL_MH2X_CH_TRANS_ERR_INTR_EN		(CTL_BASE + 0x128)
#define CTL_MH2X_CH_TRANS_ERR_INTR_STA		(CTL_BASE + 0x12C)
#define CTL_MH2X_CH_TRANS_ERR_INTR_STA_RAW	(CTL_BASE + 0x130)
#define CTL_MH2X_CH_LP_EN			(CTL_BASE + 0x134)
#define CTL_AP_DMAC_LP_EN			(CTL_BASE + 0x138)
#if defined(CONFIG_CPU_LC1810)
#define CTL_EMMC_INIT_EN			(CTL_BASE + 0x140)
#endif
#define CTL_USB_OTG_PHY_RST_CTRL		(CTL_BASE + 0x150)
#define CTL_USB_OTG_PHY_SUSPEND 		(CTL_BASE + 0x154)
#define CTL_USB_OTG_PHY_STA 			(CTL_BASE + 0x158)
#define CTL_USB_OTG_WKUP_INTRAW 		(CTL_BASE + 0x15C)
#define CTL_USB_OTG_WKUP_INTR_STA		(CTL_BASE + 0x160)
#define CTL_USB_OTG_WKUP_INTR_EN		(CTL_BASE + 0x164)
#define CTL_USB_OTG_PHY_CFG0			(CTL_BASE + 0x168)	/* L1813S */
#define CTL_USB_OTG_PHY_CFG1			(CTL_BASE + 0x16C)	/* L1813S */

#if defined(CONFIG_CPU_LC1810)
#define CTL_USB_HOST_PHY_RST_CTRL		(CTL_BASE + 0x170)
#define CTL_USB_HOST_PHY_SUSPEND		(CTL_BASE + 0x174)
#define CTL_USB_HOST_PHY_STA			(CTL_BASE + 0x178)
#define CTL_USB_HOST_WKUP_INTRAW		(CTL_BASE + 0x17C)
#define CTL_USB_HOST_WKUP_INTR_STA		(CTL_BASE + 0x180)
#define CTL_USB_HOST_WKUP_INTR_EN		(CTL_BASE + 0x184)
#define CTL_USB_HSIC_PHY_RST_CTRL		(CTL_BASE + 0x190)
#define CTL_USB_HSIC_PHY_SUSPEND		(CTL_BASE + 0x194)
#define CTL_USB_HSIC_PHY_STA			(CTL_BASE + 0x198)
#define CTL_USB_HSIC_WKUP_INTRAW		(CTL_BASE + 0x19C)
#define CTL_USB_HSIC_WKUP_INTR_STA		(CTL_BASE + 0x1a0)
#define CTL_USB_HSIC_WKUP_INTR_EN		(CTL_BASE + 0x1a4)
#define CTL_USB_HSIC_CTRL			(CTL_BASE + 0x1a8)
#endif

#if defined(CONFIG_CPU_LC1810)
#define CTL_A9_CORE1_CBOOT_JUMP_ADDR		(CTL_BASE + 0x1B0)
#define CTL_A9_CORE1_WBOOT_JUMP_ADDR		(CTL_BASE + 0x1B4)
#define CTL_A9_CORE0_WBOOT_JUMP_ADDR		(CTL_BASE + 0x1B8)
#elif defined(CONFIG_CPU_LC1813)
#define CTL_A7_CORE1_CBOOT_JUMP_ADDR		(CTL_BASE + 0x1B0)
#define CTL_A7_CORE1_WBOOT_JUMP_ADDR		(CTL_BASE + 0x1B4)
#define CTL_A7_CORE0_WBOOT_JUMP_ADDR		(CTL_BASE + 0x1B8)
#endif

#if defined(CONFIG_CPU_LC1810)
#define CTL_ACP_REGION1_LOW_ADDR		(CTL_BASE + 0x1C0)
#define CTL_ACP_REGION1_HIGH_ADDR		(CTL_BASE + 0x1C4)
#define CTL_ACP_REGION1_AXCACHE_PARA		(CTL_BASE + 0x1C8)
#define CTL_ACP_REGION2_LOW_ADDR		(CTL_BASE + 0x1D0)
#define CTL_ACP_REGION2_HIGH_ADDR		(CTL_BASE + 0x1D4)
#define CTL_ACP_REGION2_AXCACHE_PARA		(CTL_BASE + 0x1D8)
#define CTL_ACP_REGION3_LOW_ADDR		(CTL_BASE + 0x1E0)
#define CTL_ACP_REGION3_HIGH_ADDR		(CTL_BASE + 0x1E4)
#define CTL_ACP_REGION3_AXCACHE_PARA		(CTL_BASE + 0x1E8)
#define CTL_ACP_REGION4_LOW_ADDR		(CTL_BASE + 0x1F0)
#define CTL_ACP_REGION4_HIGH_ADDR		(CTL_BASE + 0x1F4)
#define CTL_ACP_REGION4_AXCACHE_PARA		(CTL_BASE + 0x1F8)
#define CTL_ACP_REGION5_LOW_ADDR		(CTL_BASE + 0x200)
#define CTL_ACP_REGION5_HIGH_ADDR		(CTL_BASE + 0x204)
#define CTL_ACP_REGION5_AXCACHE_PARA		(CTL_BASE + 0x208)
#define CTL_ACP_REGION6_LOW_ADDR		(CTL_BASE + 0x210)
#define CTL_ACP_REGION6_HIGH_ADDR		(CTL_BASE + 0x214)
#define CTL_ACP_REGION6_AXCACHE_PARA		(CTL_BASE + 0x218)
#define CTL_ACP_DUFAULT_AXCACHE_PARA		(CTL_BASE + 0x220)
#define CTL_CLK32K_GLITCH_BYPASS		(CTL_BASE + 0x224)
#elif defined(CONFIG_CPU_LC1813)
#define CTL_CLK32K_GLITCH_EN			(CTL_BASE + 0x224)
#endif

#define CTL_SSI0_PROTOCOL_CTRL			(CTL_BASE + 0x230)
#define CTL_SSI1_PROTOCOL_CTRL			(CTL_BASE + 0x234)
#define CTL_SSI2_PROTOCOL_CTRLL 		(CTL_BASE + 0x238)
#define CTL_SSI3_PROTOCOL_CTRL			(CTL_BASE + 0x23C)

#if defined(CONFIG_CPU_LC1810)
#define CTL_A9_NEON_EXCEPT_INTR_STA_RAW 	(CTL_BASE + 0x250)
#define CTL_A9_NEON_EXCEPT_INTR_STA 		(CTL_BASE + 0x254)
#define CTL_A9_NEON_EXCEPT_INTR_EN		(CTL_BASE + 0x258)
#define CTL_CPHY1_ERROR_STAT			(CTL_BASE + 0x264)
#define CTL_CPHY1_STAT				(CTL_BASE + 0x26c)
#define CTL_CPHY1_RSTZ				(CTL_BASE + 0x274)
#define CTL_CPHY1_CTRL0 			(CTL_BASE + 0x280)
#define CTL_CPHY1_CTRL1 			(CTL_BASE + 0x284)
#define CTL_CPHY1_MODE				(CTL_BASE + 0x28C)
#define CTL_A9_INTR_STA 			(CTL_BASE + 0x298)
#define CTL_HSIC_PHY_CTRL0			(CTL_BASE + 0x2A0)
#define CTL_HSIC_PHY_CTRL1			(CTL_BASE + 0x2A4)
#define CTL_HSIC_PHY_CTRL2			(CTL_BASE + 0x2A8)
#endif

#if defined(CONFIG_CPU_LC1813)
#define CTL_CPHY_DUMMY				0
#define CTL_CPHY1_ERROR_STAT		CTL_CPHY_DUMMY
#define CTL_CPHY1_STAT				CTL_CPHY_DUMMY
#define CTL_CPHY1_RSTZ				CTL_CPHY_DUMMY
#define CTL_CPHY1_CTRL0 			CTL_CPHY_DUMMY
#define CTL_CPHY1_CTRL1 			CTL_CPHY_DUMMY
#define CTL_CPHY1_MODE				CTL_CPHY_DUMMY
#endif

#define CTL_CPHY0_ERROR_STAT			(CTL_BASE + 0x260)
#define CTL_CPHY0_STAT				(CTL_BASE + 0x268)
#define CTL_CPHY0_RSTZ				(CTL_BASE + 0x270)
#define CTL_CPHY0_CTRL0 			(CTL_BASE + 0x278)
#define CTL_CPHY0_CTRL1 			(CTL_BASE + 0x27C)
#define CTL_CPHY0_MODE				(CTL_BASE + 0x288)

#if defined(CONFIG_CPU_LC1810)
#define CTL_A9_WBOOT_JUMP_ADDR1 		(CTL_BASE + 0x290)
#define CTL_A9_WBOOT_JUMP_ADDR2 		(CTL_BASE + 0x294)

#elif defined(CONFIG_CPU_LC1813)

#define CTL_A7_WBOOT_JUMP_ADDR1 		(CTL_BASE + 0x290)
#define CTL_A7_WBOOT_JUMP_ADDR2 		(CTL_BASE + 0x294)
#define CTL_A7_INTR_STA 			(CTL_BASE + 0x298)
#define CTL_A7_INTR_STA1 			(CTL_BASE + 0x29C)
#define CTL_A7_CORE2_CBOOT_JUMP_ADDR 		(CTL_BASE + 0x2B0)
#define CTL_A7_CORE2_WBOOT_JUMP_ADDR 		(CTL_BASE + 0x2B4)
#define CTL_A7_CORE3_CBOOT_JUMP_ADDR 		(CTL_BASE + 0x2B8)
#define CTL_A7_CORE3_WBOOT_JUMP_ADDR 		(CTL_BASE + 0x2BC)
#define CTL_A7_CFGTE 				(CTL_BASE + 0x2C0)
#define CTL_ISP_HIGH_ADDR 			(CTL_BASE + 0x2D0)
#define CTL_CP_FUNCTION_TEST 			(CTL_BASE + 0x2FC)
#define CTL_2DACC_STA				(CTL_BASE + 0x2D4)	/* L1813S */
#define CTL_MMC0IOCTRL				(CTL_BASE + 0x2D8)	/* L1813S */
#define CTL_M02MMC1_EN				(CTL_BASE + 0x2DC)	/* L1813S */
#endif

/* CTL_A92M0. */		
#define CTL_A92M0_INTR_EN_INTR_EN			16
#define CTL_A92M0_INTR_SRC7_INTR			7
#define CTL_A92M0_INTR_SRC6_INTR			6
#define CTL_A92M0_INTR_SRC5_INTR			5
#define CTL_A92M0_INTR_SRC4_INTR			4
#define CTL_A92M0_INTR_SRC3_INTR			3
#define CTL_A92M0_INTR_SRC2_INTR			2
#define CTL_A92M0_INTR_SRC1_INTR			1
#define CTL_A92M0_INTR_SRC0_INTR			0

/* CTL_A92M0_INTR_STA_RAW. */			
#define CTL_A92M0_INTR_STA_RAW_INTR_SRC7_STA_RAW	14
#define CTL_A92M0_INTR_STA_RAW_INTR_SRC6_STA_RAW	12
#define CTL_A92M0_INTR_STA_RAW_INTR_SRC5_STA_RAW	10
#define CTL_A92M0_INTR_STA_RAW_INTR_SRC4_STA_RAW	8
#define CTL_A92M0_INTR_STA_RAW_INTR_SRC3_STA_RAW	6
#define CTL_A92M0_INTR_STA_RAW_INTR_SRC2_STA_RAW	4
#define CTL_A92M0_INTR_STA_RAW_INTR_SRC1_STA_RAW	2
#define CTL_A92M0_INTR_STA_RAW_INTR_SRC0_STA_RAW	0

/* CTL_M02A9. */
#define CTL_M02A9_INTR_EN_INTR_EN			16
#define CTL_M02A9_INTR_SRC7_INTR			7
#define CTL_M02A9_INTR_SRC6_INTR			6
#define CTL_M02A9_INTR_SRC5_INTR			5
#define CTL_M02A9_INTR_SRC4_INTR			4
#define CTL_M02A9_INTR_SRC3_INTR			3
#define CTL_M02A9_INTR_SRC2_INTR			2
#define CTL_M02A9_INTR_SRC1_INTR			1
#define CTL_M02A9_INTR_SRC0_INTR			0

/* CTL_M02A9_INTR_STA_RAW. */
#define	CTL_M02A9_INTR_STA_RAW_INTR_SRC7_STA_RAW	14
#define	CTL_M02A9_INTR_STA_RAW_INTR_SRC6_STA_RAW	12
#define	CTL_M02A9_INTR_STA_RAW_INTR_SRC5_STA_RAW	10
#define	CTL_M02A9_INTR_STA_RAW_INTR_SRC4_STA_RAW	8
#define	CTL_M02A9_INTR_STA_RAW_INTR_SRC3_STA_RAW	6
#define	CTL_M02A9_INTR_STA_RAW_INTR_SRC2_STA_RAW	4
#define	CTL_M02A9_INTR_STA_RAW_INTR_SRC1_STA_RAW	2
#define	CTL_M02A9_INTR_STA_RAW_INTR_SRC0_STA_RAW	0

/* CTL_ARM02A9. */
#define	CTL_ARM02A9_INTR_EN_INTR_EN			16
#define	CTL_ARM02A9_INTR_SRC7_INTR			7
#define	CTL_ARM02A9_INTR_SRC6_INTR			6
#define	CTL_ARM02A9_INTR_SRC5_INTR			5
#define	CTL_ARM02A9_INTR_SRC4_INTR			4
#define	CTL_ARM02A9_INTR_SRC3_INTR			3
#define	CTL_ARM02A9_INTR_SRC2_INTR			2
#define	CTL_ARM02A9_INTR_SRC1_INTR			1
#define	CTL_ARM02A9_INTR_SRC0_INTR			0

/* CTL_CP2AP_INTR_STA_RAW. */
#define	CTL_CP2AP_INTR_STA_RAW_INTR_SRC7_STA_RAW	14
#define	CTL_CP2AP_INTR_STA_RAW_INTR_SRC6_STA_RAW	12
#define	CTL_CP2AP_INTR_STA_RAW_INTR_SRC5_STA_RAW	10
#define	CTL_CP2AP_INTR_STA_RAW_INTR_SRC4_STA_RAW	8
#define	CTL_CP2AP_INTR_STA_RAW_INTR_SRC3_STA_RAW	6
#define	CTL_CP2AP_INTR_STA_RAW_INTR_SRC2_STA_RAW	4
#define	CTL_CP2AP_INTR_STA_RAW_INTR_SRC1_STA_RAW	2
#define	CTL_CP2AP_INTR_STA_RAW_INTR_SRC0_STA_RAW	0

/* CTL_ARM02M0. */
#define	CTL_ARM02M0_INTR_EN_INTR_EN			16
#define	CTL_ARM02M0_INTR_SRC7_INTR			7
#define	CTL_ARM02M0_INTR_SRC6_INTR			6
#define	CTL_ARM02M0_INTR_SRC5_INTR			5
#define	CTL_ARM02M0_INTR_SRC4_INTR			4
#define	CTL_ARM02M0_INTR_SRC3_INTR			3
#define	CTL_ARM02M0_INTR_SRC2_INTR			2
#define	CTL_ARM02M0_INTR_SRC1_INTR			1
#define	CTL_ARM02M0_INTR_SRC0_INTR			0

/* CTL_ARM02M0_INTR_STA_RAW */
#define	CTL_ARM02M0_INTR_STA_RAW_INTR_SRC7_STA_RAW	14
#define	CTL_ARM02M0_INTR_STA_RAW_INTR_SRC6_STA_RAW	12
#define	CTL_ARM02M0_INTR_STA_RAW_INTR_SRC5_STA_RAW	10
#define	CTL_ARM02M0_INTR_STA_RAW_INTR_SRC4_STA_RAW	8
#define	CTL_ARM02M0_INTR_STA_RAW_INTR_SRC3_STA_RAW	6
#define	CTL_ARM02M0_INTR_STA_RAW_INTR_SRC2_STA_RAW	4
#define	CTL_ARM02M0_INTR_STA_RAW_INTR_SRC1_STA_RAW	2
#define	CTL_ARM02M0_INTR_STA_RAW_INTR_SRC0_STA_RAW	0

/* CTL_AP2ARM0_INTR_SET_STA. */
#define	CTL_AP2ARM0_INTR_SET_STA_INTR_SET_STA8		8
#define	CTL_AP2ARM0_INTR_SET_STA_INTR_SET_STA7		7
#define	CTL_AP2ARM0_INTR_SET_STA_INTR_SET_STA6		6
#define	CTL_AP2ARM0_INTR_SET_STA_INTR_SET_STA5		5
#define	CTL_AP2ARM0_INTR_SET_STA_INTR_SET_STA4		4
#define	CTL_AP2ARM0_INTR_SET_STA_INTR_SET_STA3		3
#define	CTL_AP2ARM0_INTR_SET_STA_INTR_SET_STA2		2
#define	CTL_AP2ARM0_INTR_SET_STA_INTR_SET_STA1		1
#define	CTL_AP2ARM0_INTR_SET_STA_INTR_SET_STA0		0

/* CTL_ISP_ICM_PRIOR. */
#define	CTL_ISP_ICM_PRIOR_AP_DMAC_PRIOR			8
#define	CTL_ISP_ICM_PRIOR_A9_PRIOR			4
#define	CTL_ISP_ICM_PRIOR_M0_PRIOR			0

/* CTL_LCDC_ICM_PRIOR. */
#define	CTL_LCDC_ICM_PRIOR_A9_PRIOR			4
#define	CTL_LCDC_ICM_PRIOR_M0_PRIOR			0

/* CTL_DATA_APB_ICM_PRIOR. */
#define	CTL_DATA_APB_ICM_PRIOR_A9_PRIOR			8
#define	CTL_DATA_APB_ICM_PRIOR_AP_DMAS_PRIOR		4
#define	CTL_DATA_APB_ICM_PRIOR_AU_DMAS_PRIOR		0

/* CTL_TOPBRG_ICM_PRIOR. */
#define	CTL_TOPBRG_ICM_PRIOR_A9_PRIOR			12
#define	CTL_TOPBRG_ICM_PRIOR_M0_PRIOR			8
#define	CTL_TOPBRG_ICM_PRIOR_AP_DMAS_BUS_PRIOR		4
#define	CTL_TOPBRG_ICM_PRIOR_AU_DMAS_BUS_PRIOR		0

/* CTL_NFC_ICM_PRIOR. */
#define	CTL_NFC_ICM_PRIOR_AXI_AHB0_BUS_PRIOR		4
#define	CTL_NFC_ICM_PRIOR_AP_DMAS_BUS_PRIOR		0

/* CTL_M0_IRAM_ICM_PRIOR. */
#define	CTL_M0_IRAM_ICM_PRIOR_AP_DMAC_BUS_PRIOR		8
#define	CTL_M0_IRAM_ICM_PRIOR_A9_PRIOR			4
#define	CTL_M0_IRAM_ICM_PRIOR_M0_PRIOR			0

/* CTL_ICM_PRIOR. */
#define	CTL_ICM_PRIOR_AXI_AHB0_BUS_PRIOR		4
#define	CTL_ICM_PRIOR_M0_BUS_PRIOR			0

/* CTL_AP_DMA_ICM_PRIOR. */
#define	CTL_AP_DMA_ICM_PRIOR_AXI_AHB0_BUS_PRIOR		4
#define	CTL_AP_DMA_ICM_PRIOR_M0_BUS_PRIOR		0

/* CTL_APB_ICM_PRIOR. */
#define	CTL_APB_ICM_PRIOR_A9_PRIOR			4
#define	CTL_APB_ICM_PRIOR_M0_PRIOR			0

/* CTL_ACP_MST0_ICM_PRIOR. */
#define	CTL_ACP_MST0_ICM_PRIOR_SDIO0_PRIOR		8
#define	CTL_ACP_MST0_ICM_PRIOR_AP_DMAC_PRIOR		4
#define	CTL_ACP_MST0_ICM_PRIOR_NFC_PRIOR		0

/* CTL_ACP_CIPHER_SDIO1_ICM_PRIOR. */
#define	CTL_ACP_CIPHER_SDIO1_ICM_PRIOR_SDIO1_PRIOR	4
#define	CTL_ACP_CIPHER_SDIO1_ICM_PRIOR_CIPHER_PRIOR	0

/* CTL_ACP_MST3_ICM_PRIOR. */
#define	CTL_ACP_MST3_ICM_PRIOR_AP_DMAS_BUS_PRIOR	4
#define	CTL_ACP_MST3_ICM_PRIOR_AU_DMAS_BUS_PRIOR	0

/* CTL_ACP_SDIO23_ICM_PRIOR. */
#define	CTL_ACP_SDIO23_ICM_PRIOR_SDIO3_PRIOR		4
#define	CTL_ACP_SDIO23_ICM_PRIOR_SDIO2_PRIOR		0

/* CTL_ACP_MH2X_CH_PRIOR. */
#define	CTL_ACP_MH2X_CH_PRIOR_CH3_PRIOR			12
#define	CTL_ACP_MH2X_CH_PRIOR_CH2_PRIOR			8
#define	CTL_ACP_MH2X_CH_PRIOR_CH1_PRIOR			4
#define	CTL_ACP_MH2X_CH_PRIOR_CH0_PRIOR			0

/* CTL_USB_MH2X_PRIOR. */
#define	CTL_USB_MH2X_PRIOR_USB_HSIC_CH_PRIOR		8
#define	CTL_USB_MH2X_PRIOR_USB_HOST_CH_PRIOR		4
#define	CTL_USB_MH2X_PRIOR_USB_OTG_CH_PRIOR		0

/* CTL_LP_MODE_CTRL. */
#define	CTL_LP_MODE_CTRL_AHB_IDLE_LIMIT			8
#define	CTL_LP_MODE_CTRL_CTL_LP_EN			0

/* CTL_ARBITER_EN. */
#define CTL_ARBITER_EN_ARBIT7_EN			7
#define CTL_ARBITER_EN_ARBIT6_EN			6
#define CTL_ARBITER_EN_ARBIT5_EN			5
#define CTL_ARBITER_EN_ARBIT4_EN			4
#define CTL_ARBITER_EN_ARBIT3_EN			3
#define CTL_ARBITER_EN_ARBIT2_EN			2
#define CTL_ARBITER_EN_ARBIT1_EN			1
#define CTL_ARBITER_EN_ARBIT0_EN			0
								
/* CTL_CPUX_ARBITER_REQ. */
#define CTL_CPU_ARBITER_REQ_CPU_ARBIT7_PRIOR		29
#define CTL_CPU_ARBITER_REQ_CPU_ARBIT7_REQ		28
#define CTL_CPU_ARBITER_REQ_CPU_ARBIT6_PRIOR		25
#define CTL_CPU_ARBITER_REQ_CPU_ARBIT6_REQ		24
#define CTL_CPU_ARBITER_REQ_CPU_ARBIT5_PRIOR		21
#define CTL_CPU_ARBITER_REQ_CPU_ARBIT5_REQ		20
#define CTL_CPU_ARBITER_REQ_CPU_ARBIT4_PRIOR		17
#define CTL_CPU_ARBITER_REQ_CPU_ARBIT4_REQ		16
#define CTL_CPU_ARBITER_REQ_CPU_ARBIT3_PRIOR		13
#define CTL_CPU_ARBITER_REQ_CPU_ARBIT3_REQ		12
#define CTL_CPU_ARBITER_REQ_CPU_ARBIT2_PRIOR		9
#define CTL_CPU_ARBITER_REQ_CPU_ARBIT2_REQ		8
#define CTL_CPU_ARBITER_REQ_CPU_ARBIT1_PRIOR		5
#define CTL_CPU_ARBITER_REQ_CPU_ARBIT1_REQ		4
#define CTL_CPU_ARBITER_REQ_CPU_ARBIT0_PRIOR		1
#define CTL_CPU_ARBITER_REQ_CPU_ARBIT0_REQ		0

/* CTL_CPUX_ARBITER_ACK */
#define CTL_CPU_ARBITER_ACK_CPU_ACK7			7
#define CTL_CPU_ARBITER_ACK_CPU_ACK6			6
#define CTL_CPU_ARBITER_ACK_CPU_ACK5			5
#define CTL_CPU_ARBITER_ACK_CPU_ACK4			4
#define CTL_CPU_ARBITER_ACK_CPU_ACK3			3
#define CTL_CPU_ARBITER_ACK_CPU_ACK2			2
#define CTL_CPU_ARBITER_ACK_CPU_ACK1			1
#define CTL_CPU_ARBITER_ACK_CPU_ACK0			0

/* CTL_USB_SCALEDOWN_MODE */
#define	CTL_USB_SCALEDOWN_MODE_USB_HSIC_SCALEDOWN	4
#define	CTL_USB_SCALEDOWN_MODE_USB_OTG_SCALEDOWN	2
#define	CTL_USB_SCALEDOWN_MODE_USB_HOST_SCALEDOWN	0

/* CTL_MH2X. */
#define	CTL_MH2X_CH_TRANS_ERR_USB_MH2X_CH2_INTR		6
#define	CTL_MH2X_CH_TRANS_ERR_USB_MH2X_CH1_INTR		5
#define	CTL_MH2X_CH_TRANS_ERR_USB_MH2X_CH0_INTR		4
#define	CTL_MH2X_CH_TRANS_ERR_ACP_MH2X_CH3_INTR		3
#define	CTL_MH2X_CH_TRANS_ERR_ACP_MH2X_CH2_INTR		2
#define	CTL_MH2X_CH_TRANS_ERR_ACP_MH2X_CH1_INTR		1
#define	CTL_MH2X_CH_TRANS_ERR_ACP_MH2X_CH0_INTR		0

/* CTL_MH2X_CH_LP_EN. */
#define	CTL_MH2X_CH_LP_EN_USB_MH2X_CH2_LP_EN		6
#define	CTL_MH2X_CH_LP_EN_USB_MH2X_CH1_LP_EN		5
#define	CTL_MH2X_CH_LP_EN_USB_MH2X_CH0_LP_EN		4
#define	CTL_MH2X_CH_LP_EN_ACP_MH2X_CH3_LP_EN		3
#define	CTL_MH2X_CH_LP_EN_ACP_MH2X_CH2_LP_EN		2
#define	CTL_MH2X_CH_LP_EN_ACP_MH2X_CH1_LP_EN		1
#define	CTL_MH2X_CH_LP_EN_ACP_MH2X_CH0_LP_EN		0

/* CTL_AP_DMAC_LP_EN. */
#define	CTL_AP_DMAC_LP_EN_AP_DMAC_LP_EN			0

/* CTL_USB_OTG_PHY_STA */
#define	CTL_USB_OTG_PHY_STA_LINESTATE			2
#define	CTL_USB_OTG_PHY_STA_FSVMINUS			1
#define	CTL_USB_OTG_PHY_STA_FSVPLUS			0

/* CTL_USB_OTG_PHY_CFG0 */
#define CTL_USB_OTG_PHY_CFG0_TXRESTUNE0		28
#define CTL_USB_OTG_PHY_CFG0_TXRISETUNE0	20
#define CTL_USB_OTG_PHY_CFG0_TXPREEMPPULSETUNE0	18
#define CTL_USB_OTG_PHY_CFG0_TXPREEMPAMPTUNE0	16

/* CTL_USB_HOST_PHY_SUSPEND. */
#define	CTL_USB_HOST_PHY_SUSPEND_PLLBGOE		8
#define	CTL_USB_HOST_PHY_SUSPEND_FORCE_SUSPEND_EXIT	4
#define	CTL_USB_HOST_PHY_SUSPEND_USBPHY_SUSPEND_N	0

/* CTL_USB_HOST_PHY_STA. */
#define	CTL_USB_HOST_PHY_STA_LINESTATE			2
#define	CTL_USB_HOST_PHY_STA_FSVMINUS			1
#define	CTL_USB_HOST_PHY_STA_FSVPLUS			0

/* CTL_USB_HSIC_PHY_STA. */
#define	CTL_USB_HSIC_PHY_STA_LINESTATE			2
#define	CTL_USB_HSIC_PHY_STA_FSVMINUS			1
#define	CTL_USB_HSIC_PHY_STA_FSVPLUS			0

/* CTL_USB_HSIC_CTRL. */
#define	CTL_USB_HSIC_CTRL_HSIC_TXSRTUNE			24
#define	CTL_USB_HSIC_CTRL_HSIC_TXRPUTUNE		20
#define	CTL_USB_HSIC_CTRL_HSIC_TXRPDTUNE		16
#define	CTL_USB_HSIC_CTRL_HSIC_TXBITSTUFFENH		14
#define	CTL_USB_HSIC_CTRL_HSIC_TXBITSTUFFEN		13
#define	CTL_USB_HSIC_CTRL_HSIC_SLEEPM			12
#define	CTL_USB_HSIC_CTRL_HSIC_LOOPBACKENB		11
#define	CTL_USB_HSIC_CTRL_HSIC_COMMONONN		10
#define	CTL_USB_HSIC_CTRL_HSIC_SS_SCALEDOWN_MODE	8
#define	CTL_USB_HSIC_CTRL_HSIC_UTMI_HOSTDISCONNECT	7
#define	CTL_USB_HSIC_CTRL_HSIC_UTMIOTG_DPPULLDOWN	6
#define	CTL_USB_HSIC_CTRL_HSIC_UTMIOTG_DMPULLDOWN	5
#define	CTL_USB_HSIC_CTRL_HSIC_UTMIOTG_IDDIG		4
#define	CTL_USB_HSIC_CTRL_HSIC_PORTRESET		3
#define	CTL_USB_HSIC_CTRL_HSIC_SUSPENDM_CTL		2
#define	CTL_USB_HSIC_CTRL_HSIC_POR_CTL			1
#define	CTL_USB_HSIC_CTRL_HSIC_IF_SELECT_HSIC		0

/* CTL_ACP_REGIONX_AXCACHE_PARA. */
#define	CTL_ACP_REGION_AXCACHE_PARA_ACP_REGION_AXUSER0		4
#define	CTL_ACP_REGION_AXCACHE_PARA_ACP_REGION_AXCACHE_PARA	0

/* CTL_A9_NEON. */
#define	CTL_A9_NEON_EXCEPT_A9_CORE1_NEON_INTR		1
#define	CTL_A9_NEON_EXCEPT_A9_CORE0_NEON_INTR		0

/* CTL_CPHYX_ERROR_STAT. */
#define	CTL_CPHY0_ERROR_STAT_CTL_DPHY_ERRCONTENTIONLP13		28
#define	CTL_CPHY0_ERROR_STAT_CTL_DPHY_ERRCONTENTIONLP03		27
#define	CTL_CPHY0_ERROR_STAT_CTL_DPHY_ERRCONTROL3		26
#define	CTL_CPHY0_ERROR_STAT_CTL_DPHY_ERRSYNCESC3		25
#define	CTL_CPHY0_ERROR_STAT_CTL_DPHY_ERRESC3			24
#define	CTL_CPHY0_ERROR_STAT_CTL_DPHY_ERRCONTENTIONLP12		20
#define	CTL_CPHY0_ERROR_STAT_CTL_DPHY_ERRCONTENTIONLP02		19
#define	CTL_CPHY0_ERROR_STAT_CTL_DPHY_ERRCONTROL2		18
#define	CTL_CPHY0_ERROR_STAT_CTL_DPHY_ERRSYNCESC2		17
#define	CTL_CPHY0_ERROR_STAT_CTL_DPHY_ERRESC2			16
#define	CTL_CPHY0_ERROR_STAT_CTL_DPHY_ERRCONTENTIONLP11		12
#define	CTL_CPHY0_ERROR_STAT_CTL_DPHY_ERRCONTENTIONLP01		11
#define	CTL_CPHY0_ERROR_STAT_CTL_DPHY_ERRCONTROL1		10
#define	CTL_CPHY0_ERROR_STAT_CTL_DPHY_ERRSYNCESC1		9
#define	CTL_CPHY0_ERROR_STAT_CTL_DPHY_ERRESC1			8
#define	CTL_CPHY0_ERROR_STAT_CTL_DPHY_ERRCONTENTIONLP10		4
#define	CTL_CPHY0_ERROR_STAT_CTL_DPHY_ERRCONTENTIONLP0		3
#define	CTL_CPHY0_ERROR_STAT_CTL_DPHY_ERRCONTROL0		2
#define	CTL_CPHY0_ERROR_STAT_CTL_DPHY_ERRSYNCESC0		1
#define	CTL_CPHY0_ERROR_STAT_CTL_DPHY_ERRESC0			0

/* CTL_CPHYX_STAT. */
#define	CTL_CPHY0_STAT_
#define	CTL_CPHY0_STAT_CTL_CPHY_STOPSTATEDATA3			23
#define	CTL_CPHY0_STAT_CTL_CPHY_STOPSTATEDATA2			22
#define	CTL_CPHY0_STAT_CTL_CPHY_STOPSTATEDATA1			21
#define	CTL_CPHY0_STAT_CTL_CPHY_STOPSTATEDATA0			20
#define	CTL_CPHY0_STAT_CTL_CPHY_ULPSACTIVENOT3			19
#define	CTL_CPHY0_STAT_CTL_CPHY_ULPSACTIVENOT2			18
#define	CTL_CPHY0_STAT_CTL_CPHY_ULPSACTIVENOT1			17
#define	CTL_CPHY0_STAT_CTL_CPHY_ULPSACTIVENOT0			16
#define	CTL_CPHY0_STAT_CTL_CPHY_RXLPDTESC3			15
#define	CTL_CPHY0_STAT_CTL_CPHY_RXLPDTESC2			14
#define	CTL_CPHY0_STAT_CTL_CPHY_RXLPDTESC1			13
#define	CTL_CPHY0_STAT_CTL_CPHY_RXLPDTESC0			12
#define	CTL_CPHY0_STAT_CTL_CPHY_RXULPSESC3			11
#define	CTL_CPHY0_STAT_CTL_CPHY_RXULPSESC2			10
#define	CTL_CPHY0_STAT_CTL_CPHY_RXULPSESC1			9
#define	CTL_CPHY0_STAT_CTL_CPHY_RXULPSESC0			8
#define	CTL_CPHY0_STAT_CTL_CPHY_RXULPSCLKNOT			1
#define	CTL_CPHY0_STAT_CTL_CPHY_STOPSTATECLK			0

/* CTL_CPHYX_RSTZ. */
#define	CTL_CPHY0_RSTZ_CTL_CPHY_ENABLE_3			6
#define	CTL_CPHY0_RSTZ_CTL_CPHY_ENABLE_2			5
#define	CTL_CPHY0_RSTZ_CTL_CPHY_ENABLE_1			4
#define	CTL_CPHY0_RSTZ_CTL_CPHY_ENABLE_0			3
#define	CTL_CPHY0_RSTZ_CTL_CPHY_ENABLECLK			2
#define	CTL_CPHY0_RSTZ_CTL_CPHY_RSTZ				1
#define	CTL_CPHY0_RSTZ_CTL_CPHY_SHUTDOWNZ			0

/* CTL_CPHYX_CTRL0. */
#define	CTL_CPHY0_CTRL0_CTL_CPHY_TESTCLK			1
#define	CTL_CPHY0_CTRL0_CTL_CPHY_TESTCLR			0

/* CTL_CPHYX_CTRL1. */
#define	CTL_CPHY0_CTRL1_CTL_CPHY_TESTEN				16
#define	CTL_CPHY0_CTRL1_CTL_CPHY_TESTOUT			8
#define	CTL_CPHY0_CTRL1_CTL_CPHY_TESTDIN			0

/* CTL_CPHYX_MODE. */
#define	CTL_CPHY0_MODE_CTL_CPHY_FORCETXSTOPMODE			3
#define	CTL_CPHY0_MODE_CTL_CPHY_FORCERXMODE			2
#define	CTL_CPHY0_MODE_CTL_CPHY_TURNDISABLE			1
#define	CTL_CPHY0_MODE_CTL_CPHY_TURNREQUEST			0

/* CTL_A9_INTR_STA. */
#define	CTL_A9_INTR_STA_NFIQ1					3
#define	CTL_A9_INTR_STA_NFIQ0					2
#define	CTL_A9_INTR_STA_NIRQ1					1
#define	CTL_A9_INTR_STA_NIRQ0					0

/* HSIC_PHY_CTRL0. */
#define	HSIC_PHY_CTRL0_CTL_TESTDOUT_SEL				16
#define	HSIC_PHY_CTRL0_CTL_HSICPHY_TESTDOUT			8
#define	HSIC_PHY_CTRL0_CTL_HSICPHY_TESTDIN			0

#endif /* __ASM_ARCH_REGS_CTL_H */
