#ifndef __ASM_ARCH_REGS_KBS_H
#define __ASM_ARCH_REGS_KBS_H

#define KBS_CTL 				(0x00)
#define KBS_DIRKEY_CTL				(0x04)
#define KBS_MASK				(0x08)
#define KBS_DETECT_INTVAL			(0x0C)
#define KBS_DEBOUNCE_INTVAL			(0x10)
#define KBS_LONG_REPEAT_INTVAL 			(0x14)
#define KBS_ROTARY0 				(0x18)
#define KBS_ROTARY1 				(0x1C)
#define KBS_MTXKEY_MANUAL_ROWOUT		(0x20)
#define KBS_MTXKEY_MANUAL_COLIN 		(0x24)
#define KBS_MTXKEY_FIFO 			(0x28)
#define KBS_MTXKEY_ASREG0			(0x2C)
#define KBS_MTXKEY_ASREG1			(0x30)
#define KBS_DIRKEY_INT				(0x34)
#define KBS_MTXROT_INT				(0x38)
#define KBS_DIRKEY_INT_RAW			(0x3C)
#define KBS_MTXROT_INT_RAW			(0x40)
#define KBS_DIRKEY_INT_EN			(0x44)
#define KBS_MTXROT_INT_EN			(0x48)

/* KBS_CTL. */
#define KBS_DEBUG_EN				12
#define KBS_ROTARY1_EN				9
#define KBS_ROTARY0_EN				8
#define KBS_MTXKEY_PULL_CFG			4
#define KBS_MTXKEY_LONG_EN			3
#define KBS_MTXKEY_REPEAT_EN			2
#define KBS_MTXKEY_AUTOSCAN_EN			1
#define KBS_MTXKEY_EN				0

/* KBS_DIRKEY_CTL. */
#define KBS_DIRKEY_PULL_CFG			24
#define KBS_DIRKEY_LPRS_EN			16
#define KBS_DIRKEY_RPRS_EN			8
#define KBS_DIRKEY_EN				0

/* KBS_MASK. */
#define KBS_DIRKEY_MASK				16
#define KBS_MTXKEY_COL_MASK			8
#define KBS_MTXKEY_ROW_MASK			0

/* KBS_DETECT_INTVAL. */
#define KBS_DIRKEY_RELEASE_INTVAL		24
#define KBS_DIRKEY_PRESS_INTVAL			16
#define KBS_MTXKEY_RELEASE_INTVAL		8
#define KBS_MTXKEY_PRESS_INTVAL			0

/* KBS_DBC_INTVAL. */
#define KBS_ROTARY_DBC_INTVAL			8
#define KBS_MTXKEY_DBC_INTVAL			0

/* KBS_LPRS_INTVAL. */
#define KBS_LONG_INTVAL				10
#define KBS_REPEAT_INTVAL			0

/* KBS_ROTARYX. */
#define KBS_ROTARY_CNT0_OF			9
#define KBS_ROTARY_CNT0_UF			8
#define KBS_ROTARY_ROTARY_CNT0			0

/* KBS_MTXKEY_MANUAL_ROWOUT. */
#define KBS_MTXKEY_MANUAL_RELEASE		8
#define KBS_MTXKEY_ROW_SCAN_OUT			0

/* KBS_MTXKEY_FIFO. */
#define KBS_MTXKEY_FIFO_FLUSH			14
#define KBS_MTXKEY_FIFO_PUSH_ERROR 		13
#define KBS_MTXKEY_FIFO_POP_ERROR		12
#define KBS_MTXKEY_FIFO_FULL			11
#define KBS_MTXKEY_FIFO_AL_FULL			10
#define KBS_MTXKEY_FIFO_EMPTY			9
#define KBS_MTXKEY_FIFO_AL_EMPTY		8
#define KBS_MTXKEY_SINGLE_KEY_ROW		4
#define KBS_MTXKEY_SINGLE_KEY_COL		0

/* KBS_MTXKEY_ASREGX. */
#define KBS_MTXKEY_ASREG_ROW3			24
#define KBS_MTXKEY_ASREG_ROW2			16
#define KBS_MTXKEY_ASREG_ROW1			8
#define KBS_MTXKEY_ASREG_ROW0			0

/* KBS_DIRKEY_INT. */
#define KBS_DIRKEY_RELEASE_INTR			24
#define KBS_DIRKEY_LONG_INTR			16
#define KBS_DIRKEY_REPEAT_INTR			8
#define KBS_DIRKEY_PRESS_INTR			0

/* KBS_MTXROT_INT. */
#define KBS_ROTARY1_INTR			9
#define KBS_ROTARY0_INTR			8
#define KBS_MTXKEY_RELEASE_INTR			4
#define KBS_MTXKEY_LONG_INTR			3
#define KBS_MTXKEY_REPEAT_INTR			2
#define KBS_MTXKEY_FIFO_UPDATE_INTR		1
#define KBS_MTXKEY_PRESS_INTR			0

#endif /* __ASM_ARCH_REGS_KBS_H. */
