#ifndef __ASM_ARCH_REGS_SECURITY_H
#define __ASM_ARCH_REGS_SECURITY_H

#define SECURITY_SEC_CF 			(SECURITY_BASE + 0x00)
#define SECURITY_EFUSE_CTRL 			(SECURITY_BASE + 0x04)
#define SECURITY_SEC_MODE			(SECURITY_BASE + 0x08)
#define SECURITY_CONV_S0_CTR			(SECURITY_BASE + 0x0C)
#define SECURITY_CONV_S1_CTR			(SECURITY_BASE + 0x10)
#define SECURITY_SEC_LPC_CTRL			(SECURITY_BASE + 0x14)
#define SECURITY_SEC_INTRAW 			(SECURITY_BASE + 0x18)
#define SECURITY_SEC_INTE			(SECURITY_BASE + 0x1C)
#define SECURITY_SEC_INTS			(SECURITY_BASE + 0x20)
#define SECURITY_DBG_ACC			(SECURITY_BASE + 0x24)
#define SECURITY_RAM_REP_STATE			(SECURITY_BASE + 0x28)
#define SECURITY_APPWR_PROTECT			(SECURITY_BASE + 0x2C)
#define SECURITY_KEY4_0 			(SECURITY_BASE + 0x70)
#define SECURITY_KEY4_1 			(SECURITY_BASE + 0x74)
#define SECURITY_KEY4_2 			(SECURITY_BASE + 0x78)
#define SECURITY_KEY4_3 			(SECURITY_BASE + 0x7C)
#define SECURITY_CHIP_ID			(SECURITY_BASE + 0x80)
#define SECURITY_KEY0_0 			(SECURITY_BASE + 0x90)
#define SECURITY_KEY0_1 			(SECURITY_BASE + 0x94)
#define SECURITY_KEY0_2 			(SECURITY_BASE + 0x98)
#define SECURITY_KEY0_3 			(SECURITY_BASE + 0x9C)
#define SECURITY_KEY1_0 			(SECURITY_BASE + 0xA0)
#define SECURITY_KEY1_1 			(SECURITY_BASE + 0xA4)
#define SECURITY_KEY1_2 			(SECURITY_BASE + 0xA8)
#define SECURITY_KEY1_3 			(SECURITY_BASE + 0xAC)
#define SECURITY_KEY2_0 			(SECURITY_BASE + 0xB0)
#define SECURITY_KEY2_1 			(SECURITY_BASE + 0xB4)
#define SECURITY_KEY2_2 			(SECURITY_BASE + 0xB8)
#define SECURITY_KEY2_3 			(SECURITY_BASE + 0xBC)
#define SECURITY_KEY3_0 			(SECURITY_BASE + 0xC0)
#define SECURITY_KEY3_1 			(SECURITY_BASE + 0xC4)
#define SECURITY_KEY3_2 			(SECURITY_BASE + 0xC8)
#define SECURITY_KEY3_3 			(SECURITY_BASE + 0xCC)
#define SECURITY_SEC_FF 			(SECURITY_BASE + 0xD0)
#define SECURITY_ECC_CTRL			(SECURITY_BASE + 0xD4)
#define SECURITY_ECC_RAW			(SECURITY_BASE + 0xD8)
#define SECURITY_ECC_CAL			(SECURITY_BASE + 0xDC)
#define SECURITY_ECC_RES			(SECURITY_BASE + 0xE0)
#define SECURITY_RAM_ECC_RAW			(SECURITY_BASE + 0xE4)
#define SECURITY_RAM_ECC_CAL			(SECURITY_BASE + 0xE8)
#define SECURITY_RAM_ECC_RES			(SECURITY_BASE + 0xEC)
#define SECURITY_SHRAM0_RAM0_REP		(SECURITY_BASE + 0x100)
#define SECURITY_SHRAM0_RAM1_REP		(SECURITY_BASE + 0x104)
#define SECURITY_SHRAM0_RAM2_REP		(SECURITY_BASE + 0x108)
#define SECURITY_SEC_RAM0_REP			(SECURITY_BASE + 0x10C)
#define SECURITY_SEC_RAM1_REP			(SECURITY_BASE + 0x110)
#define SECURITY_SEC_RAM2_REP			(SECURITY_BASE + 0x114)
#define SECURITY_SEC_RAM3_REP			(SECURITY_BASE + 0x118)
#define SECURITY_M0_RAM0_REP			(SECURITY_BASE + 0x11C)
#define SECURITY_M0_RAM1_REP			(SECURITY_BASE + 0x120)
#define SECURITY_M0_RAM2_REP			(SECURITY_BASE + 0x124)
#define SECURITY_M0_RAM3_REP			(SECURITY_BASE + 0x128)
#define SECURITY_HDMI_KEY			(SECURITY_BASE + 0x200)

/* SECURITY_SEC_CF. */
#define SECURITY_SEC_CF_SEC1_SEL_1		7
#define SECURITY_SEC_CF_SEC1_SEL_0		6
#define SECURITY_SEC_CF_SEC0_SEL_1		5
#define SECURITY_SEC_CF_SEC0_SEL_0		4
#define SECURITY_SEC_CF_TPZ_LOCK		3
#define SECURITY_SEC_CF_SEC_ST			2
#define SECURITY_SEC_CF_SEC_SA			1
#define SECURITY_SEC_CF_SEC_SR			0

/* SECURITY_EFUSE_CTRL. */
#define SECURITY_SPECIAL_ECC_CORR_MASK		2
#define SECURITY_EFUSE_UPDATE			1
#define SECURITY_EFUSE_LOAD_EN			0

/* SECURITY_SEC_LPC_CTRL. */
#define SECURITY_AHB_IDLE_TIME			8
#define SECURITY_EFUSE_IDLE_TIME		4
#define SECURITY_EFUSE_LPC_EN			1
#define SECURITY_AHB_LPC_EN			0

/* SECURITY_SEC_INTE. */
#define SECURITY_SEC_SEC1_POP_INTR		8
#define SECURITY_SEC_SEC1_PUSH_INTR		7
#define SECURITY_SEC_SEC0_POP_INTR		6
#define SECURITY_SEC_SEC0_PUSH_INTR		5
#define SECURITY_SEC_CONV_S1_INTR		4
#define SECURITY_SEC_SECS_INTR			3
#define SECURITY_SEC_CONV_S0_INTR		2
#define SECURITY_SEC_NON_SECS_INTR		1
#define SECURITY_SEC_EFUSE_LOAD_INTR		0	

/* SECURITY_DBG_ACC */
#define SECURITY_DBG_ACC_A9_L2C_SPIDEN		20
#define SECURITY_DBG_ACC_CS_SPNIDEN		19
#define SECURITY_DBG_ACC_CS_SPIDEN		18
#define SECURITY_DBG_ACC_CS_NIDEN		17
#define SECURITY_DBG_ACC_CS_DBGEN		16
#define SECURITY_DBG_ACC_A9_SPNIDEN		14
#define SECURITY_DBG_ACC_A9_SPIDEN		12
#define SECURITY_DBG_ACC_A9_NIDEN		10
#define SECURITY_DBG_ACC_A9_DBGEN		8
#define SECURITY_DBG_ACC_A9_CP15SDIS		1
#define SECURITY_DBG_ACC_A9_CFGSDIS		0

/* SECURITY_SEC_FF. */
#define SECURITY_SEC_FF_CM			10
#define SECURITY_SEC_FF_FL			8
#define SECURITY_SEC_FF_SSD			5
#define SECURITY_SEC_FF_DA9			4
#define SECURITY_SEC_FF_SMC			2
#define SECURITY_SEC_FF_ST			1
#define SECURITY_SEC_FF_SE			0

/* SECURITY_ECC_CTRL. */
#define SECURITY_RAM_ECC_NUM1			16
#define SECURITY_ECC_NUM1			8
#define SECURITY_RAM_ECC_CORR_SUCC		3
#define SECURITY_RAM_ECC_CHECK_SUCC		2
#define SECURITY_ECC_CORR_SUCC			1
#define SECURITY_ECC_CHECK_SUCC			0

/* SECURITY_XXX_RAMX_REP. */
#define SECURITY_RAM_REP_CRE2			13
#define SECURITY_RAM_REP_FCA2			8
#define SECURITY_RAM_REP_CRE1			5
#define SECURITY_RAM_REP_FCA1			0

#endif /* __ASM_ARCH_REGS_SECURITY_H */
