#ifndef __ASM_ARCH_REGS_TRACKBALL_H
#define __ASM_ARCH_REGS_TRACKBALL_H

#define TRACKBALL_CTL				(0x00)	
#define TRACKBALL_SEN				(0x04)	
#define TRACKBALL_PUSH_SET			(0x08)	
#define TRACKBALL_PUSH_TIME1			(0x0c)	
#define TRACKBALL_PUSH_TIME2			(0x10)	
#define TRACKBALL_MVALUE_SET			(0x14)	
#define TRACKBALL_INTR_EN			(0x20)	
#define TRACKBALL_INTR_ST			(0x24)	
#define TRACKBALL_INTR_RAW			(0x28)	
#define TRACKBALL_EDGE_INTR_EN			(0x30)	
#define TRACKBALL_EDGE_INTR_ST			(0x34)	
#define TRACKBALL_EDGE_INTR_RAW			(0x38)	
#define TRACKBALL_DIRECTION			(0x40)
#define TRACKBALL_PUSH_CNT			(0x44)	
#define TRACKBALL_UP_DOWN_CNT			(0x48)	
#define TRACKBALL_LEFT_RIGHT_CNT		(0x4c)	

/* TRACKBALL_PUSH_SET. */
#define TRACKBALL_PUSH_LONG_EN			2
#define TRACKBALL_PUSH_REPEAT_EN		1
#define TRACKBALL_PUSH_VALID_SET		0

/* TRACKBALL_PUSH_TIME1. */
#define TRACKBALL_PUSH_SHORT			16
#define TRACKBALL_PUSH_DEBOUNCE			0

/* TRACKBALL_PUSH_TIME2. */
#define TRACKBALL_PUSH_LONG			16
#define TRACKBALL_PUSH_REPEAT			0

/* TRACKBALL_MVALUE_SET. */
#define TRACKBALL_MVALUE_SET_CNT_MIN		16
#define TRACKBALL_MVALUE_SET_CNT_MAX		0

/* TRACKBALL_INTR_EN. */
#define TRACKBALL_PUSH_RELEASE_INTR		7
#define TRACKBALL_PUSH_REPEAT_INTR		6
#define TRACKBALL_PUSH_LONG_INTR		5
#define TRACKBALL_PUSH_SHORT_INTR		4
#define TRACKBALL_RIGHT_INTR			3
#define TRACKBALL_LEFT_INTR			2
#define TRACKBALL_DOWN_INTR			1
#define TRACKBALL_UP_INTR			0

/* TRACKBALL EDGE INTR. */
#define TRACKBALL_PUSH_EDGE_INTR		4
#define TRACKBALL_RIGHT_EDGE_INTR		3
#define TRACKBALL_LEFT_EDGE_INTR		2
#define TRACKBALL_DOWN_EDGE_INTR		1
#define TRACKBALL_UP_EDGE_INTR			0

/* TRACKBALL_DIRECTION. */
#define TRACKBALL_DIRECTION_PUSH		4
#define TRACKBALL_DIRECTION_RIGHT		3
#define TRACKBALL_DIRECTION_LEFT		2
#define TRACKBALL_DIRECTION_DOWN		1
#define TRACKBALL_DIRECTION_UP			0

/* TRACKBALL_PUSH_CNT. */
#define TRACKBALL_LONG_CNT			16
#define TRACKBALL_SHORT_CNT			0

/* TRACKBALL_UP_DOWN_CNT. */
#define TRACKBALL_DOWN_CNT			16
#define TRACKBALL_UP_CNT			0

/* TRACKBALL_LEFT_RIGHT_CNT. */
#define TRACKBALL_LEFT_CNT			16
#define TRACKBALL_RIGHT_CNT			0

#endif	/* __ASM_ARCH_REGS_TRACKBALL_H */
