#ifndef __ASM_ARCH_REGS_HDMI_H
#define __ASM_ARCH_REGS_HDMI_H

#define HDMI_DESIGN_ID					(0x00)
#define HDMI_REVISION_ID				(0x01)
#define HDMI_PRODUCT_ID0				(0x02)
#define HDMI_PRODUCT_ID1				(0x03)
#define HDMI_CONFIG0_ID 				(0x04)
#define HDMI_CONFIG1_ID 				(0x05)
#define HDMI_CONFIG2_ID 				(0x06)
#define HDMI_CONFIG3_ID 				(0x07)
#define HDMI_IH_FC_STAT0				(0x100)
#define HDMI_TX_INVID0					(0x200)
#define HDMI_VP_STATUS					(0x800)
#define HDMI_FC_INVIDCONF				(0x1000)
#define HDMI_PHY_CONF0					(0x3000)
#define HDMI_PHY_I2CM_SLAVE_ADDR			(0x3020)
#define HDMI_AUD_CONF0					(0x3100)
#define HDMI_GP_CONF0					(0x3500)
#define HDMI_AHB_DMA_CONF0				(0x3600)
#define HDMI_MC_CLKDIS					(0x4001)
#define HDMI_CSC_CFG					(0x4001)
#define HDMI_A_HDCPCFG0 				(0x5000)
#define HDMI_HDCPREG_BKSV0				(0x7800)
#define HDMI_HDCPREG_ANCONF 				(0x7805)
#define HDMI_CEC_CTRL					(0x7D00)
#define HDMI_I2CM_SLAVE 				(0x7E00)
#define HDMI_POINTER_ADDR				(0x7F00)

/* HDMI_CONFIG0_ID. */
#define HDMI_CONFIG0_ID_PREPEN				7
#define HDMI_CONFIG0_ID_AUDHBR				6
#define HDMI_CONFIG0_ID_AUDSPDIF			5
#define HDMI_CONFIG0_ID_AUDI2S				4
#define HDMI_CONFIG0_ID_HSMI14				3
#define HDMI_CONFIG0_ID_CSC 				2
#define HDMI_CONFIG0_ID_CEC 				1
#define HDMI_CONFIG0_ID_HDCP				0

/* HDMI_CONFIG1_ID. */
#define HDMI_CONFIG1_ID_CONFSFRDIR			4
#define HDMI_CONFIG1_ID_CONFI2C				3
#define HDMI_CONFIG1_ID_CONFOCP				2
#define HDMI_CONFIG1_ID_CONFAPB				1
#define HDMI_CONFIG1_ID_CONFAHB				0

/* HDMI_IH_FC_STAT0. */
#define HDMI_IH_FC_STAT0_AUDIO				7
#define HDMI_IH_FC_STAT0_ACP				6
#define HDMI_IH_FC_STAT0_HBR				5
#define HDMI_IH_FC_STAT0_DST				4
#define HDMI_IH_FC_STAT0_OBA				3
#define HDMI_IH_FC_STAT0_AUDS				2
#define HDMI_IH_FC_STAT0_ACR				1
#define HDMI_IH_FC_STAT0_NULL				0

/* HDMI_TX_INVID0. */
#define HDMI_TX_INVID0_INTERNAL_DE_GENERATION		7
#define HDMI_TX_INVID0_VIDEO_MAPPING			0

/* HDMI_FC_INVIDCONF. */
#define HDMI_FC_INVIDCONF_HDCP_KEEPOUT			7
#define HDMI_FC_INVIDCONF_VSYNC_IN_POLARITY		6
#define HDMI_FC_INVIDCONF_HSYNC_IN_POLARITY		5
#define HDMI_FC_INVIDCONF_DE_IN_POLARITY		4
#define HDMI_FC_INVIDCONF_DVI_MODEZ			3
#define HDMI_FC_INVIDCONF_R_V_BLANK_IN_OSC		1
#define HDMI_FC_INVIDCONF_IN_I_P			0

/* HDMI_PHY_CONF0. */
#define HDMI_PHY_CONF0_ENTMDS				6
#define HDMI_PHY_CONF0_SPARECTRL			5
#define HDMI_PHY_CONF0_GEN2_PDDQ			4
#define HDMI_PHY_CONF0_GEN2_TXPWRON			3
#define HDMI_PHY_CONF0_GEN2_ENHPDRXSENSE		2
#define HDMI_PHY_CONF0_SELDATAENPOL			1
#define HDMI_PHY_CONF0_SELDIPIF				0

/* HDMI_AUD_CONF0. */
#define HDMI_AUD_CONF0_SW_AUDIO_FIFO_RST		7
#define HDMI_AUD_CONF0_I2S_SELECT			5
#define HDMI_AUD_CONF0_I2S_IN_EN			0

/* HDMI_GP_CONF0. */
#define HDMI_GP_CONF0_SW_AUDIO_FIFO_RST			0

/* HDMI_AHB_DMA_CONF0. */
#define HDMI_AHB_DMA_CONF0_SW_FIFO_RST			7
#define HDMI_AHB_DMA_CONF0_HBR				4
#define HDMI_AHB_DMA_CONF0_ENABLE_HLOCK			3
#define HDMI_AHB_DMA_CONF0_INCR_TYPE			1
#define HDMI_AHB_DMA_CONF0_BURST_MODE			0

/* HDMI_MC_CLKDIS. */
#define HDMI_MC_CLKDIS_HDCPCLK_DISABLE			6
#define HDMI_MC_CLKDIS_CESCLK_DISABLE			5
#define HDMI_MC_CLKDIS_CSCCLK_DISABLE			4
#define HDMI_MC_CLKDIS_AUDCLK_DISABLE			3
#define HDMI_MC_CLKDIS_PREPCLK_DISABLE			2
#define HDMI_MC_CLKDIS_TMDS_DISABLE			1
#define HDMI_MC_CLKDIS_PIXECLK_DISABLE			0

/* HDMI_CSC_CFG. */
#define HDMI_CSC_CFG_INTMODE				4
#define HDMI_CSC_CFG_DECMODE				0

/* HDMI_A_HDCPCFG0. */
#define HDMI_A_HDCPCFG0_ELVENA				7
#define HDMI_A_HDCPCFG0_I2CFASTMODE			6
#define HDMI_A_HDCPCFG0_BYPENCRYPTION			5
#define HDMI_A_HDCPCFG0_SYNCRICHECK			4
#define HDMI_A_HDCPCFG0_AVMUTE				3
#define HDMI_A_HDCPCFG0_RXDETECT			2
#define HDMI_A_HDCPCFG0_EN11FETURE			1
#define HDMI_A_HDCPCFG0_HDMIDVI				0

/* HDMI_CEC_CTRL. */
#define HDMI_CEC_CTRL_STANDBY				4
#define HDMI_CEC_CTRL_BC_NACK				3
#define HDMI_CEC_CTRL_FRAME_TYP				1

/* HDMI_POINTER_ADDR. */
#define HDMI_POINTER_ADDR_EN_BASE_POINTER_ADDR		7
#define HDMI_POINTER_ADDR_BASE_POINTER_BASE_ADDR	0

#endif /* __ASM_ARCH_REGS_HDMI_H. */
