#ifndef __ASM_ARCH_REGS_MFP_H
#define __ASM_ARCH_REGS_MFP_H

#define MUX_PIN_MUX0				(MUX_PIN_BASE + 0x00)
#define MUX_PIN_MUX1				(MUX_PIN_BASE + 0x04)
#define MUX_PIN_MUX2				(MUX_PIN_BASE + 0x08)
#define MUX_PIN_MUX3				(MUX_PIN_BASE + 0x0C)
#define MUX_PIN_MUX4				(MUX_PIN_BASE + 0x10)
#define MUX_PIN_MUX5				(MUX_PIN_BASE + 0x14)
#define MUX_PIN_MUX6				(MUX_PIN_BASE + 0x18)
#define MUX_PIN_MUX7				(MUX_PIN_BASE + 0x1C)
#define MUX_PIN_MUX8				(MUX_PIN_BASE + 0x20)
#define MUX_PIN_MUX9				(MUX_PIN_BASE + 0x24)
#define MUX_PIN_MUX10				(MUX_PIN_BASE + 0x28)
#define MUX_PIN_MUX11				(MUX_PIN_BASE + 0x2C)
#define MUX_PIN_MUX12				(MUX_PIN_BASE + 0x30)
#define MUX_PIN_MUX13				(MUX_PIN_BASE + 0x34)
#define MUX_PIN_MUX14				(MUX_PIN_BASE + 0x38)
#define MUX_PIN_MUX15				(MUX_PIN_BASE + 0x3c)
#define MUX_PIN_TST_PIN_CTRL0			(MUX_PIN_BASE + 0x40)
#define MUX_PIN_TST_PIN_CTRL1			(MUX_PIN_BASE + 0x44)
#define MUX_PIN_PULL_EN0			(MUX_PIN_BASE + 0x70)
#define MUX_PIN_PULL_EN1			(MUX_PIN_BASE + 0x74)
#define MUX_PIN_PULL_EN2			(MUX_PIN_BASE + 0x78)
#define MUX_PIN_PULL_EN3			(MUX_PIN_BASE + 0x7C)
#define MUX_PIN_PULL_EN4			(MUX_PIN_BASE + 0x80)
#define MUX_PIN_PULL_EN5			(MUX_PIN_BASE + 0x84)
#define MUX_PIN_PULL_EN6			(MUX_PIN_BASE + 0x88)
#define MUX_PIN_PULL_EN7			(MUX_PIN_BASE + 0x8C)
#define MUX_PIN_SDMMC0_PAD_CTRL 		(MUX_PIN_BASE + 0x90)
#define MUX_PIN_SDMMC1_PAD_CTRL 		(MUX_PIN_BASE + 0x94)
#define MUX_PIN_SDMMC2_PAD_CTRL 		(MUX_PIN_BASE + 0x98)
#define MUX_PIN_SDMMC3_PAD_CTRL 		(MUX_PIN_BASE + 0x9C)
#define MUX_PIN_SEC_PORT			(MUX_PIN_BASE + 0x100)

/* MUX_PIN_SEC_POR.T */
#define MUX_PIN_SEC_SMC_VAL_1			3
#define MUX_PIN_SEC_SW_VAL_1			2
#define MUX_PIN_SEC_SMC_VAL_0			1
#define MUX_PIN_SEC_SW_VAL_0			0

#endif /* __ASM_ARCH_REGS_MFP_H */
