#
# Makefile for the touchscreen drivers.
#
obj-$(CONFIG_TOUCHSCREEN_FT5X06)	+= ft5x06_ts.o ft5x06_ex_fun.o focaltech_ctl.o
obj-$(CONFIG_TOUCHSCREEN_EDT_FT5X06)	+= edt-ft5x06.o
obj-$(CONFIG_TOUCHSCREEN_ZET62XX)	+= zet62xx.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX)                += gt9xx.o gt9xx_update.o goodix_tool.o
obj-$(CONFIG_TOUCHSCREEN_ICN8528F)	+= icn85xx.o flash.o
obj-$(CONFIG_TOUCHSCREEN_GT9XX)      += gt9xx.o gt9xx_update.o goodix_tool.o
obj-$(CONFIG_TOUCHSCREEN_S2716)		+=  synaptics_dsx_core.o synaptics_dsx_i2c.o synaptics_dsx_rmi_dev.o synaptics_dsx_fw_update.o
obj-$(CONFIG_TOUCHSCREEN_BF686x)	+= bf686x_ts.o
obj-$(CONFIG_TOUCHSCREEN_BF67xx)	+= bf67xx_ts.o
obj-$(CONFIG_TOUCHSCREEN_BF675x)	+= bf675x_ts.o byd_cts15_ts_obfus.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS200)	+= mms200_ts.o mms200_fw_update.o mms_ts_test.o
obj-$(CONFIG_TOUCHSCREEN_MELFAS_MMS438)	+= melfas_mms400.o melfas_mms400_mod.o melfas_mms400_test.o melfas_mms400_cmd.o melfas_mms438_fw_update.o

