# board product config

# LC1810 board
obj-$(CONFIG_COMIP_PROJECT_YL8150S) += board-yl8150s.o

# LC1813 board
obj-$(CONFIG_COMIP_PROJECT_UST802) += board-ust802.o
obj-$(CONFIG_COMIP_PROJECT_LC1813) += board-lc1813.o
obj-$(CONFIG_COMIP_PROJECT_TL920) += board-tl920.o