#ifndef __ASM_ARCH_REGS_DSI_ISP_CTL_H
#define __ASM_ARCH_REGS_DSI_ISP_CTL_H_

#define DSI_ISP_CTL_LP_MODE_CTRL	(DSI_ISP_CTL + 0xA0)

#define CTL_CPHY0_ERROR_STAT		(DSI_ISP_CTL + 0x100)
#define CTL_CPHY0_STAT				(DSI_ISP_CTL + 0x104)
#define CTL_CPHY0_RSTZ				(DSI_ISP_CTL + 0xF4)
#define CTL_CPHY0_CTRL0 			(DSI_ISP_CTL + 0xF8)
#define CTL_CPHY0_CTRL1 			(DSI_ISP_CTL + 0xFC)
#define CTL_CPHY0_MODE				(DSI_ISP_CTL + 0xF0)

#define CTL_CPHY1_ERROR_STAT		(DSI_ISP_CTL + 0x118)
#define CTL_CPHY1_STAT				(DSI_ISP_CTL + 0x11C)
#define CTL_CPHY1_RSTZ				(DSI_ISP_CTL + 0x10C)
#define CTL_CPHY1_CTRL0 			(DSI_ISP_CTL + 0x110)
#define CTL_CPHY1_CTRL1 			(DSI_ISP_CTL + 0x114)
#define CTL_CPHY1_MODE				(DSI_ISP_CTL + 0x108)

#endif

