#ifndef __ASM_ARCH_REGS_CTL_H
#define __ASM_ARCH_REGS_CTL_H

#define CTL_AP_HA7_CORE0_WBOOT_ADDR		(CTL_BASE + 0x00)
#define CTL_AP_HA7_CORE1_CBOOT_ADDR		(CTL_BASE + 0x04)
#define CTL_AP_HA7_CORE1_WBOOT_ADDR		(CTL_BASE + 0x08)
#define CTL_AP_HA7_CORE2_CBOOT_ADDR		(CTL_BASE + 0x0c)
#define CTL_AP_HA7_CORE2_WBOOT_ADDR		(CTL_BASE + 0x10)
#define CTL_AP_HA7_CORE3_CBOOT_ADDR		(CTL_BASE + 0x14)
#define CTL_AP_HA7_CORE3_WBOOT_ADDR		(CTL_BASE + 0x18)
#define CTL_AP_SA7_CORE0_WBOOT_ADDR		(CTL_BASE + 0x1c)
#define CTL_AP_SA7_CTRL			(CTL_BASE + 0xe4)
#define CTL_AP_HA7_CTRL			(CTL_BASE + 0xe8)
#define CTL_SSI0_PROTOCOL_CTRL			(CTL_BASE + 0xb0)
#define CTL_SSI1_PROTOCOL_CTRL			(CTL_BASE + 0xb4)
#define CTL_SSI2_PROTOCOL_CTRL			(CTL_BASE + 0xb8)
#define CTL_TIMER1_PAUSE_CTRL			(CTL_BASE + 0xbc)
#define CTL_TIMER2_PAUSE_CTRL			(CTL_BASE + 0xc0)
#define CTL_TIMER3_PAUSE_CTRL			(CTL_BASE + 0xc4)
#define CTL_TIMER4_PAUSE_CTRL			(CTL_BASE + 0xc8)
#define CTL_TIMER5_PAUSE_CTRL			(CTL_BASE + 0xcc)
#define CTL_TIMER6_PAUSE_CTRL			(CTL_BASE + 0xd0)
#define CTL_TIMER7_PAUSE_CTRL			(CTL_BASE + 0xd4)
#define CTL_TIMER8_PAUSE_CTRL			(CTL_BASE + 0xd8)
#define CTL_GPU_CTRL				(CTL_BASE + 0xec)
#define CTL_ON2_RAM_CLKGATE_CTRL		(CTL_BASE + 0x120)
#define CTL_BUS_CFG				(CTL_BASE + 0x124)

#define CTL_USB_OTG_PHY_CFG0			(CTL_BASE + 0x168)	/* L1813S */
#define CTL_USB_OTG_PHY_CFG1			(CTL_BASE + 0x16C)	/* L1813S */

/* CTL_USB_OTG_PHY_STA */
#define	CTL_USB_OTG_PHY_STA_LINESTATE			2

/* CTL_USB_OTG_PHY_CFG0 */
#define CTL_USB_OTG_PHY_CFG0_TXRESTUNE0			28
#define CTL_USB_OTG_PHY_CFG0_TXRISETUNE0		20
#define CTL_USB_OTG_PHY_CFG0_TXPREEMPPULSETUNE0		18
#define CTL_USB_OTG_PHY_CFG0_TXPREEMPAMPTUNE0		16


#endif /* __ASM_ARCH_REGS_CTL_H */
