#ifndef __ASM_ARCH_REGS_CTL_USB_H
#define __ASM_ARCH_REGS_CTL_USB_H


#define CTL_POR_OTGPHY_CTRL				(USB_CTL + 0x20)
#define CTL_PORTRESET_OTGPHY_CTRL		(USB_CTL + 0x24)
#define CTL_OTGPHY_SUSPENDM_CTRL		(USB_CTL + 0x28)
#define CTL_OTGPHY_CTRL					(USB_CTL + 0x2c)
#define CTL_OTGPHY_TEST_CTRL0			(USB_CTL + 0x30)
#define CTL_OTGPHY_TEST_CTRL1			(USB_CTL + 0x34)
#define CTL_OTGPHY_TEST_CTRL2			(USB_CTL + 0x38)
#define CTL_OTGPHY_CHARGE_CTRL			(USB_CTL + 0x3c)
#define CTL_OTGPHY_PARAM_OVERRIDE		(USB_CTL + 0x40)
#define CTL_OTG_CORE_CTRL				(USB_CTL + 0x44)
#define CTL_OTG_PHY_STATUS				(USB_CTL + 0x48)
#define CTL_OTGPHY_INTR_RAW				(USB_CTL + 0x4c)
#define CTL_OTGPHY_INTR_STA				(USB_CTL + 0x50)
#define CTL_OTGPHY_INTR_EN				(USB_CTL + 0x54)
#define CTL_HSIC_PHY_POR_CTRL			(USB_CTL + 0x60)
#define CTL_HSIC_PHY_PORTRESET_CTRL		(USB_CTL + 0x64)
#define CTL_HSIC_PHY_SUSPEND_CTRL		(USB_CTL + 0x68)
#define CTL_HSIC_SCALEDOWN_MODE_CTRL	(USB_CTL + 0x6c)
#define CTL_HSIC_PHY_STATUS				(USB_CTL + 0x70)
#define	CTL_HSICPHY_CTRL				(USB_CTL + 0x74)
#define CTL_HSICPHY_TEST_CTRL0			(USB_CTL + 0x78)
#define CTL_HSICPHY_TEST_CTRL1			(USB_CTL + 0x7c)
#define CTL_HSICPHY_TEST_CTRL2			(USB_CTL + 0x80)
#define CTL_HSICPHY_PARAM_OVERRIDE		(USB_CTL + 0x84)
#define CTL_HSICPHY_INTR_RAW			(USB_CTL + 0x88)
#define CTL_HSICPHY_INTR_STA			(USB_CTL + 0x8c)
#define CTL_HSICPHY_INTR_EN				(USB_CTL + 0x90)
#define CTL_OTG_CORE_RST_CTRL			(USB_CTL + 0x94)
#define CTL_HSIC_CORE_RST_CTRL			(USB_CTL + 0x98)
#define CTL_OTGPHY_SUSPEND_STATUS		(USB_CTL + 0xdc)
#define CTL_HSICPHY_SUSPEND_STATUS		(USB_CTL + 0xe0)
#define CTL_LP_MODE_CTRL				(USB_CTL + 0xa0)

/* CTL_OTG_PHY_STATUS */
#define	CTL_OTG_UTMI_LINESTATE						0

/* CTL_POR_OTGPHY_CTRL */
#define CTL_POR_OTGPHY_CTRL_POR_OTGPHY				0

/* CTL_OTGPHY_CHARGE_CTRL */
#define CTL_OTGPHY_CHARGE_CTRL_VDATDETENB0_OTGPHY	4
#define CTL_OTGPHY_CHARGE_CTRL_VDATSRCENB0_OTGPHY	3
#define CTL_OTGPHY_CHARGE_CTRL_DCDENB0_OTGPHY		2
#define CTL_OTGPHY_CHARGE_CTRL_ACAENB0_OTGPHY		1
#define CTL_OTGPHY_CHARGE_CTRL_CHRGSEL0_OTGPHY		0

#endif /* __ASM_ARCH_REGS_CTL_USB_H */
