#ifndef __ASM_ARCH_REGS_DDR_PWR_H
#define __ASM_ARCH_REGS_DDR_PWR_H

#define DDR_PWR_PLLCFG					(DDR_PWR_BASE + 0x00)
#define DDR_PWR_PLLCTL					(DDR_PWR_BASE + 0x04)
#define DDR_PWR_PLLTIME					(DDR_PWR_BASE + 0x08)
#define DDR_PWR_DDRCLKDIV_NOW				(DDR_PWR_BASE + 0x0c)
#define DDR_PWR_COMPRECLKDIV				(DDR_PWR_BASE + 0x10)
#define DDR_PWR_I2SCLKDIV				(DDR_PWR_BASE + 0x14)
#define DDR_PWR_CORESIGHTCLKDIV				(DDR_PWR_BASE + 0x18)
#define DDR_PWR_I2CCLKDIV				(DDR_PWR_BASE + 0x1c)
#define DDR_PWR_PCMCLKDIV				(DDR_PWR_BASE + 0x20)
#define DDR_PWR_COMUARTCLKDIV				(DDR_PWR_BASE + 0x24)
#define DDR_PWR_CLKOUT0DIV				(DDR_PWR_BASE + 0x28)
#define DDR_PWR_CLKOUT1DIV				(DDR_PWR_BASE + 0x2c)
#define DDR_PWR_BUSCLKDIV				(DDR_PWR_BASE + 0x30)
#define DDR_PWR_COMAPBCLKDIV				(DDR_PWR_BASE + 0x34)
#define DDR_PWR_PCLKEN					(DDR_PWR_BASE + 0x3c)
#define DDR_PWR_CLKEN0					(DDR_PWR_BASE + 0x40)
#define DDR_PWR_CLKEN1					(DDR_PWR_BASE + 0x44)
#define DDR_PWR_UARTCLKCTL				(DDR_PWR_BASE + 0x48)
#define DDR_PWR_METERCLKCTL				(DDR_PWR_BASE + 0x4c)
#define DDR_PWR_TSCLKCTL				(DDR_PWR_BASE + 0x50)
#define DDR_PWR_LPCLKCTL				(DDR_PWR_BASE + 0x54)
#define DDR_PWR_A7GTMCLKCTL				(DDR_PWR_BASE + 0x58)
#define DDR_PWR_CMDFIFOCTL				(DDR_PWR_BASE + 0x5c)
#define DDR_PWR_CMDFIFOSTATUS				(DDR_PWR_BASE + 0x60)
#define DDR_PWR_CMDFIFOWR				(DDR_PWR_BASE + 0x64)
#define DDR_PWR_DDRCLKDIVL				(DDR_PWR_BASE + 0x68)
#define DDR_PWR_DDRCLKDIVH				(DDR_PWR_BASE + 0x6c)
#define DDR_PWR_AP_DDR_FREQ				(DDR_PWR_BASE + 0x70)
#define DDR_PWR_CP_DDR_FREQ				(DDR_PWR_BASE + 0x74)
#define DDR_PWR_MEMCTLLPEXTCTL				(DDR_PWR_BASE + 0x78)
#define DDR_PWR_MEMCTLDATAAXICTL			(DDR_PWR_BASE + 0x7c)
#define DDR_PWR_TOP_RAM1_PD_CTL				(DDR_PWR_BASE + 0x94)
#define DDR_PWR_TOP_RAM1_PD_CNT1			(DDR_PWR_BASE + 0x98)
#define DDR_PWR_TOP_RAM1_PD_CNT2			(DDR_PWR_BASE + 0x9c)
#define DDR_PWR_TOP_RAM1_PD_CNT3			(DDR_PWR_BASE + 0xa0)
#define DDR_PWR_TL420_PD_CTL				(DDR_PWR_BASE + 0xa4)
#define DDR_PWR_TL420_PD_CNT1				(DDR_PWR_BASE + 0xa8)
#define DDR_PWR_TL420_PD_CNT2				(DDR_PWR_BASE + 0xac)
#define DDR_PWR_TL420_PD_CNT3				(DDR_PWR_BASE + 0xb0)
#define DDR_PWR_MEMCTL0_PD_CTL				(DDR_PWR_BASE + 0xb4)
#define DDR_PWR_MEMCTL1_PD_CTL				(DDR_PWR_BASE + 0xb8)
#define DDR_PWR_MEMCTL_PD_CNT1				(DDR_PWR_BASE + 0xbc)
#define DDR_PWR_MEMCTL_PD_CNT2				(DDR_PWR_BASE + 0xc0)
#define DDR_PWR_MEMCTL_PD_CNT3				(DDR_PWR_BASE + 0xc4)
#define DDR_PWR_FC_CTL					(DDR_PWR_BASE + 0xc8)
#define DDR_PWR_FC_SHORT_PERIOD				(DDR_PWR_BASE + 0xcc)
#define DDR_PWR_FC_LONG_PERIOD				(DDR_PWR_BASE + 0xd0)
#define DDR_PWR_FC_AWUSER				(DDR_PWR_BASE + 0xd4)
#define DDR_PWR_FC_ARUSR				(DDR_PWR_BASE + 0xd8)
#define DDR_PWR_FC_LONG_TIMESCAL0			(DDR_PWR_BASE + 0xdc)
#define DDR_PWR_FC_LONG_TIMESCAL1			(DDR_PWR_BASE + 0xe0)
#define DDR_PWR_FC_LONG_TIMESCAL2			(DDR_PWR_BASE + 0xe4)
#define DDR_PWR_FC_LONG_TIMESCAL3			(DDR_PWR_BASE + 0xe8)
#define DDR_PWR_FC_LONG_TIMESCAL4			(DDR_PWR_BASE + 0xec)
#define DDR_PWR_FC_LONG_TIMESCAL5			(DDR_PWR_BASE + 0xf0)
#define DDR_PWR_FC_LONG_TIMESCAL6			(DDR_PWR_BASE + 0xf4)
#define DDR_PWR_FC_LONG_TIMESCAL7			(DDR_PWR_BASE + 0xf8)
#define DDR_PWR_FC_LONG_BYTESCAL0			(DDR_PWR_BASE + 0xfc)
#define DDR_PWR_FC_LONG_BYTESCAL1			(DDR_PWR_BASE + 0x100)
#define DDR_PWR_FC_LONG_BYTESCAL2			(DDR_PWR_BASE + 0x104)
#define DDR_PWR_FC_LONG_BYTESCAL3			(DDR_PWR_BASE + 0x108)
#define DDR_PWR_FC_LONG_BYTESCAL4			(DDR_PWR_BASE + 0x10c)
#define DDR_PWR_FC_LONG_BYTESCAL5			(DDR_PWR_BASE + 0x110)
#define DDR_PWR_FC_LONG_BYTESCAL6			(DDR_PWR_BASE + 0x114)
#define DDR_PWR_FC_LONG_BYTESCAL7			(DDR_PWR_BASE + 0x11c)
#define DDR_PWR_INTR_MASK_CPA7				(DDR_PWR_BASE + 0x120)
#define DDR_PWR_INTR_MASK_APA7				(DDR_PWR_BASE + 0x124)
#define DDR_PWR_INTR_MASK_XC4210			(DDR_PWR_BASE + 0x128)
#define DDR_PWR_INTR_MASK_TL420				(DDR_PWR_BASE + 0x12c)
#define DDR_PWR_INTR_MASK_X1643				(DDR_PWR_BASE + 0x130)
#define DDR_PWR_INTR_RAW				(DDR_PWR_BASE + 0x134)
#define DDR_PWR_INTR_EN_CPA7				(DDR_PWR_BASE + 0x138)
#define DDR_PWR_INTR_CPA7				(DDR_PWR_BASE + 0x13c)
#define DDR_PWR_INTR_EN_APA7				(DDR_PWR_BASE + 0x140)
#define DDR_PWR_INTR_APA7				(DDR_PWR_BASE + 0x144)
#define DDR_PWR_INTR_EN_XC4210				(DDR_PWR_BASE + 0x148)
#define DDR_PWR_INTR_XC4210				(DDR_PWR_BASE + 0x14c)
#define DDR_PWR_INTR_EN_TL420				(DDR_PWR_BASE + 0x150)
#define DDR_PWR_INTR_TL420				(DDR_PWR_BASE + 0x154)
#define DDR_PWR_INTR_EN_X1643				(DDR_PWR_BASE + 0x158)
#define DDR_PWR_INTR_X1643				(DDR_PWR_BASE + 0x15c)
#define DDR_PWR_AT_CTL					(DDR_PWR_BASE + 0x160)
#define DDR_PWR_AT_C1					(DDR_PWR_BASE + 0x164)
#define DDR_PWR_AT_C2					(DDR_PWR_BASE + 0x168)
#define DDR_PWR_AT_C1_SNAP				(DDR_PWR_BASE + 0x16c)
#define DDR_PWR_AT_C2_SNAP				(DDR_PWR_BASE + 0x170)
#define DDR_PWR_AT_CALIB_CTL				(DDR_PWR_BASE + 0x174)
#define DDR_PWR_AT_CALIB_32KINC				(DDR_PWR_BASE + 0x178)
#define DDR_PWR_AT_CALIB_32KNUM				(DDR_PWR_BASE + 0x17c)
#define DDR_PWR_AT_CALIB_RESULT				(DDR_PWR_BASE + 0x180)
#define DDR_PWR_TOPBUSLPCTL				(DDR_PWR_BASE + 0x184)
#define DDR_PWR_TOPBUSLPCNTNUM				(DDR_PWR_BASE + 0x188)
#define DDR_PWR_TOPBUSLPCNTNUM2				(DDR_PWR_BASE + 0x18c)
#define DDR_PWR_DDRBUSLPCTL				(DDR_PWR_BASE + 0x190)
#define DDR_PWR_DDRBUSLPCNTNUM				(DDR_PWR_BASE + 0x198)
#define DDR_PWR_TOPCTRLBUSLPCTL				(DDR_PWR_BASE + 0x19c)
#define DDR_PWR_TOPCTRLBUSLPCNTNUM			(DDR_PWR_BASE + 0x1a4)
#define DDR_PWR_MEMCTLLPCTL				(DDR_PWR_BASE + 0x1a8)
#define DDR_PWR_TL420LPCTL				(DDR_PWR_BASE + 0x1ac)
#define DDR_PWR_REVLOCK					(DDR_PWR_BASE + 0x1c0)
#define DDR_PWR_TL420BOOTADDRSEL			(DDR_PWR_BASE + 0x1c4)
#define DDR_PWR_TL420_BOOT_ADDR1			(DDR_PWR_BASE + 0x1c8)
#define DDR_PWR_TOPFSMCTL				(DDR_PWR_BASE + 0x1cc)
#define DDR_PWR_DDR_INITIALIZED				(DDR_PWR_BASE + 0x1d0)
#define DDR_PWR_PMU_CTL					(DDR_PWR_BASE + 0x1d4)
#define DDR_PWR_RESET					(DDR_PWR_BASE + 0x1d8)
#define DDR_PWR_NPDRAMCTL				(DDR_PWR_BASE + 0x1dc)
#define DDR_PWR_MEMCTL0EN				(DDR_PWR_BASE + 0x1e0)
#define DDR_PWR_MEMCTL1EN				(DDR_PWR_BASE + 0x1e4)
#define DDR_PWR_MEMCTLIFCTL				(DDR_PWR_BASE + 0x1e8)
#define DDR_PWR_CPCLK26MSEL				(DDR_PWR_BASE + 0x1ec)
#define DDR_PWR_CDBGPWRUPREQMASK			(DDR_PWR_BASE + 0x1f0)
#define DDR_PWR_RESET2					(DDR_PWR_BASE + 0x1f4)
#define DDR_PWR_TL420CTL				(DDR_PWR_BASE + 0x1f8)
#define DDR_PWR_APOSCCTL				(DDR_PWR_BASE + 0x1fc)
#define DDR_PWR_CPOSCCTL				(DDR_PWR_BASE + 0x200)
#define DDR_PWR_CPDBGCTL				(DDR_PWR_BASE + 0x204)
#define DDR_PWR_ATSPECIALTIME				(DDR_PWR_BASE + 0x208)
#define DDR_PWR_ATSPECIALTIMEMASK			(DDR_PWR_BASE + 0x20c)
#define DDR_PWR_UARCONNECTSEL				(DDR_PWR_BASE + 0x214)
#define DDR_PWR_A7GTMCTL				(DDR_PWR_BASE + 0x218)
#define DDR_PWR_PLLCFG1					(DDR_PWR_BASE + 0x21c)

/* DDR_PWR_PLLCFG0 */
#define PLL_DSMPD					28
#define PLL_POSTDIV2					24
#define PLL_POSTDIV1					20
#define PLL_FBDIV					8
#define PLL_REFDIV					0

/* DDR_PWR_PLLCFG1 */
#define PLL_LD						31
#define PLL_FRAC					0

/* DDR_PWR_PLLTIME */
#define PLL_STABLE_TIME					8
#define OSC_STABLE_TIME					0

/* DDR_PWR_PCMCLKDIV */
#define COM_PCM_CLK_MUL					16
#define COM_PCM_CLK_DIV					0

/* DDR_PWR_COMUARTCLKDIV */
#define COM_UART_CLK_MUL				16
#define COM_UART_CLK_DIV				0

/* DDR_PWR_CLKOUT0DIV */
#define CLK_OUT0_MUL					16
#define CLK_OUT0_DIV					0

/* DDR_PWR_CLKOUT1DIV */
#define CLK_OUT1_MUL					16
#define CLK_OUT1_DIV					0

/* DDR_PWR_BUSCLKDIV */
#define BUSCLKDIV_BIT_WE				16
#define TOP_BUS_CLK_MUL					8
#define TOP_BUS_CLK_DIV					0

/* DDR_PWR_COMAPBCLKDIV */
#define COMAPBCLKDIV_BIT_WE				16
#define COM_APB_CLK_DIV					0

/* DDR_PWR_PCLKEN */
#define PCLKEN_BIT_WE					16
#define GPIO_PCLK_EN					5
#define COM_PCM_PCLK_EN					4
#define COM_UART_PCLK_EN				3
#define COM_I2C_PCLK_EN					2
#define COM_I2S_PCLK_EN					1
#define MUXPIN_PCLK_EN					0

/* DDR_PWR_CLKEN0 */
#define CLKEN0_BIT_WE					16
#define TOP_RAM1_CLK_EN					13
#define TL420_ICTL_CLK_EN				12
#define TL420_CLK_EN					11
#define CORESIGHT_CLK_EN				10
#define TOP_MAIL_BOX_CLK_EN				9
#define COM_UART_CLK_EN					8
#define GPIO_CLK_EN					7
#define TOP_DMAG_CLK_EN					6
#define TOP_DMAS_CLK_EN					5
#define COM_PCM_CLK_EN					4
#define COM_I2C_CLK_EN					3
#define COM_I2S_CLK_EN					2
#define MEMCTL1_CLK_EN					1
#define MEMCTL0_CLK_EN					0

/* DDR_PWR_CLKEN1 */
#define CLKEN1_BIT_WE					16
#define MEMCTL1_REGAXI_CLK_EN				6
#define MEMCTL0_REGAXI_CLK_EN				5
#define MEMCTL1_PHY_CLK_EN				4
#define MEMCTL0_PHY_CLK_EN				3
#define CLK_OUT1_EN					2
#define CLK_OUT0_EN					1
#define CP_BOOT_RAM_CLK_EN				0

/* DDR_PWR_UARTCLKCTL */
#define COM_UART_LP_REQ_PCLK				2
#define COM_UART_LP_REQ_SCLK				1
#define COM_UART_CLK_OFF_PROTECT			0

/* DDR_PWR_METERCLKCTL */
#define METER_CLK_EN					8
#define METER_CLK_DIV					0

/* DDR_PWR_TSCLKCTL */
#define TS_CLK_EN					8
#define TS_CLK_DIV					0

/* DDR_PWR_LPCLKCTL */
#define LP_CLK_EN					8
#define LP_CLK_DIV					0

/* DDR_PWR_A7GTMCLKCTL */
#define A7_GTM_CLK_EN					20
#define A7_GTM_CLK_DIV1					8
#define A7_GTM_CLK_DIV0					0

/* DDR_PWR_CMDFIFOSTATUS */
#define CMD_FIFO_FULL					1
#define CMD_FIFO_EMPTY					0

/* DDR_PWR_MEMCTLDATAAXICTL */
#define MEMCTL_DATA_AXI_STOPED				1
#define HOLD_MEMCTL_DATA_AXI				0

/* DDR_PWR_TOP_RAM1_PD_CTL */
#define TOP_RAM1_PD_CTL_BIT_WE				16
#define TOP_RAM1_PD_MK					3
#define TOP_RAM1_WK_ACK_MK				2
#define TOP_RAM1_WK_UP					1
#define TOP_RAM1_PD_EN					0

/* DDR_PWR_TL420_PD_CTL */
#define TL420_PD_CTL_BIT_WE				16
#define TL420_PD_MK					3
#define TL420_WK_ACK_MK					2
#define TL420_WK_UP					1
#define TL420_PD_EN					0

/* DDR_PWR_MEMCTL0_PD_CTL */
#define MEMCTL0_PD_CTL_BIT_WE				16
#define MEMCTL0_PD_FSM_STATE				12
#define MEMCTL0_PD_MK					4
#define MEMCTL0_RELEASE_DATA_RETENTION_MK		3
#define MEMCTL0_WK_ACK_MK				2
#define MEMCTL0_WK_UP					1

/* DDR_PWR_MEMCTL1_PD_CTL */
#define MEMCTL1_PD_CTL_BIT_WE				16
#define MEMCTL1_PD_FSM_STATE				12
#define MEMCTL1_PD_MK					4
#define MEMCTL1_RELEASE_DATA_RETENTION_MK		3
#define MEMCTL1_WK_ACK_MK				2
#define MEMCTL1_WK_UP					1

/* DDR_PWR_MEMCTL_PD_CNT1 */
#define MEMCTL_EN1_CNT					16
#define MEMCTL_EN0_CNT					0

/* DDR_PWR_MEMCTL_PD_CNT2 */
#define RELEASE_DATA_RETENTION_CNT			16
#define MEMCTL_WK0_CNT					0

/* DDR_PWR_FC_CTL */
#define FLOW_CAL_FLAG					12
#define HSL_OUTPUT_TRIGTYPE				11
#define WITH_TIMESTAMP					10
#define HSL_OUTPUT_EN					9
#define CAL_EN						8
#define LONG_CAL_EN					0

/* DDR_PWR_FC_AWUSER */
#define AWUSER7						28
#define AWUSER6						24
#define AWUSER5						20
#define AWUSER4						16
#define AWUSER3						12
#define AWUSER2						8
#define AWUSER1						4
#define AWUSER0						0

/* DDR_PWR_FC_ARUSR */
#define ARUSR7						28
#define ARUSR6						24
#define ARUSR5						20
#define ARUSR4						16
#define ARUSR3						12
#define ARUSR2						8
#define ARUSR1						4
#define ARUSR0						0

/* DDR_PWR_INTR_MASK_CPA7 & DDR_PWR_INTR_MASK_APA7 & DDR_PWR_INTR_MASK_XC4210 */
/* DDR_PWR_INTR_EN_TL420 & DDR_PWR_INTR_TL420 */
/* DDR_PWR_INTR_EN_X1643 & DDR_PWR_INTR_X1643 */
#define AT_SPECIAL_TIME_INTR				24
#define AP_WDT4_RESET_INTR				23
#define TOP_FSM_SLEEP02RST_INTR				22
#define LP_EXT_CMD_FAIL_INTR				21
#define MEMCTL1_PU_INTR					20
#define MEMCTL0_PU_INTR					19
#define TL420_PU_INTR					17
#define TOP_RAM1_PU_INTR				16
#define MEMCTL1_PD_INTR					15
#define MEMCTL0_PD_INTR					14
#define TL420_PD_INTR					12
#define TOP_RAM1_PD_INTR				11
#define LPX_EXIT_INTR					10
#define TOP_FSM_WK2RST_INTR				9
#define AP_WDT0_RESET_INTR				8
#define AP_WDT1_RESET_INTR				7
#define AP_WDT2_RESET_INTR				6
#define AP_WDT3_RESET_INTR				5
#define CP_WDT_RESET_INTR				4
#define AT_CALIB_FINISH_INTR				3
#define AT_SNAP_INTR					2
#define PLL_CONFIG_FINISH_INTR				1
#define FLOW_CAL_FINISH_INTR				0

/* DDR_PWR_AT_CTL */
#define AT_SNAP_SF					1
#define AT_SNAP_RST					0

/* DDR_PWR_AT_CALIB_CTL */
#define AT_CALIB_AUTOUPDATE_EN				1
#define AT_CALIB_START					0

/* DDR_PWR_TOPBUSLPCTL */
#define MIDWAY_BACK_ACK_MK				31
#define TL420RAM_TBAXI_LP_EN				15
#define DDRBUS_TBAXI_LP_EN				14
#define TOPCTRLBUS_TBAXI_LP_EN				13
#define TOCP_TBAXI_LP_EN				12
#define TOAP_TBAXI_LP_EN				11
#define APTRACE_TBAXI_LP_EN				10
#define CPTRACE_TBAXI_LP_EN				9
#define TL420AXI1_TBAXI_LP_EN				8
#define TL420AXI0_TBAXI_LP_EN				7
#define TOPDMAG_TBAXI_LP_EN				6
#define TOPDMAS_TBAXI_LP_EN				5
#define APTOP_TBAXI_LP_EN				4
#define CPTOP_TBAXI_LP_EN				3
#define CPBOOTRAM_TBAXI_LP_EN				2
#define TOPRAM1_TBAXI_LP_EN				1
#define MAIN_TBAXI_LP_EN				0

/* DDR_PWR_TOPBUSLPCNTNUM */
#define MAIN_TBAXI_LPCNTNUM				14
#define TL420AXI0_TBAXI_LPCNTNUM			12
#define TOPDMAG_TBAXI_LPCNTNUM				10
#define APTOP_TBAXI_LPCNTNUM				6
#define CPTOP_TBAXI_LPCNTNUM				4
#define CPBOOTRAM_TBAXI_LPCNTNUM			2
#define TOPRAM1_TBAXI_LPCNTNUM				0

/* DDR_PWR_TOPBUSLPCNTNUM2 */
#define TL420RAM_TBAXI_LPCNTNUM				14
#define DDRBUS_TBAXI_LPCNTNUM				12
#define TOPCTRLBUS_TBAXI_LPCNTNUM			10
#define TOCP_TBAXI_LPCNTNUM				8
#define TOAP_TBAXI_LPCNTNUM				6
#define APTRACE_TBAXI_LPCNTNUM				4
#define CPTRACE_TBAXI_LPCNTNUM				2
#define TL420AXI1_TBAXI_LPCNTNUM			0

/* DDR_PWR_DDRBUSLPCTL */
#define AP1_DBAXI_LP_EN					7
#define MAIN_DBAXI_LP_EN				6
#define TOPBUS_DBAXI_LP_EN				5
#define AP0_DBAXI_LP_EN					4
#define CP_DBAXI_LP_EN					3
#define CPA7_DBAXI_LP_EN				2
#define DDR1_DBAXI_LP_EN				1
#define DDR0_DBAXI_LP_EN				0

/* DDR_PWR_DDRBUSLPCNTNUM */
#define AP1_DBAXI_LPCNTNUM				14
#define MAIN_DBAXI_LPCNTNUM				12
#define TOPBUS_DBAXI_LPCNTNUM				10
#define AP0_DBAXI_LPCNTNUM				8
#define CP_DBAXI_LPCNTNUM				6
#define CPA7_DBAXI_LPCNTNUM				4
#define DDR1_DBAXI_LPCNTNUM				2
#define DDR0_DBAXI_LPCNTNUM				0

/* DDR_PWR_TOPCTRLBUSLPCTL */
#define COM_APB_BUS_LP_EN				7
#define MAIN_TCBAXI_LP_EN				6
#define DDR1_TCBAXI_LP_EN				5
#define DDR0_TCBAXI_LP_EN				4
#define TOPMAILBOX_TCBAXI_LP_EN				3
#define TOPDMAS_TCBAXI_LP_EN				2
#define TOPDMAG_TCBAXI_LP_EN				1
#define TL420_ICTL_TCBAXI_LP_EN				0

/* DDR_PWR_TOPCTRLBUSLPCNTNUM */
#define MAIN_TCBAXI_LPCNTNUM				14
#define COM_APB_BUS_LPCNTNUM				12
#define DDR1_TCBAXI_LPCNTNUM				10
#define DDR0_TCBAXI_LPCNTNUM				8
#define TOPMAILBOX_TCBAXI_LPCNTNUM			6
#define TOPDMAS_TCBAXI_LPCNTNUM				4
#define TOPDMAG_TCBAXI_LPCNTNUM				2
#define TL420_ICTL_TCBAXI_LPCNTNUM			0

/* DDR_PWR_MEMCTLLPCTL */
#define MEMCTL_CLK_LP_LIMIT				9
#define MEMCTL1_CLK_LP_EN				8
#define MEMCTL0_CLK_LP_LIMIT				1
#define MEMCTL0_CLK_LP_EN				0

/* DDR_PWR_TOPFSMCTL */
#define TOP_OSC_EN_OR					10
#define RF_OSC_EN_SEL					9
#define TL420_SLEEP_EN					8
#define DDR_RESET_PERIOD				4
#define TOP_FSM_STATE					0

/* DDR_PWR_PMU_CTL */
#define VOL_SW_A7					12
#define VOL_TW_A7					8
#define VOL_SW_GPU					4
#define VOL_TW_GPU					0

/* DDR_PWR_RESET */
#define RESET_BIT_WE					16
#define TL420_SF_RST					15
#define CP_BOOT_RAM_SF_RST				14
#define TOP_RAM1_SF_RST					13
#define TS_SF_RST					12
#define TL420_ICTL_SF_RST				11
#define TOP_DMAG_SF_RST					10
#define TOP_DMAS_SF_RST					9
#define MEMCTL1_SF_RST					8
#define MEMCTL0_SF_RST					7
#define MUXPIN_SF_RST					6
#define GPIO_SF_RST					5
#define TOP_MAIL_BOX_SF_RST				4
#define COM_PCM_SF_RST					3
#define COM_UART_SF_RST					2
#define COM_I2S_SF_RST					1
#define COM_I2C_SF_RST					0

/* DDR_PWR_MEMCTLIFCTL */
#define MEMCTL1_AXI_AWCOBUF				3
#define MEMCTL0_AXI_AWCOBUF				2
#define MEMCTL1_IDDQ_EN					1
#define MEMCTL0_IDDQ_EN					0

/* DDR_PWR_CPCLK26MSEL */
#define FORCE_SEL_CP_CLK26M1				9
#define FORCE_SEL_CLK26M0				8
#define CP_CLK26M_SEL					0

/* DDR_PWR_CDBGPWRUPREQMASK */
#define CDBGPWRUPREQ_HA7_MASK				4
#define CDBGPWRUPREQ_SA7_MASK				3
#define CDBGPWRUPREQ_AP_MASK				2
#define CDBGPWRUPREQ_CPA7_MASK				1
#define CDBGPWRUPREQ_CP_MASK				0

/* DDR_PWR_RESET2 */
#define RESET2_BIT_WE					16
#define CORESIGHT_AP4COREPCLK_SF_RST			7
#define CORESIGHT_AP1COREPCLK_SF_RST			6
#define CORESIGHT_CP1COREPCLK_SF_RST			5
#define CORESIGHT_ATCLK_SF_RST				4
#define CORESIGHT_PCLKDBG_SF_RST			3
#define CORESIGHT_AP4COREATCLK_SF_RST			2
#define CORESIGHT_AP1COREATCLK_SF_RST			1
#define CORESIGHT_CP1COREATCLK_SF_RST			0

/* DDR_PWR_TL420CTL */
#define AP_ACCESS_ERR_MASK				23
#define CP_ACCESS_ERR_MASK				22
#define CP_WDT_RST_MASK					21
#define AP_WDT0_RST_MASK				20
#define AP_WDT1_RST_MASK				19
#define AP_WDT2_RST_MASK				18
#define AP_WDT3_RST_MASK				17
#define AP_WDT4_RST_MASK				16
#define TL420_BOOT					12
#define TL420_TOPFSM_RSTN_LIMIT				8
#define TL420_IDLE					5
#define TL420_WAIT					4
#define TL420_CORE_RECOVERY				3
#define TL420_PSU_CORE_IDLE				2
#define TL420_DBUS_IDLE					1
#define TL420_PBUS_IDLE					0

/* DDR_PWR_APOSCCTL */
#define AP_OSC_ST_TIME_SEL				8
#define AP_OSC_ST_TIME					0

/* DDR_PWR_CPOSCCTL */
#define CP_OSC_ST_TIME_SEL				8
#define CP_OSC_ST_TIME					0

/* DDR_PWR_CPDBGCTL */
#define CPDBG_MK					2
#define CPDBG_EDGE_SEL					1
#define CPDBG_JTAG_SEL					0

/* DDR_PWR_A7GTMCTL */
#define A7GTMCTL_BIT_WE					16
#define CS_HLTDBG_MK					3
#define STATE_CTL					2
#endif /* __ASM_ARCH_REGS_DDR_PWR_H. */
