# Device Driver

obj-y += misc/

# BASE
obj-y += drivers/base/dmas/
obj-y += drivers/base/gpio/
obj-y += drivers/base/i2c/
obj-y += drivers/base/mfp/
obj-y += drivers/base/pwm/
obj-y += drivers/base/reset/
obj-y += drivers/base/spi/
obj-y += drivers/base/timer/
obj-y += drivers/base/uart/
obj-y += drivers/base/mmc/
obj-y += drivers/base/nand/
obj-y += drivers/base/tpz/
obj-y += drivers/base/mets/

# ION
obj-y += drivers/ion/

# DISPLAY
obj-y += drivers/gpu/
obj-y += drivers/2d/
obj-y += drivers/video/
obj-y += drivers/backlight/

# INPUT
obj-y += drivers/keypad/
obj-y += drivers/touchscreen/
obj-y += drivers/sensor/

# LEDS
obj-y += drivers/leds/

# SOUND
obj-y += drivers/sound/

# PMIC
obj-y += drivers/pmic/
obj-y += drivers/rtc/
obj-y += drivers/switch/
obj-y += drivers/powerkey/
obj-y += drivers/vibrator/

# CAMERA
obj-y += drivers/camera/

# WIRELESS Devices
obj-y += drivers/wireless/

# Radio
obj-y += drivers/radio/

# Multimedia
obj-$(CONFIG_ON2_COMIP) += drivers/on2/

# MISC
obj-y += drivers/misc/monitor/
obj-y += drivers/misc/thermal/
obj-y += drivers/misc/ureg/
obj-y += drivers/misc/apanic/

#NET-BIH
obj-y += net/

