obj-$(CONFIG_UMP_MALI400) += mali400/ump/
obj-$(CONFIG_MALI400) += mali400/mali/
obj-$(CONFIG_MALI_DRIVER_MIDGARD_R4) += malit6xx_r4/gpu/arm/
obj-$(CONFIG_MALI_DRIVER_MIDGARD_R5) += malit6xx_r5/gpu/arm/