#
# Makefile for the Leadcore COMIP framebuffer driver
#
CFLAGS_EXTRA += -O0
obj-$(CONFIG_FB_COMIP) += comipfb.o comipfb_hw.o comipfb_dev.o comipfb_if.o comipfb_spi.o mipi_interface.o mipi_cmd.o
#obj-y += comipfb.o comipfb_hw.o comipfb_dev.o comipfb_if.o comipfb_spi.o  mipi_interface.o
obj-$(CONFIG_LCD_BYD_8937S)     += lcd_byd_bm397wv_8937ftgs.o
obj-$(CONFIG_LCD_YT_H8369A)     += lcd_yt_h8369a.o
obj-$(CONFIG_LCD_YT_ILI9805E)   += lcd_yt_ili9805e.o
obj-$(CONFIG_LCD_LEAD_LD35510S)	+= lcd_lead_ld35510s.o
obj-$(CONFIG_LCD_YT_OTM9608)	+= lcd_yt_otm9608.o
obj-$(CONFIG_LCD_TM_NT35516)	+= lcd_tm_nt35516.o
obj-$(CONFIG_LCD_YT_H8389B)	+= lcd_yt_h8389b.o
obj-$(CONFIG_LCD_AUO_ER61308)	+= lcd_auo_eR61308.o
obj-$(CONFIG_LCD_ZET_OTM8009A)	+= lcd_zetrax_otm8009a.o
obj-$(CONFIG_LCD_ZET_SSD2075)	+= lcd_zetrax_ssd2075.o
obj-$(CONFIG_LCD_BOE_H8394A)	+= lcd_boe_h8394a.o
obj-$(CONFIG_LCD_BOE_H8394A01)	+= lcd_boe_h8394a01.o
obj-$(CONFIG_LCD_LEAD_LD35512S)	+= lcd_lead_ld35512s.o
obj-$(CONFIG_LCD_LG_H8379A)     += lcd_lg_h8379a.o
obj-$(CONFIG_LCD_SHP_H8392A)	+= lcd_shp_h8392a.o
obj-$(CONFIG_LCD_TM_NT35520)	+= lcd_tm_nt35520.o
obj-$(CONFIG_LCD_TM_NT35521)	+= lcd_tm_nt35521.o
