obj-$(CONFIG_COMIP_LC1160) += lc1160.o lc1160-pmic.o
obj-$(CONFIG_LC1160_ADC) += lc1160_adc.o lc1160_adc_temperature.o
obj-$(CONFIG_LC1160_MONITOR_BATTERY) += lc1160_monitor_battery.o
obj-$(CONFIG_LC1160_PWM) += lc1160-pwm.o
